// Package rpcapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package rpcapi

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for GearCertificationAuthority.
const (
	GearCertificationAuthorityCcc      GearCertificationAuthority = "ccc"
	GearCertificationAuthorityCe       GearCertificationAuthority = "ce"
	GearCertificationAuthorityFcc      GearCertificationAuthority = "fcc"
	GearCertificationAuthorityInternal GearCertificationAuthority = "internal"
	GearCertificationAuthorityMiit     GearCertificationAuthority = "miit"
	GearCertificationAuthorityRohs     GearCertificationAuthority = "rohs"
	GearCertificationAuthoritySrrc     GearCertificationAuthority = "srrc"
	GearCertificationAuthorityUnknown  GearCertificationAuthority = "unknown"
)

// Valid indicates whether the value is a known member of the GearCertificationAuthority enum.
func (e GearCertificationAuthority) Valid() bool {
	switch e {
	case GearCertificationAuthorityCcc:
		return true
	case GearCertificationAuthorityCe:
		return true
	case GearCertificationAuthorityFcc:
		return true
	case GearCertificationAuthorityInternal:
		return true
	case GearCertificationAuthorityMiit:
		return true
	case GearCertificationAuthorityRohs:
		return true
	case GearCertificationAuthoritySrrc:
		return true
	case GearCertificationAuthorityUnknown:
		return true
	default:
		return false
	}
}

// Defines values for GearCertificationType.
const (
	GearCertificationTypeCertification GearCertificationType = "certification"
	GearCertificationTypeLicense       GearCertificationType = "license"
)

// Valid indicates whether the value is a known member of the GearCertificationType enum.
func (e GearCertificationType) Valid() bool {
	switch e {
	case GearCertificationTypeCertification:
		return true
	case GearCertificationTypeLicense:
		return true
	default:
		return false
	}
}

// Defines values for GearRole.
const (
	GearRoleAdmin       GearRole = "admin"
	GearRoleGear        GearRole = "gear"
	GearRoleServer      GearRole = "server"
	GearRoleUnspecified GearRole = "unspecified"
)

// Valid indicates whether the value is a known member of the GearRole enum.
func (e GearRole) Valid() bool {
	switch e {
	case GearRoleAdmin:
		return true
	case GearRoleGear:
		return true
	case GearRoleServer:
		return true
	case GearRoleUnspecified:
		return true
	default:
		return false
	}
}

// Defines values for GearStatus.
const (
	GearStatusActive      GearStatus = "active"
	GearStatusBlocked     GearStatus = "blocked"
	GearStatusUnspecified GearStatus = "unspecified"
)

// Valid indicates whether the value is a known member of the GearStatus enum.
func (e GearStatus) Valid() bool {
	switch e {
	case GearStatusActive:
		return true
	case GearStatusBlocked:
		return true
	case GearStatusUnspecified:
		return true
	default:
		return false
	}
}

// Defines values for RPCErrorCode.
const (
	RPCErrorCodeBadRequest     RPCErrorCode = 400
	RPCErrorCodeConflict       RPCErrorCode = 409
	RPCErrorCodeInternalError  RPCErrorCode = -32603
	RPCErrorCodeInvalidParams  RPCErrorCode = -32602
	RPCErrorCodeInvalidRequest RPCErrorCode = -32600
	RPCErrorCodeMethodNotFound RPCErrorCode = -32601
	RPCErrorCodeNotFound       RPCErrorCode = 404
)

// Valid indicates whether the value is a known member of the RPCErrorCode enum.
func (e RPCErrorCode) Valid() bool {
	switch e {
	case RPCErrorCodeBadRequest:
		return true
	case RPCErrorCodeConflict:
		return true
	case RPCErrorCodeInternalError:
		return true
	case RPCErrorCodeInvalidParams:
		return true
	case RPCErrorCodeInvalidRequest:
		return true
	case RPCErrorCodeMethodNotFound:
		return true
	case RPCErrorCodeNotFound:
		return true
	default:
		return false
	}
}

// Defines values for RPCMethod.
const (
	RPCMethodGearConfigGet            RPCMethod = "gear.config.get"
	RPCMethodGearInfoGet              RPCMethod = "gear.info.get"
	RPCMethodGearInfoPut              RPCMethod = "gear.info.put"
	RPCMethodGearOtaGet               RPCMethod = "gear.ota.get"
	RPCMethodGearRegistrationGet      RPCMethod = "gear.registration.get"
	RPCMethodGearRegistrationRegister RPCMethod = "gear.registration.register"
	RPCMethodGearRuntimeGet           RPCMethod = "gear.runtime.get"
	RPCMethodPeerPing                 RPCMethod = "peer.ping"
	RPCMethodServerInfoGet            RPCMethod = "server.info.get"
)

// Valid indicates whether the value is a known member of the RPCMethod enum.
func (e RPCMethod) Valid() bool {
	switch e {
	case RPCMethodGearConfigGet:
		return true
	case RPCMethodGearInfoGet:
		return true
	case RPCMethodGearInfoPut:
		return true
	case RPCMethodGearOtaGet:
		return true
	case RPCMethodGearRegistrationGet:
		return true
	case RPCMethodGearRegistrationRegister:
		return true
	case RPCMethodGearRuntimeGet:
		return true
	case RPCMethodPeerPing:
		return true
	case RPCMethodServerInfoGet:
		return true
	default:
		return false
	}
}

// Defines values for RPCVersion.
const (
	RPCVersionV1 RPCVersion = 1
)

// Valid indicates whether the value is a known member of the RPCVersion enum.
func (e RPCVersion) Valid() bool {
	switch e {
	case RPCVersionV1:
		return true
	default:
		return false
	}
}

// Configuration defines model for Configuration.
type Configuration struct {
	Certifications *[]GearCertification `json:"certifications,omitempty"`
	Firmware       *FirmwareConfig      `json:"firmware,omitempty"`
}

// DepotFile defines model for DepotFile.
type DepotFile struct {
	Md5    string `json:"md5"`
	Path   string `json:"path"`
	Sha256 string `json:"sha256"`
}

// DeviceInfo defines model for DeviceInfo.
type DeviceInfo struct {
	Hardware *HardwareInfo `json:"hardware,omitempty"`
	Name     *string       `json:"name,omitempty"`
	Sn       *string       `json:"sn,omitempty"`
}

// FirmwareConfig defines model for FirmwareConfig.
type FirmwareConfig struct {
	Channel *GearFirmwareChannel `json:"channel,omitempty"`
}

// Gear defines model for Gear.
type Gear struct {
	ApprovedAt     *time.Time    `json:"approved_at,omitempty"`
	AutoRegistered *bool         `json:"auto_registered,omitempty"`
	Configuration  Configuration `json:"configuration"`
	CreatedAt      time.Time     `json:"created_at"`
	Device         DeviceInfo    `json:"device"`
	PublicKey      string        `json:"public_key"`
	Role           GearRole      `json:"role"`
	Status         GearStatus    `json:"status"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

// GearCertification defines model for GearCertification.
type GearCertification struct {
	Authority     GearCertificationAuthority `json:"authority"`
	AuthorityName *string                    `json:"authority_name,omitempty"`
	Id            string                     `json:"id"`
	Type          GearCertificationType      `json:"type"`
}

// GearCertificationAuthority defines model for GearCertificationAuthority.
type GearCertificationAuthority string

// GearCertificationType defines model for GearCertificationType.
type GearCertificationType string

// GearFirmwareChannel defines model for GearFirmwareChannel.
type GearFirmwareChannel = string

// GearGetConfigRequest defines model for GearGetConfigRequest.
type GearGetConfigRequest = map[string]interface{}

// GearGetConfigResponse defines model for GearGetConfigResponse.
type GearGetConfigResponse = Configuration

// GearGetInfoRequest defines model for GearGetInfoRequest.
type GearGetInfoRequest = map[string]interface{}

// GearGetInfoResponse defines model for GearGetInfoResponse.
type GearGetInfoResponse = DeviceInfo

// GearGetOTARequest defines model for GearGetOTARequest.
type GearGetOTARequest = map[string]interface{}

// GearGetOTAResponse defines model for GearGetOTAResponse.
type GearGetOTAResponse = OTASummary

// GearGetRegistrationRequest defines model for GearGetRegistrationRequest.
type GearGetRegistrationRequest = map[string]interface{}

// GearGetRegistrationResponse defines model for GearGetRegistrationResponse.
type GearGetRegistrationResponse = Registration

// GearGetRuntimeRequest defines model for GearGetRuntimeRequest.
type GearGetRuntimeRequest = map[string]interface{}

// GearGetRuntimeResponse defines model for GearGetRuntimeResponse.
type GearGetRuntimeResponse = Runtime

// GearIMEI defines model for GearIMEI.
type GearIMEI struct {
	Name   *string `json:"name,omitempty"`
	Serial string  `json:"serial"`
	Tac    string  `json:"tac"`
}

// GearLabel defines model for GearLabel.
type GearLabel struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GearPutInfoRequest defines model for GearPutInfoRequest.
type GearPutInfoRequest = DeviceInfo

// GearPutInfoResponse defines model for GearPutInfoResponse.
type GearPutInfoResponse = DeviceInfo

// GearRegisterRequest defines model for GearRegisterRequest.
type GearRegisterRequest struct {
	Device DeviceInfo `json:"device"`
}

// GearRegisterResponse defines model for GearRegisterResponse.
type GearRegisterResponse struct {
	Gear         Gear         `json:"gear"`
	Registration Registration `json:"registration"`
}

// GearRole defines model for GearRole.
type GearRole string

// GearStatus defines model for GearStatus.
type GearStatus string

// HardwareInfo defines model for HardwareInfo.
type HardwareInfo struct {
	Depot            *string      `json:"depot,omitempty"`
	FirmwareSemver   *string      `json:"firmware_semver,omitempty"`
	HardwareRevision *string      `json:"hardware_revision,omitempty"`
	Imeis            *[]GearIMEI  `json:"imeis,omitempty"`
	Labels           *[]GearLabel `json:"labels,omitempty"`
	Manufacturer     *string      `json:"manufacturer,omitempty"`
	Model            *string      `json:"model,omitempty"`
}

// OTASummary defines model for OTASummary.
type OTASummary struct {
	Channel        string      `json:"channel"`
	Depot          string      `json:"depot"`
	Files          []DepotFile `json:"files"`
	FirmwareSemver string      `json:"firmware_semver"`
}

// PingRequest defines model for PingRequest.
type PingRequest struct {
	ClientSendTime int64 `json:"client_send_time"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	ServerTime int64 `json:"server_time"`
}

// RPCError defines model for RPCError.
type RPCError struct {
	Code    RPCErrorCode `json:"code"`
	Message string       `json:"message"`
}

// RPCErrorCode defines model for RPCErrorCode.
type RPCErrorCode int

// RPCMethod defines model for RPCMethod.
type RPCMethod string

// RPCRequest defines model for RPCRequest.
type RPCRequest struct {
	Id     string             `json:"id"`
	Method RPCMethod          `json:"method"`
	Params *RPCRequest_Params `json:"params,omitempty"`
	V      RPCVersion         `json:"v"`
}

// RPCRequest_Params defines model for RPCRequest.Params.
type RPCRequest_Params struct {
	union json.RawMessage
}

// RPCResponse defines model for RPCResponse.
type RPCResponse struct {
	Error  *RPCError           `json:"error,omitempty"`
	Id     string              `json:"id"`
	Result *RPCResponse_Result `json:"result,omitempty"`
	V      RPCVersion          `json:"v"`
}

// RPCResponse_Result defines model for RPCResponse.Result.
type RPCResponse_Result struct {
	union json.RawMessage
}

// RPCVersion defines model for RPCVersion.
type RPCVersion int

// Registration defines model for Registration.
type Registration struct {
	ApprovedAt     *time.Time `json:"approved_at,omitempty"`
	AutoRegistered *bool      `json:"auto_registered,omitempty"`
	CreatedAt      time.Time  `json:"created_at"`
	PublicKey      string     `json:"public_key"`
	Role           GearRole   `json:"role"`
	Status         GearStatus `json:"status"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

// Runtime defines model for Runtime.
type Runtime struct {
	LastAddr   *string   `json:"last_addr,omitempty"`
	LastSeenAt time.Time `json:"last_seen_at"`
	Online     bool      `json:"online"`
	RxBytes    *uint64   `json:"rx_bytes,omitempty"`
	TxBytes    *uint64   `json:"tx_bytes,omitempty"`
}

// ServerGetInfoRequest defines model for ServerGetInfoRequest.
type ServerGetInfoRequest = map[string]interface{}

// ServerGetInfoResponse defines model for ServerGetInfoResponse.
type ServerGetInfoResponse = ServerInfo

// ServerInfo defines model for ServerInfo.
type ServerInfo struct {
	BuildCommit string `json:"build_commit"`
	PublicKey   string `json:"public_key"`
	ServerTime  int64  `json:"server_time"`
}

// AsPingRequest returns the union data inside the RPCRequest_Params as a PingRequest
func (t RPCRequest_Params) AsPingRequest() (PingRequest, error) {
	var body PingRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPingRequest overwrites any union data inside the RPCRequest_Params as the provided PingRequest
func (t *RPCRequest_Params) FromPingRequest(v PingRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePingRequest performs a merge with any union data inside the RPCRequest_Params, using the provided PingRequest
func (t *RPCRequest_Params) MergePingRequest(v PingRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsServerGetInfoRequest returns the union data inside the RPCRequest_Params as a ServerGetInfoRequest
func (t RPCRequest_Params) AsServerGetInfoRequest() (ServerGetInfoRequest, error) {
	var body ServerGetInfoRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServerGetInfoRequest overwrites any union data inside the RPCRequest_Params as the provided ServerGetInfoRequest
func (t *RPCRequest_Params) FromServerGetInfoRequest(v ServerGetInfoRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServerGetInfoRequest performs a merge with any union data inside the RPCRequest_Params, using the provided ServerGetInfoRequest
func (t *RPCRequest_Params) MergeServerGetInfoRequest(v ServerGetInfoRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearGetConfigRequest returns the union data inside the RPCRequest_Params as a GearGetConfigRequest
func (t RPCRequest_Params) AsGearGetConfigRequest() (GearGetConfigRequest, error) {
	var body GearGetConfigRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearGetConfigRequest overwrites any union data inside the RPCRequest_Params as the provided GearGetConfigRequest
func (t *RPCRequest_Params) FromGearGetConfigRequest(v GearGetConfigRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearGetConfigRequest performs a merge with any union data inside the RPCRequest_Params, using the provided GearGetConfigRequest
func (t *RPCRequest_Params) MergeGearGetConfigRequest(v GearGetConfigRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearGetInfoRequest returns the union data inside the RPCRequest_Params as a GearGetInfoRequest
func (t RPCRequest_Params) AsGearGetInfoRequest() (GearGetInfoRequest, error) {
	var body GearGetInfoRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearGetInfoRequest overwrites any union data inside the RPCRequest_Params as the provided GearGetInfoRequest
func (t *RPCRequest_Params) FromGearGetInfoRequest(v GearGetInfoRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearGetInfoRequest performs a merge with any union data inside the RPCRequest_Params, using the provided GearGetInfoRequest
func (t *RPCRequest_Params) MergeGearGetInfoRequest(v GearGetInfoRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearPutInfoRequest returns the union data inside the RPCRequest_Params as a GearPutInfoRequest
func (t RPCRequest_Params) AsGearPutInfoRequest() (GearPutInfoRequest, error) {
	var body GearPutInfoRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearPutInfoRequest overwrites any union data inside the RPCRequest_Params as the provided GearPutInfoRequest
func (t *RPCRequest_Params) FromGearPutInfoRequest(v GearPutInfoRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearPutInfoRequest performs a merge with any union data inside the RPCRequest_Params, using the provided GearPutInfoRequest
func (t *RPCRequest_Params) MergeGearPutInfoRequest(v GearPutInfoRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearGetOTARequest returns the union data inside the RPCRequest_Params as a GearGetOTARequest
func (t RPCRequest_Params) AsGearGetOTARequest() (GearGetOTARequest, error) {
	var body GearGetOTARequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearGetOTARequest overwrites any union data inside the RPCRequest_Params as the provided GearGetOTARequest
func (t *RPCRequest_Params) FromGearGetOTARequest(v GearGetOTARequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearGetOTARequest performs a merge with any union data inside the RPCRequest_Params, using the provided GearGetOTARequest
func (t *RPCRequest_Params) MergeGearGetOTARequest(v GearGetOTARequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearGetRegistrationRequest returns the union data inside the RPCRequest_Params as a GearGetRegistrationRequest
func (t RPCRequest_Params) AsGearGetRegistrationRequest() (GearGetRegistrationRequest, error) {
	var body GearGetRegistrationRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearGetRegistrationRequest overwrites any union data inside the RPCRequest_Params as the provided GearGetRegistrationRequest
func (t *RPCRequest_Params) FromGearGetRegistrationRequest(v GearGetRegistrationRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearGetRegistrationRequest performs a merge with any union data inside the RPCRequest_Params, using the provided GearGetRegistrationRequest
func (t *RPCRequest_Params) MergeGearGetRegistrationRequest(v GearGetRegistrationRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearRegisterRequest returns the union data inside the RPCRequest_Params as a GearRegisterRequest
func (t RPCRequest_Params) AsGearRegisterRequest() (GearRegisterRequest, error) {
	var body GearRegisterRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearRegisterRequest overwrites any union data inside the RPCRequest_Params as the provided GearRegisterRequest
func (t *RPCRequest_Params) FromGearRegisterRequest(v GearRegisterRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearRegisterRequest performs a merge with any union data inside the RPCRequest_Params, using the provided GearRegisterRequest
func (t *RPCRequest_Params) MergeGearRegisterRequest(v GearRegisterRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearGetRuntimeRequest returns the union data inside the RPCRequest_Params as a GearGetRuntimeRequest
func (t RPCRequest_Params) AsGearGetRuntimeRequest() (GearGetRuntimeRequest, error) {
	var body GearGetRuntimeRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearGetRuntimeRequest overwrites any union data inside the RPCRequest_Params as the provided GearGetRuntimeRequest
func (t *RPCRequest_Params) FromGearGetRuntimeRequest(v GearGetRuntimeRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearGetRuntimeRequest performs a merge with any union data inside the RPCRequest_Params, using the provided GearGetRuntimeRequest
func (t *RPCRequest_Params) MergeGearGetRuntimeRequest(v GearGetRuntimeRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RPCRequest_Params) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RPCRequest_Params) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPingResponse returns the union data inside the RPCResponse_Result as a PingResponse
func (t RPCResponse_Result) AsPingResponse() (PingResponse, error) {
	var body PingResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPingResponse overwrites any union data inside the RPCResponse_Result as the provided PingResponse
func (t *RPCResponse_Result) FromPingResponse(v PingResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePingResponse performs a merge with any union data inside the RPCResponse_Result, using the provided PingResponse
func (t *RPCResponse_Result) MergePingResponse(v PingResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsServerGetInfoResponse returns the union data inside the RPCResponse_Result as a ServerGetInfoResponse
func (t RPCResponse_Result) AsServerGetInfoResponse() (ServerGetInfoResponse, error) {
	var body ServerGetInfoResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServerGetInfoResponse overwrites any union data inside the RPCResponse_Result as the provided ServerGetInfoResponse
func (t *RPCResponse_Result) FromServerGetInfoResponse(v ServerGetInfoResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServerGetInfoResponse performs a merge with any union data inside the RPCResponse_Result, using the provided ServerGetInfoResponse
func (t *RPCResponse_Result) MergeServerGetInfoResponse(v ServerGetInfoResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearGetConfigResponse returns the union data inside the RPCResponse_Result as a GearGetConfigResponse
func (t RPCResponse_Result) AsGearGetConfigResponse() (GearGetConfigResponse, error) {
	var body GearGetConfigResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearGetConfigResponse overwrites any union data inside the RPCResponse_Result as the provided GearGetConfigResponse
func (t *RPCResponse_Result) FromGearGetConfigResponse(v GearGetConfigResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearGetConfigResponse performs a merge with any union data inside the RPCResponse_Result, using the provided GearGetConfigResponse
func (t *RPCResponse_Result) MergeGearGetConfigResponse(v GearGetConfigResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearGetInfoResponse returns the union data inside the RPCResponse_Result as a GearGetInfoResponse
func (t RPCResponse_Result) AsGearGetInfoResponse() (GearGetInfoResponse, error) {
	var body GearGetInfoResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearGetInfoResponse overwrites any union data inside the RPCResponse_Result as the provided GearGetInfoResponse
func (t *RPCResponse_Result) FromGearGetInfoResponse(v GearGetInfoResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearGetInfoResponse performs a merge with any union data inside the RPCResponse_Result, using the provided GearGetInfoResponse
func (t *RPCResponse_Result) MergeGearGetInfoResponse(v GearGetInfoResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearPutInfoResponse returns the union data inside the RPCResponse_Result as a GearPutInfoResponse
func (t RPCResponse_Result) AsGearPutInfoResponse() (GearPutInfoResponse, error) {
	var body GearPutInfoResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearPutInfoResponse overwrites any union data inside the RPCResponse_Result as the provided GearPutInfoResponse
func (t *RPCResponse_Result) FromGearPutInfoResponse(v GearPutInfoResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearPutInfoResponse performs a merge with any union data inside the RPCResponse_Result, using the provided GearPutInfoResponse
func (t *RPCResponse_Result) MergeGearPutInfoResponse(v GearPutInfoResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearGetOTAResponse returns the union data inside the RPCResponse_Result as a GearGetOTAResponse
func (t RPCResponse_Result) AsGearGetOTAResponse() (GearGetOTAResponse, error) {
	var body GearGetOTAResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearGetOTAResponse overwrites any union data inside the RPCResponse_Result as the provided GearGetOTAResponse
func (t *RPCResponse_Result) FromGearGetOTAResponse(v GearGetOTAResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearGetOTAResponse performs a merge with any union data inside the RPCResponse_Result, using the provided GearGetOTAResponse
func (t *RPCResponse_Result) MergeGearGetOTAResponse(v GearGetOTAResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearGetRegistrationResponse returns the union data inside the RPCResponse_Result as a GearGetRegistrationResponse
func (t RPCResponse_Result) AsGearGetRegistrationResponse() (GearGetRegistrationResponse, error) {
	var body GearGetRegistrationResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearGetRegistrationResponse overwrites any union data inside the RPCResponse_Result as the provided GearGetRegistrationResponse
func (t *RPCResponse_Result) FromGearGetRegistrationResponse(v GearGetRegistrationResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearGetRegistrationResponse performs a merge with any union data inside the RPCResponse_Result, using the provided GearGetRegistrationResponse
func (t *RPCResponse_Result) MergeGearGetRegistrationResponse(v GearGetRegistrationResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearRegisterResponse returns the union data inside the RPCResponse_Result as a GearRegisterResponse
func (t RPCResponse_Result) AsGearRegisterResponse() (GearRegisterResponse, error) {
	var body GearRegisterResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearRegisterResponse overwrites any union data inside the RPCResponse_Result as the provided GearRegisterResponse
func (t *RPCResponse_Result) FromGearRegisterResponse(v GearRegisterResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearRegisterResponse performs a merge with any union data inside the RPCResponse_Result, using the provided GearRegisterResponse
func (t *RPCResponse_Result) MergeGearRegisterResponse(v GearRegisterResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGearGetRuntimeResponse returns the union data inside the RPCResponse_Result as a GearGetRuntimeResponse
func (t RPCResponse_Result) AsGearGetRuntimeResponse() (GearGetRuntimeResponse, error) {
	var body GearGetRuntimeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGearGetRuntimeResponse overwrites any union data inside the RPCResponse_Result as the provided GearGetRuntimeResponse
func (t *RPCResponse_Result) FromGearGetRuntimeResponse(v GearGetRuntimeResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGearGetRuntimeResponse performs a merge with any union data inside the RPCResponse_Result, using the provided GearGetRuntimeResponse
func (t *RPCResponse_Result) MergeGearGetRuntimeResponse(v GearGetRuntimeResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RPCResponse_Result) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RPCResponse_Result) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
