// Package rpcapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package rpcapi

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for RPCErrorCode.
const (
	RPCErrorCodeBadRequest     RPCErrorCode = 400
	RPCErrorCodeConflict       RPCErrorCode = 409
	RPCErrorCodeInternalError  RPCErrorCode = -32603
	RPCErrorCodeInvalidParams  RPCErrorCode = -32602
	RPCErrorCodeInvalidRequest RPCErrorCode = -32600
	RPCErrorCodeMethodNotFound RPCErrorCode = -32601
	RPCErrorCodeNotFound       RPCErrorCode = 404
)

// Valid indicates whether the value is a known member of the RPCErrorCode enum.
func (e RPCErrorCode) Valid() bool {
	switch e {
	case RPCErrorCodeBadRequest:
		return true
	case RPCErrorCodeConflict:
		return true
	case RPCErrorCodeInternalError:
		return true
	case RPCErrorCodeInvalidParams:
		return true
	case RPCErrorCodeInvalidRequest:
		return true
	case RPCErrorCodeMethodNotFound:
		return true
	case RPCErrorCodeNotFound:
		return true
	default:
		return false
	}
}

// Defines values for RPCMethod.
const (
	RPCMethodDeviceIdentifiersGet RPCMethod = "device.identifiers.get"
	RPCMethodDeviceInfoGet        RPCMethod = "device.info.get"
	RPCMethodPeerInfoGet          RPCMethod = "peer.info.get"
	RPCMethodPeerInfoPut          RPCMethod = "peer.info.put"
	RPCMethodPeerPing             RPCMethod = "peer.ping"
	RPCMethodPeerRuntimeGet       RPCMethod = "peer.runtime.get"
	RPCMethodServerInfoGet        RPCMethod = "server.info.get"
)

// Valid indicates whether the value is a known member of the RPCMethod enum.
func (e RPCMethod) Valid() bool {
	switch e {
	case RPCMethodDeviceIdentifiersGet:
		return true
	case RPCMethodDeviceInfoGet:
		return true
	case RPCMethodPeerInfoGet:
		return true
	case RPCMethodPeerInfoPut:
		return true
	case RPCMethodPeerPing:
		return true
	case RPCMethodPeerRuntimeGet:
		return true
	case RPCMethodServerInfoGet:
		return true
	default:
		return false
	}
}

// Defines values for RPCVersion.
const (
	RPCVersionV1 RPCVersion = 1
)

// Valid indicates whether the value is a known member of the RPCVersion enum.
func (e RPCVersion) Valid() bool {
	switch e {
	case RPCVersionV1:
		return true
	default:
		return false
	}
}

// DeviceGetIdentifiersRequest defines model for DeviceGetIdentifiersRequest.
type DeviceGetIdentifiersRequest = map[string]interface{}

// DeviceGetIdentifiersResponse defines model for DeviceGetIdentifiersResponse.
type DeviceGetIdentifiersResponse = RefreshIdentifiers

// DeviceGetInfoRequest defines model for DeviceGetInfoRequest.
type DeviceGetInfoRequest = map[string]interface{}

// DeviceGetInfoResponse defines model for DeviceGetInfoResponse.
type DeviceGetInfoResponse = RefreshInfo

// DeviceInfo defines model for DeviceInfo.
type DeviceInfo struct {
	Hardware *HardwareInfo `json:"hardware,omitempty"`
	Name     *string       `json:"name,omitempty"`
	Sn       *string       `json:"sn,omitempty"`
}

// GearIMEI defines model for GearIMEI.
type GearIMEI struct {
	Name   *string `json:"name,omitempty"`
	Serial string  `json:"serial"`
	Tac    string  `json:"tac"`
}

// GearLabel defines model for GearLabel.
type GearLabel struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// HardwareInfo defines model for HardwareInfo.
type HardwareInfo struct {
	HardwareRevision *string      `json:"hardware_revision,omitempty"`
	Imeis            *[]GearIMEI  `json:"imeis,omitempty"`
	Labels           *[]GearLabel `json:"labels,omitempty"`
	Manufacturer     *string      `json:"manufacturer,omitempty"`
	Model            *string      `json:"model,omitempty"`
}

// PeerGetInfoRequest defines model for PeerGetInfoRequest.
type PeerGetInfoRequest = map[string]interface{}

// PeerGetInfoResponse defines model for PeerGetInfoResponse.
type PeerGetInfoResponse = DeviceInfo

// PeerGetRuntimeRequest defines model for PeerGetRuntimeRequest.
type PeerGetRuntimeRequest = map[string]interface{}

// PeerGetRuntimeResponse defines model for PeerGetRuntimeResponse.
type PeerGetRuntimeResponse = Runtime

// PeerPutInfoRequest defines model for PeerPutInfoRequest.
type PeerPutInfoRequest = DeviceInfo

// PeerPutInfoResponse defines model for PeerPutInfoResponse.
type PeerPutInfoResponse = DeviceInfo

// PingRequest defines model for PingRequest.
type PingRequest struct {
	ClientSendTime int64 `json:"client_send_time"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	ServerTime int64 `json:"server_time"`
}

// RPCError defines model for RPCError.
type RPCError struct {
	Code    RPCErrorCode `json:"code"`
	Message string       `json:"message"`
}

// RPCErrorCode defines model for RPCErrorCode.
type RPCErrorCode int

// RPCMethod defines model for RPCMethod.
type RPCMethod string

// RPCRequest defines model for RPCRequest.
type RPCRequest struct {
	Id     string             `json:"id"`
	Method RPCMethod          `json:"method"`
	Params *RPCRequest_Params `json:"params,omitempty"`
	V      RPCVersion         `json:"v"`
}

// RPCRequest_Params defines model for RPCRequest.Params.
type RPCRequest_Params struct {
	union json.RawMessage
}

// RPCResponse defines model for RPCResponse.
type RPCResponse struct {
	Error  *RPCError           `json:"error,omitempty"`
	Id     string              `json:"id"`
	Result *RPCResponse_Result `json:"result,omitempty"`
	V      RPCVersion          `json:"v"`
}

// RPCResponse_Result defines model for RPCResponse.Result.
type RPCResponse_Result struct {
	union json.RawMessage
}

// RPCVersion defines model for RPCVersion.
type RPCVersion int

// RefreshIdentifiers defines model for RefreshIdentifiers.
type RefreshIdentifiers struct {
	Imeis  *[]GearIMEI  `json:"imeis,omitempty"`
	Labels *[]GearLabel `json:"labels,omitempty"`
	Sn     *string      `json:"sn,omitempty"`
}

// RefreshInfo defines model for RefreshInfo.
type RefreshInfo struct {
	HardwareRevision *string `json:"hardware_revision,omitempty"`
	Manufacturer     *string `json:"manufacturer,omitempty"`
	Model            *string `json:"model,omitempty"`
	Name             *string `json:"name,omitempty"`
}

// Runtime defines model for Runtime.
type Runtime struct {
	LastAddr   *string   `json:"last_addr,omitempty"`
	LastSeenAt time.Time `json:"last_seen_at"`
	Online     bool      `json:"online"`
	RxBytes    *uint64   `json:"rx_bytes,omitempty"`
	TxBytes    *uint64   `json:"tx_bytes,omitempty"`
}

// ServerGetInfoRequest defines model for ServerGetInfoRequest.
type ServerGetInfoRequest = map[string]interface{}

// ServerGetInfoResponse defines model for ServerGetInfoResponse.
type ServerGetInfoResponse = ServerInfo

// ServerInfo defines model for ServerInfo.
type ServerInfo struct {
	BuildCommit string `json:"build_commit"`
	PublicKey   string `json:"public_key"`
	ServerTime  int64  `json:"server_time"`
}

// AsPingRequest returns the union data inside the RPCRequest_Params as a PingRequest
func (t RPCRequest_Params) AsPingRequest() (PingRequest, error) {
	var body PingRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPingRequest overwrites any union data inside the RPCRequest_Params as the provided PingRequest
func (t *RPCRequest_Params) FromPingRequest(v PingRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePingRequest performs a merge with any union data inside the RPCRequest_Params, using the provided PingRequest
func (t *RPCRequest_Params) MergePingRequest(v PingRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceGetInfoRequest returns the union data inside the RPCRequest_Params as a DeviceGetInfoRequest
func (t RPCRequest_Params) AsDeviceGetInfoRequest() (DeviceGetInfoRequest, error) {
	var body DeviceGetInfoRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceGetInfoRequest overwrites any union data inside the RPCRequest_Params as the provided DeviceGetInfoRequest
func (t *RPCRequest_Params) FromDeviceGetInfoRequest(v DeviceGetInfoRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceGetInfoRequest performs a merge with any union data inside the RPCRequest_Params, using the provided DeviceGetInfoRequest
func (t *RPCRequest_Params) MergeDeviceGetInfoRequest(v DeviceGetInfoRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceGetIdentifiersRequest returns the union data inside the RPCRequest_Params as a DeviceGetIdentifiersRequest
func (t RPCRequest_Params) AsDeviceGetIdentifiersRequest() (DeviceGetIdentifiersRequest, error) {
	var body DeviceGetIdentifiersRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceGetIdentifiersRequest overwrites any union data inside the RPCRequest_Params as the provided DeviceGetIdentifiersRequest
func (t *RPCRequest_Params) FromDeviceGetIdentifiersRequest(v DeviceGetIdentifiersRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceGetIdentifiersRequest performs a merge with any union data inside the RPCRequest_Params, using the provided DeviceGetIdentifiersRequest
func (t *RPCRequest_Params) MergeDeviceGetIdentifiersRequest(v DeviceGetIdentifiersRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsServerGetInfoRequest returns the union data inside the RPCRequest_Params as a ServerGetInfoRequest
func (t RPCRequest_Params) AsServerGetInfoRequest() (ServerGetInfoRequest, error) {
	var body ServerGetInfoRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServerGetInfoRequest overwrites any union data inside the RPCRequest_Params as the provided ServerGetInfoRequest
func (t *RPCRequest_Params) FromServerGetInfoRequest(v ServerGetInfoRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServerGetInfoRequest performs a merge with any union data inside the RPCRequest_Params, using the provided ServerGetInfoRequest
func (t *RPCRequest_Params) MergeServerGetInfoRequest(v ServerGetInfoRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPeerGetInfoRequest returns the union data inside the RPCRequest_Params as a PeerGetInfoRequest
func (t RPCRequest_Params) AsPeerGetInfoRequest() (PeerGetInfoRequest, error) {
	var body PeerGetInfoRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPeerGetInfoRequest overwrites any union data inside the RPCRequest_Params as the provided PeerGetInfoRequest
func (t *RPCRequest_Params) FromPeerGetInfoRequest(v PeerGetInfoRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePeerGetInfoRequest performs a merge with any union data inside the RPCRequest_Params, using the provided PeerGetInfoRequest
func (t *RPCRequest_Params) MergePeerGetInfoRequest(v PeerGetInfoRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPeerPutInfoRequest returns the union data inside the RPCRequest_Params as a PeerPutInfoRequest
func (t RPCRequest_Params) AsPeerPutInfoRequest() (PeerPutInfoRequest, error) {
	var body PeerPutInfoRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPeerPutInfoRequest overwrites any union data inside the RPCRequest_Params as the provided PeerPutInfoRequest
func (t *RPCRequest_Params) FromPeerPutInfoRequest(v PeerPutInfoRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePeerPutInfoRequest performs a merge with any union data inside the RPCRequest_Params, using the provided PeerPutInfoRequest
func (t *RPCRequest_Params) MergePeerPutInfoRequest(v PeerPutInfoRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPeerGetRuntimeRequest returns the union data inside the RPCRequest_Params as a PeerGetRuntimeRequest
func (t RPCRequest_Params) AsPeerGetRuntimeRequest() (PeerGetRuntimeRequest, error) {
	var body PeerGetRuntimeRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPeerGetRuntimeRequest overwrites any union data inside the RPCRequest_Params as the provided PeerGetRuntimeRequest
func (t *RPCRequest_Params) FromPeerGetRuntimeRequest(v PeerGetRuntimeRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePeerGetRuntimeRequest performs a merge with any union data inside the RPCRequest_Params, using the provided PeerGetRuntimeRequest
func (t *RPCRequest_Params) MergePeerGetRuntimeRequest(v PeerGetRuntimeRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RPCRequest_Params) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RPCRequest_Params) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPingResponse returns the union data inside the RPCResponse_Result as a PingResponse
func (t RPCResponse_Result) AsPingResponse() (PingResponse, error) {
	var body PingResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPingResponse overwrites any union data inside the RPCResponse_Result as the provided PingResponse
func (t *RPCResponse_Result) FromPingResponse(v PingResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePingResponse performs a merge with any union data inside the RPCResponse_Result, using the provided PingResponse
func (t *RPCResponse_Result) MergePingResponse(v PingResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceGetInfoResponse returns the union data inside the RPCResponse_Result as a DeviceGetInfoResponse
func (t RPCResponse_Result) AsDeviceGetInfoResponse() (DeviceGetInfoResponse, error) {
	var body DeviceGetInfoResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceGetInfoResponse overwrites any union data inside the RPCResponse_Result as the provided DeviceGetInfoResponse
func (t *RPCResponse_Result) FromDeviceGetInfoResponse(v DeviceGetInfoResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceGetInfoResponse performs a merge with any union data inside the RPCResponse_Result, using the provided DeviceGetInfoResponse
func (t *RPCResponse_Result) MergeDeviceGetInfoResponse(v DeviceGetInfoResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceGetIdentifiersResponse returns the union data inside the RPCResponse_Result as a DeviceGetIdentifiersResponse
func (t RPCResponse_Result) AsDeviceGetIdentifiersResponse() (DeviceGetIdentifiersResponse, error) {
	var body DeviceGetIdentifiersResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceGetIdentifiersResponse overwrites any union data inside the RPCResponse_Result as the provided DeviceGetIdentifiersResponse
func (t *RPCResponse_Result) FromDeviceGetIdentifiersResponse(v DeviceGetIdentifiersResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceGetIdentifiersResponse performs a merge with any union data inside the RPCResponse_Result, using the provided DeviceGetIdentifiersResponse
func (t *RPCResponse_Result) MergeDeviceGetIdentifiersResponse(v DeviceGetIdentifiersResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsServerGetInfoResponse returns the union data inside the RPCResponse_Result as a ServerGetInfoResponse
func (t RPCResponse_Result) AsServerGetInfoResponse() (ServerGetInfoResponse, error) {
	var body ServerGetInfoResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServerGetInfoResponse overwrites any union data inside the RPCResponse_Result as the provided ServerGetInfoResponse
func (t *RPCResponse_Result) FromServerGetInfoResponse(v ServerGetInfoResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServerGetInfoResponse performs a merge with any union data inside the RPCResponse_Result, using the provided ServerGetInfoResponse
func (t *RPCResponse_Result) MergeServerGetInfoResponse(v ServerGetInfoResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPeerGetInfoResponse returns the union data inside the RPCResponse_Result as a PeerGetInfoResponse
func (t RPCResponse_Result) AsPeerGetInfoResponse() (PeerGetInfoResponse, error) {
	var body PeerGetInfoResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPeerGetInfoResponse overwrites any union data inside the RPCResponse_Result as the provided PeerGetInfoResponse
func (t *RPCResponse_Result) FromPeerGetInfoResponse(v PeerGetInfoResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePeerGetInfoResponse performs a merge with any union data inside the RPCResponse_Result, using the provided PeerGetInfoResponse
func (t *RPCResponse_Result) MergePeerGetInfoResponse(v PeerGetInfoResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPeerPutInfoResponse returns the union data inside the RPCResponse_Result as a PeerPutInfoResponse
func (t RPCResponse_Result) AsPeerPutInfoResponse() (PeerPutInfoResponse, error) {
	var body PeerPutInfoResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPeerPutInfoResponse overwrites any union data inside the RPCResponse_Result as the provided PeerPutInfoResponse
func (t *RPCResponse_Result) FromPeerPutInfoResponse(v PeerPutInfoResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePeerPutInfoResponse performs a merge with any union data inside the RPCResponse_Result, using the provided PeerPutInfoResponse
func (t *RPCResponse_Result) MergePeerPutInfoResponse(v PeerPutInfoResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPeerGetRuntimeResponse returns the union data inside the RPCResponse_Result as a PeerGetRuntimeResponse
func (t RPCResponse_Result) AsPeerGetRuntimeResponse() (PeerGetRuntimeResponse, error) {
	var body PeerGetRuntimeResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPeerGetRuntimeResponse overwrites any union data inside the RPCResponse_Result as the provided PeerGetRuntimeResponse
func (t *RPCResponse_Result) FromPeerGetRuntimeResponse(v PeerGetRuntimeResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePeerGetRuntimeResponse performs a merge with any union data inside the RPCResponse_Result, using the provided PeerGetRuntimeResponse
func (t *RPCResponse_Result) MergePeerGetRuntimeResponse(v PeerGetRuntimeResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RPCResponse_Result) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RPCResponse_Result) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
