package apitypes

// Code generated by go run ./internal/apitypesgen; DO NOT EDIT.

//go:generate go run ./internal/apitypesgen -resolve
//go:generate go tool oapi-codegen -config=codegen_config.yaml -o generated.go types_resolved.json
