package rpcgen

import "bytes"

func emitGeneratedH(model Model) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(cHeader())
	b.WriteString("#ifndef GZC_RPC_GENERATED_H\n#define GZC_RPC_GENERATED_H\n\n")
	b.WriteString("#include \"gzc_rpc_methods.h\"\n")
	b.WriteString("#include \"gzc_rpc_types.h\"\n")
	b.WriteString("#include \"gzc_rpc_encode.h\"\n")
	b.WriteString("#include \"gzc_rpc_decode.h\"\n\n")
	b.WriteString("#endif\n")
	return b.Bytes(), nil
}

func emitReadme(model Model) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("# Generated GizClaw C RPC Bindings\n\n")
	b.WriteString("This directory is generated by `tools/gzc-rpcgen`. Do not edit generated files by hand.\n\n")
	b.WriteString("Regenerate from the repository root with:\n\n")
	b.WriteString("```sh\n")
	b.WriteString("go run ./tools/gzc-rpcgen -schema api/rpc.json -include api -out sdk/c/gizclaw/generated -package gzc -format\n")
	b.WriteString("```\n\n")
	b.WriteString("Generated files depend only on the C SDK runtime headers under `sdk/c/gizclaw/include`.\n")
	_ = model
	return b.Bytes(), nil
}
