// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apitypes

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ACLPermission.
const (
	ACLPermissionBadgeAdmin         ACLPermission = "badge.admin"
	ACLPermissionBadgeRead          ACLPermission = "badge.read"
	ACLPermissionBadgeUse           ACLPermission = "badge.use"
	ACLPermissionContactAdmin       ACLPermission = "contact.admin"
	ACLPermissionContactRead        ACLPermission = "contact.read"
	ACLPermissionContactUse         ACLPermission = "contact.use"
	ACLPermissionCredentialAdmin    ACLPermission = "credential.admin"
	ACLPermissionCredentialRead     ACLPermission = "credential.read"
	ACLPermissionCredentialUse      ACLPermission = "credential.use"
	ACLPermissionEditor             ACLPermission = "editor"
	ACLPermissionFirmwareAdmin      ACLPermission = "firmware.admin"
	ACLPermissionFirmwareRead       ACLPermission = "firmware.read"
	ACLPermissionFriendAdmin        ACLPermission = "friend.admin"
	ACLPermissionFriendGroupAdmin   ACLPermission = "friend_group.admin"
	ACLPermissionFriendGroupRead    ACLPermission = "friend_group.read"
	ACLPermissionFriendGroupUse     ACLPermission = "friend_group.use"
	ACLPermissionFriendRead         ACLPermission = "friend.read"
	ACLPermissionFriendRequestAdmin ACLPermission = "friend_request.admin"
	ACLPermissionFriendRequestRead  ACLPermission = "friend_request.read"
	ACLPermissionFriendRequestUse   ACLPermission = "friend_request.use"
	ACLPermissionFriendUse          ACLPermission = "friend.use"
	ACLPermissionModelAdmin         ACLPermission = "model.admin"
	ACLPermissionModelRead          ACLPermission = "model.read"
	ACLPermissionModelUse           ACLPermission = "model.use"
	ACLPermissionOwner              ACLPermission = "owner"
	ACLPermissionPetSpeciesAdmin    ACLPermission = "pet_species.admin"
	ACLPermissionPetSpeciesRead     ACLPermission = "pet_species.read"
	ACLPermissionPetSpeciesUse      ACLPermission = "pet_species.use"
	ACLPermissionViewAdmin          ACLPermission = "view.admin"
	ACLPermissionViewRead           ACLPermission = "view.read"
	ACLPermissionViewUse            ACLPermission = "view.use"
	ACLPermissionViewer             ACLPermission = "viewer"
	ACLPermissionVoiceAdmin         ACLPermission = "voice.admin"
	ACLPermissionVoiceRead          ACLPermission = "voice.read"
	ACLPermissionVoiceUse           ACLPermission = "voice.use"
	ACLPermissionWorkflowAdmin      ACLPermission = "workflow.admin"
	ACLPermissionWorkflowRead       ACLPermission = "workflow.read"
	ACLPermissionWorkflowUse        ACLPermission = "workflow.use"
	ACLPermissionWorkspaceAdmin     ACLPermission = "workspace.admin"
	ACLPermissionWorkspaceRead      ACLPermission = "workspace.read"
	ACLPermissionWorkspaceUse       ACLPermission = "workspace.use"
)

// Valid indicates whether the value is a known member of the ACLPermission enum.
func (e ACLPermission) Valid() bool {
	switch e {
	case ACLPermissionBadgeAdmin:
		return true
	case ACLPermissionBadgeRead:
		return true
	case ACLPermissionBadgeUse:
		return true
	case ACLPermissionContactAdmin:
		return true
	case ACLPermissionContactRead:
		return true
	case ACLPermissionContactUse:
		return true
	case ACLPermissionCredentialAdmin:
		return true
	case ACLPermissionCredentialRead:
		return true
	case ACLPermissionCredentialUse:
		return true
	case ACLPermissionEditor:
		return true
	case ACLPermissionFirmwareAdmin:
		return true
	case ACLPermissionFirmwareRead:
		return true
	case ACLPermissionFriendAdmin:
		return true
	case ACLPermissionFriendGroupAdmin:
		return true
	case ACLPermissionFriendGroupRead:
		return true
	case ACLPermissionFriendGroupUse:
		return true
	case ACLPermissionFriendRead:
		return true
	case ACLPermissionFriendRequestAdmin:
		return true
	case ACLPermissionFriendRequestRead:
		return true
	case ACLPermissionFriendRequestUse:
		return true
	case ACLPermissionFriendUse:
		return true
	case ACLPermissionModelAdmin:
		return true
	case ACLPermissionModelRead:
		return true
	case ACLPermissionModelUse:
		return true
	case ACLPermissionOwner:
		return true
	case ACLPermissionPetSpeciesAdmin:
		return true
	case ACLPermissionPetSpeciesRead:
		return true
	case ACLPermissionPetSpeciesUse:
		return true
	case ACLPermissionViewAdmin:
		return true
	case ACLPermissionViewRead:
		return true
	case ACLPermissionViewUse:
		return true
	case ACLPermissionViewer:
		return true
	case ACLPermissionVoiceAdmin:
		return true
	case ACLPermissionVoiceRead:
		return true
	case ACLPermissionVoiceUse:
		return true
	case ACLPermissionWorkflowAdmin:
		return true
	case ACLPermissionWorkflowRead:
		return true
	case ACLPermissionWorkflowUse:
		return true
	case ACLPermissionWorkspaceAdmin:
		return true
	case ACLPermissionWorkspaceRead:
		return true
	case ACLPermissionWorkspaceUse:
		return true
	default:
		return false
	}
}

// Defines values for ACLPolicyBindingResourceKind.
const (
	ACLPolicyBindingResourceKindACLPolicyBinding ACLPolicyBindingResourceKind = "ACLPolicyBinding"
)

// Valid indicates whether the value is a known member of the ACLPolicyBindingResourceKind enum.
func (e ACLPolicyBindingResourceKind) Valid() bool {
	switch e {
	case ACLPolicyBindingResourceKindACLPolicyBinding:
		return true
	default:
		return false
	}
}

// Defines values for ACLResourceKind.
const (
	ACLResourceKindBadge         ACLResourceKind = "badge"
	ACLResourceKindContact       ACLResourceKind = "contact"
	ACLResourceKindCredential    ACLResourceKind = "credential"
	ACLResourceKindFirmware      ACLResourceKind = "firmware"
	ACLResourceKindFriend        ACLResourceKind = "friend"
	ACLResourceKindFriendGroup   ACLResourceKind = "friend_group"
	ACLResourceKindFriendRequest ACLResourceKind = "friend_request"
	ACLResourceKindModel         ACLResourceKind = "model"
	ACLResourceKindPetSpecies    ACLResourceKind = "pet_species"
	ACLResourceKindView          ACLResourceKind = "view"
	ACLResourceKindVoice         ACLResourceKind = "voice"
	ACLResourceKindWorkflow      ACLResourceKind = "workflow"
	ACLResourceKindWorkspace     ACLResourceKind = "workspace"
)

// Valid indicates whether the value is a known member of the ACLResourceKind enum.
func (e ACLResourceKind) Valid() bool {
	switch e {
	case ACLResourceKindBadge:
		return true
	case ACLResourceKindContact:
		return true
	case ACLResourceKindCredential:
		return true
	case ACLResourceKindFirmware:
		return true
	case ACLResourceKindFriend:
		return true
	case ACLResourceKindFriendGroup:
		return true
	case ACLResourceKindFriendRequest:
		return true
	case ACLResourceKindModel:
		return true
	case ACLResourceKindPetSpecies:
		return true
	case ACLResourceKindView:
		return true
	case ACLResourceKindVoice:
		return true
	case ACLResourceKindWorkflow:
		return true
	case ACLResourceKindWorkspace:
		return true
	default:
		return false
	}
}

// Defines values for ACLRoleResourceKind.
const (
	ACLRoleResourceKindACLRole ACLRoleResourceKind = "ACLRole"
)

// Valid indicates whether the value is a known member of the ACLRoleResourceKind enum.
func (e ACLRoleResourceKind) Valid() bool {
	switch e {
	case ACLRoleResourceKindACLRole:
		return true
	default:
		return false
	}
}

// Defines values for ACLSubjectKind.
const (
	ACLSubjectKindAllPeers ACLSubjectKind = "all_peers"
	ACLSubjectKindPk       ACLSubjectKind = "pk"
	ACLSubjectKindView     ACLSubjectKind = "view"
)

// Valid indicates whether the value is a known member of the ACLSubjectKind enum.
func (e ACLSubjectKind) Valid() bool {
	switch e {
	case ACLSubjectKindAllPeers:
		return true
	case ACLSubjectKindPk:
		return true
	case ACLSubjectKindView:
		return true
	default:
		return false
	}
}

// Defines values for ACLViewResourceKind.
const (
	ACLViewResourceKindACLView ACLViewResourceKind = "ACLView"
)

// Valid indicates whether the value is a known member of the ACLViewResourceKind enum.
func (e ACLViewResourceKind) Valid() bool {
	switch e {
	case ACLViewResourceKindACLView:
		return true
	default:
		return false
	}
}

// Defines values for ApplyAction.
const (
	ApplyActionApplied   ApplyAction = "applied"
	ApplyActionCreated   ApplyAction = "created"
	ApplyActionUnchanged ApplyAction = "unchanged"
	ApplyActionUpdated   ApplyAction = "updated"
)

// Valid indicates whether the value is a known member of the ApplyAction enum.
func (e ApplyAction) Valid() bool {
	switch e {
	case ApplyActionApplied:
		return true
	case ApplyActionCreated:
		return true
	case ApplyActionUnchanged:
		return true
	case ApplyActionUpdated:
		return true
	default:
		return false
	}
}

// Defines values for BadgeResourceKind.
const (
	BadgeResourceKindBadge BadgeResourceKind = "Badge"
)

// Valid indicates whether the value is a known member of the BadgeResourceKind enum.
func (e BadgeResourceKind) Valid() bool {
	switch e {
	case BadgeResourceKindBadge:
		return true
	default:
		return false
	}
}

// Defines values for CredentialResourceKind.
const (
	CredentialResourceKindCredential CredentialResourceKind = "Credential"
)

// Valid indicates whether the value is a known member of the CredentialResourceKind enum.
func (e CredentialResourceKind) Valid() bool {
	switch e {
	case CredentialResourceKindCredential:
		return true
	default:
		return false
	}
}

// Defines values for DashScopeTenantModelProviderDataApiMode.
const (
	DashScopeTenantModelProviderDataApiModeChatCompletions DashScopeTenantModelProviderDataApiMode = "chat_completions"
	DashScopeTenantModelProviderDataApiModeRealtime        DashScopeTenantModelProviderDataApiMode = "realtime"
)

// Valid indicates whether the value is a known member of the DashScopeTenantModelProviderDataApiMode enum.
func (e DashScopeTenantModelProviderDataApiMode) Valid() bool {
	switch e {
	case DashScopeTenantModelProviderDataApiModeChatCompletions:
		return true
	case DashScopeTenantModelProviderDataApiModeRealtime:
		return true
	default:
		return false
	}
}

// Defines values for DashScopeTenantResourceKind.
const (
	DashScopeTenantResourceKindDashScopeTenant DashScopeTenantResourceKind = "DashScopeTenant"
)

// Valid indicates whether the value is a known member of the DashScopeTenantResourceKind enum.
func (e DashScopeTenantResourceKind) Valid() bool {
	switch e {
	case DashScopeTenantResourceKindDashScopeTenant:
		return true
	default:
		return false
	}
}

// Defines values for FirmwareArtifactKind.
const (
	FirmwareArtifactKindApp  FirmwareArtifactKind = "app"
	FirmwareArtifactKindData FirmwareArtifactKind = "data"
)

// Valid indicates whether the value is a known member of the FirmwareArtifactKind enum.
func (e FirmwareArtifactKind) Valid() bool {
	switch e {
	case FirmwareArtifactKindApp:
		return true
	case FirmwareArtifactKindData:
		return true
	default:
		return false
	}
}

// Defines values for FirmwareResourceKind.
const (
	FirmwareResourceKindFirmware FirmwareResourceKind = "Firmware"
)

// Valid indicates whether the value is a known member of the FirmwareResourceKind enum.
func (e FirmwareResourceKind) Valid() bool {
	switch e {
	case FirmwareResourceKindFirmware:
		return true
	default:
		return false
	}
}

// Defines values for FirmwareSelectionChannel.
const (
	FirmwareSelectionChannelBeta    FirmwareSelectionChannel = "beta"
	FirmwareSelectionChannelDevelop FirmwareSelectionChannel = "develop"
	FirmwareSelectionChannelPending FirmwareSelectionChannel = "pending"
	FirmwareSelectionChannelStable  FirmwareSelectionChannel = "stable"
)

// Valid indicates whether the value is a known member of the FirmwareSelectionChannel enum.
func (e FirmwareSelectionChannel) Valid() bool {
	switch e {
	case FirmwareSelectionChannelBeta:
		return true
	case FirmwareSelectionChannelDevelop:
		return true
	case FirmwareSelectionChannelPending:
		return true
	case FirmwareSelectionChannelStable:
		return true
	default:
		return false
	}
}

// Defines values for FlowcraftWorkflowKind.
const (
	FlowcraftWorkflowKindFlowcraftWorkflow FlowcraftWorkflowKind = "FlowcraftWorkflow"
)

// Valid indicates whether the value is a known member of the FlowcraftWorkflowKind enum.
func (e FlowcraftWorkflowKind) Valid() bool {
	switch e {
	case FlowcraftWorkflowKindFlowcraftWorkflow:
		return true
	default:
		return false
	}
}

// Defines values for GeminiTenantResourceKind.
const (
	GeminiTenantResourceKindGeminiTenant GeminiTenantResourceKind = "GeminiTenant"
)

// Valid indicates whether the value is a known member of the GeminiTenantResourceKind enum.
func (e GeminiTenantResourceKind) Valid() bool {
	switch e {
	case GeminiTenantResourceKindGeminiTenant:
		return true
	default:
		return false
	}
}

// Defines values for MiniMaxTenantResourceKind.
const (
	MiniMaxTenantResourceKindMiniMaxTenant MiniMaxTenantResourceKind = "MiniMaxTenant"
)

// Valid indicates whether the value is a known member of the MiniMaxTenantResourceKind enum.
func (e MiniMaxTenantResourceKind) Valid() bool {
	switch e {
	case MiniMaxTenantResourceKindMiniMaxTenant:
		return true
	default:
		return false
	}
}

// Defines values for ModelKind.
const (
	ModelKindAsr       ModelKind = "asr"
	ModelKindEmbedding ModelKind = "embedding"
	ModelKindLlm       ModelKind = "llm"
	ModelKindRealtime  ModelKind = "realtime"
	ModelKindTts       ModelKind = "tts"
)

// Valid indicates whether the value is a known member of the ModelKind enum.
func (e ModelKind) Valid() bool {
	switch e {
	case ModelKindAsr:
		return true
	case ModelKindEmbedding:
		return true
	case ModelKindLlm:
		return true
	case ModelKindRealtime:
		return true
	case ModelKindTts:
		return true
	default:
		return false
	}
}

// Defines values for ModelProviderKind.
const (
	ModelProviderKindDashscopeTenant ModelProviderKind = "dashscope-tenant"
	ModelProviderKindGeminiTenant    ModelProviderKind = "gemini-tenant"
	ModelProviderKindOpenaiTenant    ModelProviderKind = "openai-tenant"
	ModelProviderKindVolcTenant      ModelProviderKind = "volc-tenant"
)

// Valid indicates whether the value is a known member of the ModelProviderKind enum.
func (e ModelProviderKind) Valid() bool {
	switch e {
	case ModelProviderKindDashscopeTenant:
		return true
	case ModelProviderKindGeminiTenant:
		return true
	case ModelProviderKindOpenaiTenant:
		return true
	case ModelProviderKindVolcTenant:
		return true
	default:
		return false
	}
}

// Defines values for ModelResourceKind.
const (
	ModelResourceKindModel ModelResourceKind = "Model"
)

// Valid indicates whether the value is a known member of the ModelResourceKind enum.
func (e ModelResourceKind) Valid() bool {
	switch e {
	case ModelResourceKindModel:
		return true
	default:
		return false
	}
}

// Defines values for ModelSource.
const (
	ModelSourceManual ModelSource = "manual"
	ModelSourceSync   ModelSource = "sync"
)

// Valid indicates whether the value is a known member of the ModelSource enum.
func (e ModelSource) Valid() bool {
	switch e {
	case ModelSourceManual:
		return true
	case ModelSourceSync:
		return true
	default:
		return false
	}
}

// Defines values for OpenAITenantAPIMode.
const (
	OpenAITenantAPIModeChatCompletions OpenAITenantAPIMode = "chat_completions"
)

// Valid indicates whether the value is a known member of the OpenAITenantAPIMode enum.
func (e OpenAITenantAPIMode) Valid() bool {
	switch e {
	case OpenAITenantAPIModeChatCompletions:
		return true
	default:
		return false
	}
}

// Defines values for OpenAITenantKind.
const (
	OpenAITenantKindAzure      OpenAITenantKind = "azure"
	OpenAITenantKindCompatible OpenAITenantKind = "compatible"
	OpenAITenantKindOpenai     OpenAITenantKind = "openai"
)

// Valid indicates whether the value is a known member of the OpenAITenantKind enum.
func (e OpenAITenantKind) Valid() bool {
	switch e {
	case OpenAITenantKindAzure:
		return true
	case OpenAITenantKindCompatible:
		return true
	case OpenAITenantKindOpenai:
		return true
	default:
		return false
	}
}

// Defines values for OpenAITenantResourceKind.
const (
	OpenAITenantResourceKindOpenAITenant OpenAITenantResourceKind = "OpenAITenant"
)

// Valid indicates whether the value is a known member of the OpenAITenantResourceKind enum.
func (e OpenAITenantResourceKind) Valid() bool {
	switch e {
	case OpenAITenantResourceKindOpenAITenant:
		return true
	default:
		return false
	}
}

// Defines values for PeerConfigResourceKind.
const (
	PeerConfigResourceKindPeerConfig PeerConfigResourceKind = "PeerConfig"
)

// Valid indicates whether the value is a known member of the PeerConfigResourceKind enum.
func (e PeerConfigResourceKind) Valid() bool {
	switch e {
	case PeerConfigResourceKindPeerConfig:
		return true
	default:
		return false
	}
}

// Defines values for PeerRegistrationStatus.
const (
	PeerRegistrationStatusActive      PeerRegistrationStatus = "active"
	PeerRegistrationStatusBlocked     PeerRegistrationStatus = "blocked"
	PeerRegistrationStatusUnspecified PeerRegistrationStatus = "unspecified"
)

// Valid indicates whether the value is a known member of the PeerRegistrationStatus enum.
func (e PeerRegistrationStatus) Valid() bool {
	switch e {
	case PeerRegistrationStatusActive:
		return true
	case PeerRegistrationStatusBlocked:
		return true
	case PeerRegistrationStatusUnspecified:
		return true
	default:
		return false
	}
}

// Defines values for PeerRole.
const (
	PeerRoleAdmin       PeerRole = "admin"
	PeerRoleClient      PeerRole = "client"
	PeerRoleServer      PeerRole = "server"
	PeerRoleUnspecified PeerRole = "unspecified"
)

// Valid indicates whether the value is a known member of the PeerRole enum.
func (e PeerRole) Valid() bool {
	switch e {
	case PeerRoleAdmin:
		return true
	case PeerRoleClient:
		return true
	case PeerRoleServer:
		return true
	case PeerRoleUnspecified:
		return true
	default:
		return false
	}
}

// Defines values for PeerRunStatusState.
const (
	PeerRunStatusStateError    PeerRunStatusState = "error"
	PeerRunStatusStateRunning  PeerRunStatusState = "running"
	PeerRunStatusStateStarting PeerRunStatusState = "starting"
	PeerRunStatusStateStopped  PeerRunStatusState = "stopped"
	PeerRunStatusStateStopping PeerRunStatusState = "stopping"
)

// Valid indicates whether the value is a known member of the PeerRunStatusState enum.
func (e PeerRunStatusState) Valid() bool {
	switch e {
	case PeerRunStatusStateError:
		return true
	case PeerRunStatusStateRunning:
		return true
	case PeerRunStatusStateStarting:
		return true
	case PeerRunStatusStateStopped:
		return true
	case PeerRunStatusStateStopping:
		return true
	default:
		return false
	}
}

// Defines values for PeerStreamEventType.
const (
	PeerStreamEventTypeBos       PeerStreamEventType = "bos"
	PeerStreamEventTypeEos       PeerStreamEventType = "eos"
	PeerStreamEventTypeTextDelta PeerStreamEventType = "text.delta"
	PeerStreamEventTypeTextDone  PeerStreamEventType = "text.done"
)

// Valid indicates whether the value is a known member of the PeerStreamEventType enum.
func (e PeerStreamEventType) Valid() bool {
	switch e {
	case PeerStreamEventTypeBos:
		return true
	case PeerStreamEventTypeEos:
		return true
	case PeerStreamEventTypeTextDelta:
		return true
	case PeerStreamEventTypeTextDone:
		return true
	default:
		return false
	}
}

// Defines values for PeerStreamKind.
const (
	PeerStreamKindAudio PeerStreamKind = "audio"
	PeerStreamKindMixed PeerStreamKind = "mixed"
	PeerStreamKindText  PeerStreamKind = "text"
	PeerStreamKindVideo PeerStreamKind = "video"
)

// Valid indicates whether the value is a known member of the PeerStreamKind enum.
func (e PeerStreamKind) Valid() bool {
	switch e {
	case PeerStreamKindAudio:
		return true
	case PeerStreamKindMixed:
		return true
	case PeerStreamKindText:
		return true
	case PeerStreamKindVideo:
		return true
	default:
		return false
	}
}

// Defines values for PetSpeciesResourceKind.
const (
	PetSpeciesResourceKindPetSpecies PetSpeciesResourceKind = "PetSpecies"
)

// Valid indicates whether the value is a known member of the PetSpeciesResourceKind enum.
func (e PetSpeciesResourceKind) Valid() bool {
	switch e {
	case PetSpeciesResourceKindPetSpecies:
		return true
	default:
		return false
	}
}

// Defines values for ProviderKind.
const (
	ProviderKindDashscopeTenant ProviderKind = "dashscope-tenant"
	ProviderKindGeminiTenant    ProviderKind = "gemini-tenant"
	ProviderKindMinimaxTenant   ProviderKind = "minimax-tenant"
	ProviderKindOpenaiTenant    ProviderKind = "openai-tenant"
	ProviderKindVolcTenant      ProviderKind = "volc-tenant"
)

// Valid indicates whether the value is a known member of the ProviderKind enum.
func (e ProviderKind) Valid() bool {
	switch e {
	case ProviderKindDashscopeTenant:
		return true
	case ProviderKindGeminiTenant:
		return true
	case ProviderKindMinimaxTenant:
		return true
	case ProviderKindOpenaiTenant:
		return true
	case ProviderKindVolcTenant:
		return true
	default:
		return false
	}
}

// Defines values for ResourceAPIVersion.
const (
	ResourceAPIVersionGizclawAdminv1alpha1 ResourceAPIVersion = "gizclaw.admin/v1alpha1"
)

// Valid indicates whether the value is a known member of the ResourceAPIVersion enum.
func (e ResourceAPIVersion) Valid() bool {
	switch e {
	case ResourceAPIVersionGizclawAdminv1alpha1:
		return true
	default:
		return false
	}
}

// Defines values for ResourceKind.
const (
	ResourceKindACLPolicyBinding ResourceKind = "ACLPolicyBinding"
	ResourceKindACLRole          ResourceKind = "ACLRole"
	ResourceKindACLView          ResourceKind = "ACLView"
	ResourceKindBadge            ResourceKind = "Badge"
	ResourceKindCredential       ResourceKind = "Credential"
	ResourceKindDashScopeTenant  ResourceKind = "DashScopeTenant"
	ResourceKindFirmware         ResourceKind = "Firmware"
	ResourceKindGeminiTenant     ResourceKind = "GeminiTenant"
	ResourceKindMiniMaxTenant    ResourceKind = "MiniMaxTenant"
	ResourceKindModel            ResourceKind = "Model"
	ResourceKindOpenAITenant     ResourceKind = "OpenAITenant"
	ResourceKindPeerConfig       ResourceKind = "PeerConfig"
	ResourceKindPetSpecies       ResourceKind = "PetSpecies"
	ResourceKindResourceList     ResourceKind = "ResourceList"
	ResourceKindVoice            ResourceKind = "Voice"
	ResourceKindVolcTenant       ResourceKind = "VolcTenant"
	ResourceKindWorkflow         ResourceKind = "Workflow"
	ResourceKindWorkspace        ResourceKind = "Workspace"
)

// Valid indicates whether the value is a known member of the ResourceKind enum.
func (e ResourceKind) Valid() bool {
	switch e {
	case ResourceKindACLPolicyBinding:
		return true
	case ResourceKindACLRole:
		return true
	case ResourceKindACLView:
		return true
	case ResourceKindBadge:
		return true
	case ResourceKindCredential:
		return true
	case ResourceKindDashScopeTenant:
		return true
	case ResourceKindFirmware:
		return true
	case ResourceKindGeminiTenant:
		return true
	case ResourceKindMiniMaxTenant:
		return true
	case ResourceKindModel:
		return true
	case ResourceKindOpenAITenant:
		return true
	case ResourceKindPeerConfig:
		return true
	case ResourceKindPetSpecies:
		return true
	case ResourceKindResourceList:
		return true
	case ResourceKindVoice:
		return true
	case ResourceKindVolcTenant:
		return true
	case ResourceKindWorkflow:
		return true
	case ResourceKindWorkspace:
		return true
	default:
		return false
	}
}

// Defines values for ResourceListResourceKind.
const (
	ResourceListResourceKindResourceList ResourceListResourceKind = "ResourceList"
)

// Valid indicates whether the value is a known member of the ResourceListResourceKind enum.
func (e ResourceListResourceKind) Valid() bool {
	switch e {
	case ResourceListResourceKindResourceList:
		return true
	default:
		return false
	}
}

// Defines values for VoiceProviderKind.
const (
	VoiceProviderKindDashscopeTenant VoiceProviderKind = "dashscope-tenant"
	VoiceProviderKindGeminiTenant    VoiceProviderKind = "gemini-tenant"
	VoiceProviderKindMinimaxTenant   VoiceProviderKind = "minimax-tenant"
	VoiceProviderKindOpenaiTenant    VoiceProviderKind = "openai-tenant"
	VoiceProviderKindVolcTenant      VoiceProviderKind = "volc-tenant"
)

// Valid indicates whether the value is a known member of the VoiceProviderKind enum.
func (e VoiceProviderKind) Valid() bool {
	switch e {
	case VoiceProviderKindDashscopeTenant:
		return true
	case VoiceProviderKindGeminiTenant:
		return true
	case VoiceProviderKindMinimaxTenant:
		return true
	case VoiceProviderKindOpenaiTenant:
		return true
	case VoiceProviderKindVolcTenant:
		return true
	default:
		return false
	}
}

// Defines values for VoiceResourceKind.
const (
	VoiceResourceKindVoice VoiceResourceKind = "Voice"
)

// Valid indicates whether the value is a known member of the VoiceResourceKind enum.
func (e VoiceResourceKind) Valid() bool {
	switch e {
	case VoiceResourceKindVoice:
		return true
	default:
		return false
	}
}

// Defines values for VoiceSource.
const (
	VoiceSourceManual VoiceSource = "manual"
	VoiceSourceSync   VoiceSource = "sync"
)

// Valid indicates whether the value is a known member of the VoiceSource enum.
func (e VoiceSource) Valid() bool {
	switch e {
	case VoiceSourceManual:
		return true
	case VoiceSourceSync:
		return true
	default:
		return false
	}
}

// Defines values for VolcTenantModelProviderDataApiMode.
const (
	VolcTenantModelProviderDataApiModeAsr      VolcTenantModelProviderDataApiMode = "asr"
	VolcTenantModelProviderDataApiModeRealtime VolcTenantModelProviderDataApiMode = "realtime"
	VolcTenantModelProviderDataApiModeTts      VolcTenantModelProviderDataApiMode = "tts"
)

// Valid indicates whether the value is a known member of the VolcTenantModelProviderDataApiMode enum.
func (e VolcTenantModelProviderDataApiMode) Valid() bool {
	switch e {
	case VolcTenantModelProviderDataApiModeAsr:
		return true
	case VolcTenantModelProviderDataApiModeRealtime:
		return true
	case VolcTenantModelProviderDataApiModeTts:
		return true
	default:
		return false
	}
}

// Defines values for VolcTenantResourceKind.
const (
	VolcTenantResourceKindVolcTenant VolcTenantResourceKind = "VolcTenant"
)

// Valid indicates whether the value is a known member of the VolcTenantResourceKind enum.
func (e VolcTenantResourceKind) Valid() bool {
	switch e {
	case VolcTenantResourceKindVolcTenant:
		return true
	default:
		return false
	}
}

// Defines values for WorkflowAPIVersion.
const (
	WorkflowAPIVersionGizclawFlowcraftv1alpha1 WorkflowAPIVersion = "gizclaw.flowcraft/v1alpha1"
)

// Valid indicates whether the value is a known member of the WorkflowAPIVersion enum.
func (e WorkflowAPIVersion) Valid() bool {
	switch e {
	case WorkflowAPIVersionGizclawFlowcraftv1alpha1:
		return true
	default:
		return false
	}
}

// Defines values for WorkflowResourceKind.
const (
	WorkflowResourceKindWorkflow WorkflowResourceKind = "Workflow"
)

// Valid indicates whether the value is a known member of the WorkflowResourceKind enum.
func (e WorkflowResourceKind) Valid() bool {
	switch e {
	case WorkflowResourceKindWorkflow:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceResourceKind.
const (
	WorkspaceResourceKindWorkspace WorkspaceResourceKind = "Workspace"
)

// Valid indicates whether the value is a known member of the WorkspaceResourceKind enum.
func (e WorkspaceResourceKind) Valid() bool {
	switch e {
	case WorkspaceResourceKindWorkspace:
		return true
	default:
		return false
	}
}

// ACLPermission ACL permission enum.
type ACLPermission string

// ACLPermissionList defines model for ACLPermissionList.
type ACLPermissionList = []ACLPermission

// ACLPolicy ACL policy describing one subject-resource-role relation and optional validity window.
type ACLPolicy struct {
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	NotBefore *time.Time `json:"not_before,omitempty"`

	// Resource ACL resource identity. Stored canonically as kind:id.
	Resource ACLResource `json:"resource"`
	Role     string      `json:"role"`

	// Subject ACL subject identity. Stored canonically as kind:id.
	Subject ACLSubject `json:"subject"`
}

// ACLPolicyBinding defines model for ACLPolicyBinding.
type ACLPolicyBinding struct {
	CreatedAt    time.Time `json:"created_at"`
	DisplayOrder float64   `json:"display_order"`
	Id           string    `json:"id"`

	// Policy ACL policy describing one subject-resource-role relation and optional validity window.
	Policy    ACLPolicy `json:"policy"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ACLPolicyBindingResource defines model for ACLPolicyBindingResource.
type ACLPolicyBindingResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion           `json:"apiVersion"`
	Kind       ACLPolicyBindingResourceKind `json:"kind"`
	Metadata   ResourceMetadata             `json:"metadata"`

	// Spec ACL policy describing one subject-resource-role relation and optional validity window.
	Spec ACLPolicy `json:"spec"`
}

// ACLPolicyBindingResourceKind defines model for ACLPolicyBindingResource.Kind.
type ACLPolicyBindingResourceKind string

// ACLResource ACL resource identity. Stored canonically as kind:id.
type ACLResource struct {
	// Id Resource identifier for the selected kind.
	Id string `json:"id"`

	// Kind ACL resource identity kind.
	Kind ACLResourceKind `json:"kind"`
}

// ACLResourceKind ACL resource identity kind.
type ACLResourceKind string

// ACLRole defines model for ACLRole.
type ACLRole struct {
	CreatedAt   time.Time         `json:"created_at"`
	Name        string            `json:"name"`
	Permissions ACLPermissionList `json:"permissions"`
	UpdatedAt   time.Time         `json:"updated_at"`
}

// ACLRoleResource defines model for ACLRoleResource.
type ACLRoleResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion  `json:"apiVersion"`
	Kind       ACLRoleResourceKind `json:"kind"`
	Metadata   ResourceMetadata    `json:"metadata"`
	Spec       ACLRoleSpec         `json:"spec"`
}

// ACLRoleResourceKind defines model for ACLRoleResource.Kind.
type ACLRoleResourceKind string

// ACLRoleSpec defines model for ACLRoleSpec.
type ACLRoleSpec struct {
	Permissions ACLPermissionList `json:"permissions"`
}

// ACLSubject ACL subject identity. Stored canonically as kind:id.
type ACLSubject struct {
	// Id Subject identifier for the selected kind.
	Id string `json:"id"`

	// Kind ACL subject identity kind.
	Kind ACLSubjectKind `json:"kind"`
}

// ACLSubjectKind ACL subject identity kind.
type ACLSubjectKind string

// ACLView defines model for ACLView.
type ACLView struct {
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// ACLViewResource defines model for ACLViewResource.
type ACLViewResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion  `json:"apiVersion"`
	Kind       ACLViewResourceKind `json:"kind"`
	Metadata   ResourceMetadata    `json:"metadata"`
	Spec       ACLViewSpec         `json:"spec"`
}

// ACLViewResourceKind defines model for ACLViewResource.Kind.
type ACLViewResourceKind string

// ACLViewSpec defines model for ACLViewSpec.
type ACLViewSpec struct {
	Description *string `json:"description,omitempty"`
}

// AgentSelection defines model for AgentSelection.
type AgentSelection struct {
	WorkspaceName string `json:"workspace_name"`
}

// ApplyAction Result of applying the resource.
type ApplyAction string

// ApplyResource defines model for ApplyResource.
type ApplyResource = Resource

// ApplyResult defines model for ApplyResult.
type ApplyResult struct {
	// Action Result of applying the resource.
	Action ApplyAction `json:"action"`

	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion `json:"apiVersion"`

	// Items Nested apply results for ResourceList resources.
	Items *[]ApplyResult `json:"items,omitempty"`

	// Kind Declarative GizClaw resource kind.
	Kind    ResourceKind `json:"kind"`
	Message *string      `json:"message,omitempty"`
	Name    string       `json:"name"`
}

// Badge defines model for Badge.
type Badge struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	IconPath    string    `json:"icon_path"`
	Id          string    `json:"id"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// BadgeResource defines model for BadgeResource.
type BadgeResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion `json:"apiVersion"`
	Kind       BadgeResourceKind  `json:"kind"`
	Metadata   ResourceMetadata   `json:"metadata"`
	Spec       BadgeSpec          `json:"spec"`
}

// BadgeResourceKind defines model for BadgeResource.Kind.
type BadgeResourceKind string

// BadgeSpec defines model for BadgeSpec.
type BadgeSpec struct {
	Description string  `json:"description"`
	IconPath    *string `json:"icon_path,omitempty"`
	Name        string  `json:"name"`
}

// Configuration defines model for Configuration.
type Configuration struct {
	Firmware *FirmwareSelection `json:"firmware,omitempty"`

	// View Current content view name selected for this peer.
	View *string `json:"view,omitempty"`
}

// Credential defines model for Credential.
type Credential struct {
	// Body Provider-specific credential payload. The shape is selected by Credential.provider.
	Body        CredentialBody `json:"body"`
	CreatedAt   time.Time      `json:"created_at"`
	Description *string        `json:"description,omitempty"`
	Name        string         `json:"name"`
	Provider    string         `json:"provider"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// CredentialBody Provider-specific credential payload. The shape is selected by Credential.provider.
type CredentialBody struct {
	union json.RawMessage
}

// CredentialResource defines model for CredentialResource.
type CredentialResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion     `json:"apiVersion"`
	Kind       CredentialResourceKind `json:"kind"`
	Metadata   ResourceMetadata       `json:"metadata"`
	Spec       CredentialSpec         `json:"spec"`
}

// CredentialResourceKind defines model for CredentialResource.Kind.
type CredentialResourceKind string

// CredentialSpec defines model for CredentialSpec.
type CredentialSpec struct {
	// Body Provider-specific credential payload. The shape is selected by Credential.provider.
	Body        CredentialBody `json:"body"`
	Description *string        `json:"description,omitempty"`
	Provider    string         `json:"provider"`
}

// DashScopeCredentialBody defines model for DashScopeCredentialBody.
type DashScopeCredentialBody struct {
	ApiKey  *string `json:"api_key,omitempty"`
	BaseUrl *string `json:"base_url,omitempty"`
	Token   *string `json:"token,omitempty"`
}

// DashScopeTenant defines model for DashScopeTenant.
type DashScopeTenant struct {
	BaseUrl        *string   `json:"base_url,omitempty"`
	CreatedAt      time.Time `json:"created_at"`
	CredentialName string    `json:"credential_name"`
	Description    *string   `json:"description,omitempty"`
	Name           string    `json:"name"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// DashScopeTenantModelProviderData defines model for DashScopeTenantModelProviderData.
type DashScopeTenantModelProviderData struct {
	ApiMode       *DashScopeTenantModelProviderDataApiMode `json:"api_mode,omitempty"`
	UpstreamModel *string                                  `json:"upstream_model,omitempty"`
}

// DashScopeTenantModelProviderDataApiMode defines model for DashScopeTenantModelProviderData.ApiMode.
type DashScopeTenantModelProviderDataApiMode string

// DashScopeTenantResource defines model for DashScopeTenantResource.
type DashScopeTenantResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion          `json:"apiVersion"`
	Kind       DashScopeTenantResourceKind `json:"kind"`
	Metadata   ResourceMetadata            `json:"metadata"`
	Spec       DashScopeTenantSpec         `json:"spec"`
}

// DashScopeTenantResourceKind defines model for DashScopeTenantResource.Kind.
type DashScopeTenantResourceKind string

// DashScopeTenantSpec defines model for DashScopeTenantSpec.
type DashScopeTenantSpec struct {
	BaseUrl        *string `json:"base_url,omitempty"`
	CredentialName string  `json:"credential_name"`
	Description    *string `json:"description,omitempty"`
}

// DashScopeTenantVoiceProviderData defines model for DashScopeTenantVoiceProviderData.
type DashScopeTenantVoiceProviderData struct {
	Raw     *map[string]interface{} `json:"raw,omitempty"`
	VoiceId *string                 `json:"voice_id,omitempty"`
}

// DeviceInfo defines model for DeviceInfo.
type DeviceInfo struct {
	Hardware *HardwareInfo `json:"hardware,omitempty"`
	Name     *string       `json:"name,omitempty"`
	Sn       *string       `json:"sn,omitempty"`
}

// ErrorPayload defines model for ErrorPayload.
type ErrorPayload struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorPayload `json:"error"`
}

// Event defines model for Event.
type Event struct {
	Data *json.RawMessage `json:"data,omitempty"`
	Name string           `json:"name"`
	V    int              `json:"v"`
}

// Firmware defines model for Firmware.
type Firmware struct {
	CreatedAt   time.Time     `json:"created_at"`
	Description *string       `json:"description,omitempty"`
	Name        string        `json:"name"`
	Slots       FirmwareSlots `json:"slots"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

// FirmwareArtifact defines model for FirmwareArtifact.
type FirmwareArtifact struct {
	// ContentType Optional content type captured during upload.
	ContentType *string `json:"content_type,omitempty"`

	// Kind Kind of payload carried by a firmware artifact.
	Kind FirmwareArtifactKind `json:"kind"`

	// Name Device-defined artifact name.
	Name string `json:"name"`

	// Path Server-owned objectstore path for the uploaded artifact payload.
	Path *string `json:"path,omitempty"`

	// Sha256 Optional SHA-256 digest for integrity checks.
	Sha256 *string `json:"sha256,omitempty"`

	// Size Optional artifact size in bytes.
	Size *int64 `json:"size,omitempty"`

	// UploadedAt Server-owned upload timestamp.
	UploadedAt *time.Time `json:"uploaded_at,omitempty"`
}

// FirmwareArtifactKind Kind of payload carried by a firmware artifact.
type FirmwareArtifactKind string

// FirmwareResource defines model for FirmwareResource.
type FirmwareResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion   `json:"apiVersion"`
	Kind       FirmwareResourceKind `json:"kind"`
	Metadata   ResourceMetadata     `json:"metadata"`
	Spec       FirmwareSpec         `json:"spec"`
}

// FirmwareResourceKind defines model for FirmwareResource.Kind.
type FirmwareResourceKind string

// FirmwareSelection defines model for FirmwareSelection.
type FirmwareSelection struct {
	// Channel Firmware channel selected for the peer.
	Channel FirmwareSelectionChannel `json:"channel"`

	// Id Firmware release-line id selected for the peer.
	Id string `json:"id"`
}

// FirmwareSelectionChannel Firmware channel selected for the peer.
type FirmwareSelectionChannel string

// FirmwareSlot defines model for FirmwareSlot.
type FirmwareSlot struct {
	// Artifacts Device-defined artifact list for this slot.
	Artifacts   *[]FirmwareArtifact `json:"artifacts,omitempty"`
	Description *string             `json:"description,omitempty"`

	// Version Version carried by this slot.
	Version *string `json:"version,omitempty"`
}

// FirmwareSlots defines model for FirmwareSlots.
type FirmwareSlots struct {
	Beta    FirmwareSlot `json:"beta"`
	Develop FirmwareSlot `json:"develop"`
	Pending FirmwareSlot `json:"pending"`
	Stable  FirmwareSlot `json:"stable"`
}

// FirmwareSpec defines model for FirmwareSpec.
type FirmwareSpec struct {
	Description *string       `json:"description,omitempty"`
	Slots       FirmwareSlots `json:"slots"`
}

// FlowcraftWorkflow defines model for FlowcraftWorkflow.
type FlowcraftWorkflow struct {
	ApiVersion WorkflowAPIVersion    `json:"apiVersion"`
	Kind       FlowcraftWorkflowKind `json:"kind"`
	Metadata   WorkflowMetadata      `json:"metadata"`
	Spec       FlowcraftWorkflowSpec `json:"spec"`
}

// FlowcraftWorkflowKind defines model for FlowcraftWorkflow.Kind.
type FlowcraftWorkflowKind string

// FlowcraftWorkflowSpec defines model for FlowcraftWorkflowSpec.
type FlowcraftWorkflowSpec map[string]interface{}

// GeminiCredentialBody defines model for GeminiCredentialBody.
type GeminiCredentialBody struct {
	ApiKey  *string `json:"api_key,omitempty"`
	BaseUrl *string `json:"base_url,omitempty"`
	Token   *string `json:"token,omitempty"`
}

// GeminiTenant defines model for GeminiTenant.
type GeminiTenant struct {
	BaseUrl        *string   `json:"base_url,omitempty"`
	CreatedAt      time.Time `json:"created_at"`
	CredentialName string    `json:"credential_name"`
	Description    *string   `json:"description,omitempty"`
	Location       *string   `json:"location,omitempty"`
	Name           string    `json:"name"`
	ProjectId      *string   `json:"project_id,omitempty"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// GeminiTenantModelProviderData defines model for GeminiTenantModelProviderData.
type GeminiTenantModelProviderData struct {
	UpstreamModel *string `json:"upstream_model,omitempty"`
}

// GeminiTenantResource defines model for GeminiTenantResource.
type GeminiTenantResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion       `json:"apiVersion"`
	Kind       GeminiTenantResourceKind `json:"kind"`
	Metadata   ResourceMetadata         `json:"metadata"`
	Spec       GeminiTenantSpec         `json:"spec"`
}

// GeminiTenantResourceKind defines model for GeminiTenantResource.Kind.
type GeminiTenantResourceKind string

// GeminiTenantSpec defines model for GeminiTenantSpec.
type GeminiTenantSpec struct {
	BaseUrl        *string `json:"base_url,omitempty"`
	CredentialName string  `json:"credential_name"`
	Description    *string `json:"description,omitempty"`
	Location       *string `json:"location,omitempty"`
	ProjectId      *string `json:"project_id,omitempty"`
}

// GeminiTenantVoiceProviderData defines model for GeminiTenantVoiceProviderData.
type GeminiTenantVoiceProviderData struct {
	Raw     *map[string]interface{} `json:"raw,omitempty"`
	VoiceId *string                 `json:"voice_id,omitempty"`
}

// HardwareInfo defines model for HardwareInfo.
type HardwareInfo struct {
	HardwareRevision *string      `json:"hardware_revision,omitempty"`
	Imeis            *[]PeerIMEI  `json:"imeis,omitempty"`
	Labels           *[]PeerLabel `json:"labels,omitempty"`
	Manufacturer     *string      `json:"manufacturer,omitempty"`
	Model            *string      `json:"model,omitempty"`
}

// MiniMaxCredentialBody defines model for MiniMaxCredentialBody.
type MiniMaxCredentialBody struct {
	ApiKey              *string `json:"api_key,omitempty"`
	BaseUrl             *string `json:"base_url,omitempty"`
	MinimaxVoiceBaseUrl *string `json:"minimax_voice_base_url,omitempty"`
	Token               *string `json:"token,omitempty"`
	VoiceBaseUrl        *string `json:"voice_base_url,omitempty"`
}

// MiniMaxTenant defines model for MiniMaxTenant.
type MiniMaxTenant struct {
	AppId          string     `json:"app_id"`
	BaseUrl        *string    `json:"base_url,omitempty"`
	CreatedAt      time.Time  `json:"created_at"`
	CredentialName string     `json:"credential_name"`
	Description    *string    `json:"description,omitempty"`
	GroupId        string     `json:"group_id"`
	LastSyncedAt   *time.Time `json:"last_synced_at,omitempty"`
	Name           string     `json:"name"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

// MiniMaxTenantResource defines model for MiniMaxTenantResource.
type MiniMaxTenantResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion        `json:"apiVersion"`
	Kind       MiniMaxTenantResourceKind `json:"kind"`
	Metadata   ResourceMetadata          `json:"metadata"`
	Spec       MiniMaxTenantSpec         `json:"spec"`
}

// MiniMaxTenantResourceKind defines model for MiniMaxTenantResource.Kind.
type MiniMaxTenantResourceKind string

// MiniMaxTenantSpec defines model for MiniMaxTenantSpec.
type MiniMaxTenantSpec struct {
	AppId          string  `json:"app_id"`
	BaseUrl        *string `json:"base_url,omitempty"`
	CredentialName string  `json:"credential_name"`
	Description    *string `json:"description,omitempty"`
	GroupId        string  `json:"group_id"`
}

// MiniMaxTenantVoiceProviderData defines model for MiniMaxTenantVoiceProviderData.
type MiniMaxTenantVoiceProviderData struct {
	Raw       *map[string]interface{} `json:"raw,omitempty"`
	VoiceId   *string                 `json:"voice_id,omitempty"`
	VoiceType *string                 `json:"voice_type,omitempty"`
}

// Model defines model for Model.
type Model struct {
	Capabilities *ModelCapabilities `json:"capabilities,omitempty"`
	CreatedAt    time.Time          `json:"created_at"`
	Description  *string            `json:"description,omitempty"`
	Id           string             `json:"id"`

	// Kind Runtime role of a model.
	Kind     ModelKind     `json:"kind"`
	Name     *string       `json:"name,omitempty"`
	Provider ModelProvider `json:"provider"`

	// ProviderData Provider-specific model runtime configuration keyed by provider kind.
	ProviderData *ModelProviderData `json:"provider_data,omitempty"`

	// Source How the model entered the global catalog
	Source    ModelSource `json:"source"`
	SyncedAt  *time.Time  `json:"synced_at,omitempty"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// ModelCapabilities defines model for ModelCapabilities.
type ModelCapabilities struct {
	JsonOutput  *bool                    `json:"json_output,omitempty"`
	SystemRole  *bool                    `json:"system_role,omitempty"`
	Temperature *bool                    `json:"temperature,omitempty"`
	TextOnly    *bool                    `json:"text_only,omitempty"`
	Thinking    *ModelThinkingCapability `json:"thinking,omitempty"`
	ToolCalls   *bool                    `json:"tool_calls,omitempty"`
}

// ModelKind Runtime role of a model.
type ModelKind string

// ModelProvider defines model for ModelProvider.
type ModelProvider struct {
	// Kind Provider resource kind usable by model runtime.
	Kind ModelProviderKind `json:"kind"`
	Name string            `json:"name"`
}

// ModelProviderData Provider-specific model runtime configuration keyed by provider kind.
type ModelProviderData map[string]interface{}

// ModelProviderKind Provider resource kind usable by model runtime.
type ModelProviderKind string

// ModelResource defines model for ModelResource.
type ModelResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion `json:"apiVersion"`
	Kind       ModelResourceKind  `json:"kind"`
	Metadata   ResourceMetadata   `json:"metadata"`
	Spec       ModelSpec          `json:"spec"`
}

// ModelResourceKind defines model for ModelResource.Kind.
type ModelResourceKind string

// ModelSource How the model entered the global catalog
type ModelSource string

// ModelSpec defines model for ModelSpec.
type ModelSpec struct {
	Capabilities *ModelCapabilities `json:"capabilities,omitempty"`
	Description  *string            `json:"description,omitempty"`

	// Kind Runtime role of a model.
	Kind     ModelKind     `json:"kind"`
	Name     *string       `json:"name,omitempty"`
	Provider ModelProvider `json:"provider"`

	// ProviderData Provider-specific model runtime configuration keyed by provider kind.
	ProviderData *ModelProviderData `json:"provider_data,omitempty"`

	// Source How the model entered the global catalog
	Source ModelSource `json:"source"`
}

// ModelThinkingCapability defines model for ModelThinkingCapability.
type ModelThinkingCapability struct {
	DefaultLevel *string `json:"default_level,omitempty"`

	// LevelParam Optional provider request parameter used for the selected thinking level or budget.
	LevelParam *string   `json:"level_param,omitempty"`
	Levels     *[]string `json:"levels,omitempty"`

	// Param Provider request parameter mapping, such as reasoning_effort, thinking.type, or enable_thinking.
	Param     *string `json:"param,omitempty"`
	Supported bool    `json:"supported"`
}

// OpenAICredentialBody defines model for OpenAICredentialBody.
type OpenAICredentialBody struct {
	ApiKey       *string `json:"api_key,omitempty"`
	BaseUrl      *string `json:"base_url,omitempty"`
	Organization *string `json:"organization,omitempty"`
	Project      *string `json:"project,omitempty"`
	Token        *string `json:"token,omitempty"`
}

// OpenAITenant defines model for OpenAITenant.
type OpenAITenant struct {
	// ApiMode OpenAI API mode used by this tenant.
	ApiMode        OpenAITenantAPIMode `json:"api_mode"`
	BaseUrl        *string             `json:"base_url,omitempty"`
	CreatedAt      time.Time           `json:"created_at"`
	CredentialName string              `json:"credential_name"`
	Description    *string             `json:"description,omitempty"`

	// Kind OpenAI-compatible endpoint kind.
	Kind      OpenAITenantKind `json:"kind"`
	Name      string           `json:"name"`
	UpdatedAt time.Time        `json:"updated_at"`
}

// OpenAITenantAPIMode OpenAI API mode used by this tenant.
type OpenAITenantAPIMode string

// OpenAITenantKind OpenAI-compatible endpoint kind.
type OpenAITenantKind string

// OpenAITenantModelProviderData defines model for OpenAITenantModelProviderData.
type OpenAITenantModelProviderData struct {
	DefaultThinkingLevel *string   `json:"default_thinking_level,omitempty"`
	SupportJsonOutput    *bool     `json:"support_json_output,omitempty"`
	SupportTextOnly      *bool     `json:"support_text_only,omitempty"`
	SupportThinking      *bool     `json:"support_thinking,omitempty"`
	SupportToolCalls     *bool     `json:"support_tool_calls,omitempty"`
	ThinkingLevelParam   *string   `json:"thinking_level_param,omitempty"`
	ThinkingLevels       *[]string `json:"thinking_levels,omitempty"`
	ThinkingParam        *string   `json:"thinking_param,omitempty"`
	UpstreamModel        *string   `json:"upstream_model,omitempty"`
	UseSystemRole        *bool     `json:"use_system_role,omitempty"`
}

// OpenAITenantResource defines model for OpenAITenantResource.
type OpenAITenantResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion       `json:"apiVersion"`
	Kind       OpenAITenantResourceKind `json:"kind"`
	Metadata   ResourceMetadata         `json:"metadata"`
	Spec       OpenAITenantSpec         `json:"spec"`
}

// OpenAITenantResourceKind defines model for OpenAITenantResource.Kind.
type OpenAITenantResourceKind string

// OpenAITenantSpec defines model for OpenAITenantSpec.
type OpenAITenantSpec struct {
	// ApiMode OpenAI API mode used by this tenant.
	ApiMode        *OpenAITenantAPIMode `json:"api_mode,omitempty"`
	BaseUrl        *string              `json:"base_url,omitempty"`
	CredentialName string               `json:"credential_name"`
	Description    *string              `json:"description,omitempty"`

	// Kind OpenAI-compatible endpoint kind.
	Kind *OpenAITenantKind `json:"kind,omitempty"`
}

// OpenAITenantVoiceProviderData defines model for OpenAITenantVoiceProviderData.
type OpenAITenantVoiceProviderData struct {
	Raw     *map[string]interface{} `json:"raw,omitempty"`
	VoiceId *string                 `json:"voice_id,omitempty"`
}

// Peer defines model for Peer.
type Peer struct {
	ApprovedAt     *time.Time             `json:"approved_at,omitempty"`
	AutoRegistered *bool                  `json:"auto_registered,omitempty"`
	Configuration  Configuration          `json:"configuration"`
	CreatedAt      time.Time              `json:"created_at"`
	Device         DeviceInfo             `json:"device"`
	PublicKey      string                 `json:"public_key"`
	Role           PeerRole               `json:"role"`
	Status         PeerRegistrationStatus `json:"status"`
	UpdatedAt      time.Time              `json:"updated_at"`
}

// PeerConfigResource defines model for PeerConfigResource.
type PeerConfigResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion     `json:"apiVersion"`
	Kind       PeerConfigResourceKind `json:"kind"`
	Metadata   ResourceMetadata       `json:"metadata"`
	Spec       Configuration          `json:"spec"`
}

// PeerConfigResourceKind defines model for PeerConfigResource.Kind.
type PeerConfigResourceKind string

// PeerIMEI defines model for PeerIMEI.
type PeerIMEI struct {
	Name   *string `json:"name,omitempty"`
	Serial string  `json:"serial"`
	Tac    string  `json:"tac"`
}

// PeerLabel defines model for PeerLabel.
type PeerLabel struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// PeerRegistrationStatus defines model for PeerRegistrationStatus.
type PeerRegistrationStatus string

// PeerRole defines model for PeerRole.
type PeerRole string

// PeerRunAgent defines model for PeerRunAgent.
type PeerRunAgent struct {
	Active  *AgentSelection `json:"active,omitempty"`
	Pending *AgentSelection `json:"pending,omitempty"`
}

// PeerRunStatus defines model for PeerRunStatus.
type PeerRunStatus struct {
	FriendOtp     *string            `json:"friend_otp,omitempty"`
	Message       *string            `json:"message,omitempty"`
	StartedAt     *time.Time         `json:"started_at,omitempty"`
	State         PeerRunStatusState `json:"state"`
	UpdatedAt     *time.Time         `json:"updated_at,omitempty"`
	WorkspaceName *string            `json:"workspace_name,omitempty"`
}

// PeerRunStatusState defines model for PeerRunStatusState.
type PeerRunStatusState string

// PeerStatus defines model for PeerStatus.
type PeerStatus struct {
	BatteryPercent *int                    `json:"battery_percent,omitempty"`
	Charging       *bool                   `json:"charging,omitempty"`
	Details        *map[string]interface{} `json:"details,omitempty"`
	Labels         *map[string]string      `json:"labels,omitempty"`
	Muted          *bool                   `json:"muted,omitempty"`
	ReportedAt     *time.Time              `json:"reported_at,omitempty"`
	Volume         *int                    `json:"volume,omitempty"`
}

// PeerStreamEvent defines model for PeerStreamEvent.
type PeerStreamEvent struct {
	Error     *string             `json:"error,omitempty"`
	Kind      *PeerStreamKind     `json:"kind,omitempty"`
	Label     *string             `json:"label,omitempty"`
	MimeType  *string             `json:"mime_type,omitempty"`
	Seq       *int64              `json:"seq,omitempty"`
	StreamId  *string             `json:"stream_id,omitempty"`
	Text      *string             `json:"text,omitempty"`
	Timestamp *int64              `json:"timestamp,omitempty"`
	Type      PeerStreamEventType `json:"type"`
	V         int                 `json:"v"`
}

// PeerStreamEventType defines model for PeerStreamEventType.
type PeerStreamEventType string

// PeerStreamKind defines model for PeerStreamKind.
type PeerStreamKind string

// PetSpecies defines model for PetSpecies.
type PetSpecies struct {
	CreatedAt    time.Time    `json:"created_at"`
	Id           string       `json:"id"`
	Name         string       `json:"name"`
	PixaMetadata PixaMetadata `json:"pixa_metadata"`
	PixaPath     string       `json:"pixa_path"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

// PetSpeciesResource defines model for PetSpeciesResource.
type PetSpeciesResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion     `json:"apiVersion"`
	Kind       PetSpeciesResourceKind `json:"kind"`
	Metadata   ResourceMetadata       `json:"metadata"`
	Spec       PetSpeciesSpec         `json:"spec"`
}

// PetSpeciesResourceKind defines model for PetSpeciesResource.Kind.
type PetSpeciesResourceKind string

// PetSpeciesSpec defines model for PetSpeciesSpec.
type PetSpeciesSpec struct {
	Name     string  `json:"name"`
	PixaPath *string `json:"pixa_path,omitempty"`
}

// PixaMetadata defines model for PixaMetadata.
type PixaMetadata struct {
	CanvasHeight int      `json:"canvas_height"`
	CanvasWidth  int      `json:"canvas_width"`
	ClipCount    int      `json:"clip_count"`
	ClipNames    []string `json:"clip_names"`
	ColorCount   int      `json:"color_count"`
	FrameCount   int      `json:"frame_count"`
	PayloadBytes int      `json:"payload_bytes"`
	Version      int      `json:"version"`
}

// Provider defines model for Provider.
type Provider struct {
	// Kind Provider resource kind, such as openai-tenant, minimax-tenant, or volc-tenant.
	Kind ProviderKind `json:"kind"`
	Name string       `json:"name"`
}

// ProviderKind Provider resource kind, such as openai-tenant, minimax-tenant, or volc-tenant.
type ProviderKind string

// RefreshIdentifiers defines model for RefreshIdentifiers.
type RefreshIdentifiers struct {
	Imeis  *[]PeerIMEI  `json:"imeis,omitempty"`
	Labels *[]PeerLabel `json:"labels,omitempty"`
	Sn     *string      `json:"sn,omitempty"`
}

// RefreshInfo defines model for RefreshInfo.
type RefreshInfo struct {
	HardwareRevision *string `json:"hardware_revision,omitempty"`
	Manufacturer     *string `json:"manufacturer,omitempty"`
	Model            *string `json:"model,omitempty"`
	Name             *string `json:"name,omitempty"`
}

// Registration defines model for Registration.
type Registration struct {
	ApprovedAt     *time.Time             `json:"approved_at,omitempty"`
	AutoRegistered *bool                  `json:"auto_registered,omitempty"`
	CreatedAt      time.Time              `json:"created_at"`
	Device         *DeviceInfo            `json:"device,omitempty"`
	PublicKey      string                 `json:"public_key"`
	Role           PeerRole               `json:"role"`
	Status         PeerRegistrationStatus `json:"status"`
	UpdatedAt      time.Time              `json:"updated_at"`
}

// Resource defines model for Resource.
type Resource struct {
	union json.RawMessage
}

// ResourceAPIVersion API version for declarative GizClaw resources.
type ResourceAPIVersion string

// ResourceKind Declarative GizClaw resource kind.
type ResourceKind string

// ResourceList defines model for ResourceList.
type ResourceList = ResourceListResource

// ResourceListResource defines model for ResourceListResource.
type ResourceListResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion       `json:"apiVersion"`
	Kind       ResourceListResourceKind `json:"kind"`
	Metadata   ResourceMetadata         `json:"metadata"`
	Spec       ResourceListSpec         `json:"spec"`
}

// ResourceListResourceKind defines model for ResourceListResource.Kind.
type ResourceListResourceKind string

// ResourceListSpec defines model for ResourceListSpec.
type ResourceListSpec struct {
	Items []Resource `json:"items"`
}

// ResourceMetadata defines model for ResourceMetadata.
type ResourceMetadata struct {
	Annotations *map[string]string `json:"annotations,omitempty"`
	Labels      *map[string]string `json:"labels,omitempty"`

	// Name Resource name. For PeerConfig this is the peer public key.
	Name string `json:"name"`
}

// Runtime defines model for Runtime.
type Runtime struct {
	LastAddr   *string   `json:"last_addr,omitempty"`
	LastSeenAt time.Time `json:"last_seen_at"`
	Online     bool      `json:"online"`
	RxBytes    *uint64   `json:"rx_bytes,omitempty"`
	TxBytes    *uint64   `json:"tx_bytes,omitempty"`
}

// ServerInfo defines model for ServerInfo.
type ServerInfo struct {
	BuildCommit string `json:"build_commit"`
	PublicKey   string `json:"public_key"`
	ServerTime  int64  `json:"server_time"`
}

// Voice defines model for Voice.
type Voice struct {
	CreatedAt   time.Time     `json:"created_at"`
	Description *string       `json:"description,omitempty"`
	Id          string        `json:"id"`
	Name        *string       `json:"name,omitempty"`
	Provider    VoiceProvider `json:"provider"`

	// ProviderData Provider-specific voice runtime configuration keyed by provider kind.
	ProviderData *VoiceProviderData `json:"provider_data,omitempty"`

	// Source How the voice entered the global catalog
	Source    VoiceSource `json:"source"`
	SyncedAt  *time.Time  `json:"synced_at,omitempty"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// VoiceProvider defines model for VoiceProvider.
type VoiceProvider struct {
	// Kind Provider resource kind usable by voice runtime.
	Kind VoiceProviderKind `json:"kind"`
	Name string            `json:"name"`
}

// VoiceProviderData Provider-specific voice runtime configuration keyed by provider kind.
type VoiceProviderData map[string]interface{}

// VoiceProviderKind Provider resource kind usable by voice runtime.
type VoiceProviderKind string

// VoiceResource defines model for VoiceResource.
type VoiceResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion `json:"apiVersion"`
	Kind       VoiceResourceKind  `json:"kind"`
	Metadata   ResourceMetadata   `json:"metadata"`
	Spec       VoiceSpec          `json:"spec"`
}

// VoiceResourceKind defines model for VoiceResource.Kind.
type VoiceResourceKind string

// VoiceSource How the voice entered the global catalog
type VoiceSource string

// VoiceSpec defines model for VoiceSpec.
type VoiceSpec struct {
	Description *string       `json:"description,omitempty"`
	Name        *string       `json:"name,omitempty"`
	Provider    VoiceProvider `json:"provider"`

	// ProviderData Provider-specific voice runtime configuration keyed by provider kind.
	ProviderData *VoiceProviderData `json:"provider_data,omitempty"`

	// Source How the voice entered the global catalog
	Source VoiceSource `json:"source"`
}

// VolcCredentialBody defines model for VolcCredentialBody.
type VolcCredentialBody struct {
	AccessKey       *string `json:"access_key,omitempty"`
	AccessKeyId     *string `json:"access_key_id,omitempty"`
	AccessToken     *string `json:"access_token,omitempty"`
	Ak              *string `json:"ak,omitempty"`
	ApiKey          *string `json:"api_key,omitempty"`
	AppId           *string `json:"app_id,omitempty"`
	BaseUrl         *string `json:"base_url,omitempty"`
	BearerToken     *string `json:"bearer_token,omitempty"`
	SaucAccessKey   *string `json:"sauc_access_key,omitempty"`
	SecretAccessKey *string `json:"secret_access_key,omitempty"`
	SecretKey       *string `json:"secret_key,omitempty"`
	SessionToken    *string `json:"session_token,omitempty"`
	Sk              *string `json:"sk,omitempty"`
	Token           *string `json:"token,omitempty"`
	VoiceBaseUrl    *string `json:"voice_base_url,omitempty"`
	XApiKey         *string `json:"x_api_key,omitempty"`
}

// VolcTenant defines model for VolcTenant.
type VolcTenant struct {
	CreatedAt      time.Time  `json:"created_at"`
	CredentialName string     `json:"credential_name"`
	Description    *string    `json:"description,omitempty"`
	Endpoint       *string    `json:"endpoint,omitempty"`
	LastSyncedAt   *time.Time `json:"last_synced_at,omitempty"`
	Name           string     `json:"name"`
	Region         *string    `json:"region,omitempty"`
	ResourceIds    *[]string  `json:"resource_ids,omitempty"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

// VolcTenantModelProviderData defines model for VolcTenantModelProviderData.
type VolcTenantModelProviderData struct {
	ApiMode              *VolcTenantModelProviderDataApiMode `json:"api_mode,omitempty"`
	AuthMode             *string                             `json:"auth_mode,omitempty"`
	DefaultThinkingLevel *string                             `json:"default_thinking_level,omitempty"`
	ResourceId           *string                             `json:"resource_id,omitempty"`
	SupportJsonOutput    *bool                               `json:"support_json_output,omitempty"`
	SupportTextOnly      *bool                               `json:"support_text_only,omitempty"`
	SupportThinking      *bool                               `json:"support_thinking,omitempty"`
	SupportToolCalls     *bool                               `json:"support_tool_calls,omitempty"`
	ThinkingLevelParam   *string                             `json:"thinking_level_param,omitempty"`
	ThinkingLevels       *[]string                           `json:"thinking_levels,omitempty"`
	ThinkingParam        *string                             `json:"thinking_param,omitempty"`
	UpstreamModel        *string                             `json:"upstream_model,omitempty"`
	UseSystemRole        *bool                               `json:"use_system_role,omitempty"`
}

// VolcTenantModelProviderDataApiMode defines model for VolcTenantModelProviderData.ApiMode.
type VolcTenantModelProviderDataApiMode string

// VolcTenantResource defines model for VolcTenantResource.
type VolcTenantResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion     `json:"apiVersion"`
	Kind       VolcTenantResourceKind `json:"kind"`
	Metadata   ResourceMetadata       `json:"metadata"`
	Spec       VolcTenantSpec         `json:"spec"`
}

// VolcTenantResourceKind defines model for VolcTenantResource.Kind.
type VolcTenantResourceKind string

// VolcTenantSpec defines model for VolcTenantSpec.
type VolcTenantSpec struct {
	CredentialName string    `json:"credential_name"`
	Description    *string   `json:"description,omitempty"`
	Endpoint       *string   `json:"endpoint,omitempty"`
	Region         *string   `json:"region,omitempty"`
	ResourceIds    *[]string `json:"resource_ids,omitempty"`
}

// VolcTenantVoiceProviderData defines model for VolcTenantVoiceProviderData.
type VolcTenantVoiceProviderData struct {
	Raw        *map[string]interface{} `json:"raw,omitempty"`
	ResourceId *string                 `json:"resource_id,omitempty"`
	State      *string                 `json:"state,omitempty"`
	Status     *string                 `json:"status,omitempty"`
	VoiceId    *string                 `json:"voice_id,omitempty"`
}

// WorkflowAPIVersion defines model for WorkflowAPIVersion.
type WorkflowAPIVersion string

// WorkflowDocument defines model for WorkflowDocument.
type WorkflowDocument = FlowcraftWorkflow

// WorkflowMetadata defines model for WorkflowMetadata.
type WorkflowMetadata struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// WorkflowResource defines model for WorkflowResource.
type WorkflowResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion   `json:"apiVersion"`
	Kind       WorkflowResourceKind `json:"kind"`
	Metadata   ResourceMetadata     `json:"metadata"`
	Spec       WorkflowDocument     `json:"spec"`
}

// WorkflowResourceKind defines model for WorkflowResource.Kind.
type WorkflowResourceKind string

// Workspace defines model for Workspace.
type Workspace struct {
	CreatedAt    time.Time               `json:"created_at"`
	Name         string                  `json:"name"`
	Parameters   *map[string]interface{} `json:"parameters,omitempty"`
	UpdatedAt    time.Time               `json:"updated_at"`
	WorkflowName string                  `json:"workflow_name"`
}

// WorkspaceResource defines model for WorkspaceResource.
type WorkspaceResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion    `json:"apiVersion"`
	Kind       WorkspaceResourceKind `json:"kind"`
	Metadata   ResourceMetadata      `json:"metadata"`
	Spec       WorkspaceSpec         `json:"spec"`
}

// WorkspaceResourceKind defines model for WorkspaceResource.Kind.
type WorkspaceResourceKind string

// WorkspaceSpec defines model for WorkspaceSpec.
type WorkspaceSpec struct {
	Parameters   *map[string]interface{} `json:"parameters,omitempty"`
	WorkflowName string                  `json:"workflow_name"`
}

// AsOpenAICredentialBody returns the union data inside the CredentialBody as a OpenAICredentialBody
func (t CredentialBody) AsOpenAICredentialBody() (OpenAICredentialBody, error) {
	var body OpenAICredentialBody
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOpenAICredentialBody overwrites any union data inside the CredentialBody as the provided OpenAICredentialBody
func (t *CredentialBody) FromOpenAICredentialBody(v OpenAICredentialBody) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOpenAICredentialBody performs a merge with any union data inside the CredentialBody, using the provided OpenAICredentialBody
func (t *CredentialBody) MergeOpenAICredentialBody(v OpenAICredentialBody) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGeminiCredentialBody returns the union data inside the CredentialBody as a GeminiCredentialBody
func (t CredentialBody) AsGeminiCredentialBody() (GeminiCredentialBody, error) {
	var body GeminiCredentialBody
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeminiCredentialBody overwrites any union data inside the CredentialBody as the provided GeminiCredentialBody
func (t *CredentialBody) FromGeminiCredentialBody(v GeminiCredentialBody) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeminiCredentialBody performs a merge with any union data inside the CredentialBody, using the provided GeminiCredentialBody
func (t *CredentialBody) MergeGeminiCredentialBody(v GeminiCredentialBody) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDashScopeCredentialBody returns the union data inside the CredentialBody as a DashScopeCredentialBody
func (t CredentialBody) AsDashScopeCredentialBody() (DashScopeCredentialBody, error) {
	var body DashScopeCredentialBody
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDashScopeCredentialBody overwrites any union data inside the CredentialBody as the provided DashScopeCredentialBody
func (t *CredentialBody) FromDashScopeCredentialBody(v DashScopeCredentialBody) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDashScopeCredentialBody performs a merge with any union data inside the CredentialBody, using the provided DashScopeCredentialBody
func (t *CredentialBody) MergeDashScopeCredentialBody(v DashScopeCredentialBody) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMiniMaxCredentialBody returns the union data inside the CredentialBody as a MiniMaxCredentialBody
func (t CredentialBody) AsMiniMaxCredentialBody() (MiniMaxCredentialBody, error) {
	var body MiniMaxCredentialBody
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMiniMaxCredentialBody overwrites any union data inside the CredentialBody as the provided MiniMaxCredentialBody
func (t *CredentialBody) FromMiniMaxCredentialBody(v MiniMaxCredentialBody) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMiniMaxCredentialBody performs a merge with any union data inside the CredentialBody, using the provided MiniMaxCredentialBody
func (t *CredentialBody) MergeMiniMaxCredentialBody(v MiniMaxCredentialBody) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVolcCredentialBody returns the union data inside the CredentialBody as a VolcCredentialBody
func (t CredentialBody) AsVolcCredentialBody() (VolcCredentialBody, error) {
	var body VolcCredentialBody
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVolcCredentialBody overwrites any union data inside the CredentialBody as the provided VolcCredentialBody
func (t *CredentialBody) FromVolcCredentialBody(v VolcCredentialBody) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVolcCredentialBody performs a merge with any union data inside the CredentialBody, using the provided VolcCredentialBody
func (t *CredentialBody) MergeVolcCredentialBody(v VolcCredentialBody) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CredentialBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CredentialBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsACLPolicyBindingResource returns the union data inside the Resource as a ACLPolicyBindingResource
func (t Resource) AsACLPolicyBindingResource() (ACLPolicyBindingResource, error) {
	var body ACLPolicyBindingResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromACLPolicyBindingResource overwrites any union data inside the Resource as the provided ACLPolicyBindingResource
func (t *Resource) FromACLPolicyBindingResource(v ACLPolicyBindingResource) error {
	v.Kind = "ACLPolicyBindingResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeACLPolicyBindingResource performs a merge with any union data inside the Resource, using the provided ACLPolicyBindingResource
func (t *Resource) MergeACLPolicyBindingResource(v ACLPolicyBindingResource) error {
	v.Kind = "ACLPolicyBindingResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsACLRoleResource returns the union data inside the Resource as a ACLRoleResource
func (t Resource) AsACLRoleResource() (ACLRoleResource, error) {
	var body ACLRoleResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromACLRoleResource overwrites any union data inside the Resource as the provided ACLRoleResource
func (t *Resource) FromACLRoleResource(v ACLRoleResource) error {
	v.Kind = "ACLRoleResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeACLRoleResource performs a merge with any union data inside the Resource, using the provided ACLRoleResource
func (t *Resource) MergeACLRoleResource(v ACLRoleResource) error {
	v.Kind = "ACLRoleResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsACLViewResource returns the union data inside the Resource as a ACLViewResource
func (t Resource) AsACLViewResource() (ACLViewResource, error) {
	var body ACLViewResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromACLViewResource overwrites any union data inside the Resource as the provided ACLViewResource
func (t *Resource) FromACLViewResource(v ACLViewResource) error {
	v.Kind = "ACLViewResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeACLViewResource performs a merge with any union data inside the Resource, using the provided ACLViewResource
func (t *Resource) MergeACLViewResource(v ACLViewResource) error {
	v.Kind = "ACLViewResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCredentialResource returns the union data inside the Resource as a CredentialResource
func (t Resource) AsCredentialResource() (CredentialResource, error) {
	var body CredentialResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCredentialResource overwrites any union data inside the Resource as the provided CredentialResource
func (t *Resource) FromCredentialResource(v CredentialResource) error {
	v.Kind = "CredentialResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCredentialResource performs a merge with any union data inside the Resource, using the provided CredentialResource
func (t *Resource) MergeCredentialResource(v CredentialResource) error {
	v.Kind = "CredentialResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFirmwareResource returns the union data inside the Resource as a FirmwareResource
func (t Resource) AsFirmwareResource() (FirmwareResource, error) {
	var body FirmwareResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFirmwareResource overwrites any union data inside the Resource as the provided FirmwareResource
func (t *Resource) FromFirmwareResource(v FirmwareResource) error {
	v.Kind = "FirmwareResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFirmwareResource performs a merge with any union data inside the Resource, using the provided FirmwareResource
func (t *Resource) MergeFirmwareResource(v FirmwareResource) error {
	v.Kind = "FirmwareResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsModelResource returns the union data inside the Resource as a ModelResource
func (t Resource) AsModelResource() (ModelResource, error) {
	var body ModelResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromModelResource overwrites any union data inside the Resource as the provided ModelResource
func (t *Resource) FromModelResource(v ModelResource) error {
	v.Kind = "ModelResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeModelResource performs a merge with any union data inside the Resource, using the provided ModelResource
func (t *Resource) MergeModelResource(v ModelResource) error {
	v.Kind = "ModelResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDashScopeTenantResource returns the union data inside the Resource as a DashScopeTenantResource
func (t Resource) AsDashScopeTenantResource() (DashScopeTenantResource, error) {
	var body DashScopeTenantResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDashScopeTenantResource overwrites any union data inside the Resource as the provided DashScopeTenantResource
func (t *Resource) FromDashScopeTenantResource(v DashScopeTenantResource) error {
	v.Kind = "DashScopeTenantResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDashScopeTenantResource performs a merge with any union data inside the Resource, using the provided DashScopeTenantResource
func (t *Resource) MergeDashScopeTenantResource(v DashScopeTenantResource) error {
	v.Kind = "DashScopeTenantResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGeminiTenantResource returns the union data inside the Resource as a GeminiTenantResource
func (t Resource) AsGeminiTenantResource() (GeminiTenantResource, error) {
	var body GeminiTenantResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGeminiTenantResource overwrites any union data inside the Resource as the provided GeminiTenantResource
func (t *Resource) FromGeminiTenantResource(v GeminiTenantResource) error {
	v.Kind = "GeminiTenantResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGeminiTenantResource performs a merge with any union data inside the Resource, using the provided GeminiTenantResource
func (t *Resource) MergeGeminiTenantResource(v GeminiTenantResource) error {
	v.Kind = "GeminiTenantResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMiniMaxTenantResource returns the union data inside the Resource as a MiniMaxTenantResource
func (t Resource) AsMiniMaxTenantResource() (MiniMaxTenantResource, error) {
	var body MiniMaxTenantResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMiniMaxTenantResource overwrites any union data inside the Resource as the provided MiniMaxTenantResource
func (t *Resource) FromMiniMaxTenantResource(v MiniMaxTenantResource) error {
	v.Kind = "MiniMaxTenantResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMiniMaxTenantResource performs a merge with any union data inside the Resource, using the provided MiniMaxTenantResource
func (t *Resource) MergeMiniMaxTenantResource(v MiniMaxTenantResource) error {
	v.Kind = "MiniMaxTenantResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOpenAITenantResource returns the union data inside the Resource as a OpenAITenantResource
func (t Resource) AsOpenAITenantResource() (OpenAITenantResource, error) {
	var body OpenAITenantResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOpenAITenantResource overwrites any union data inside the Resource as the provided OpenAITenantResource
func (t *Resource) FromOpenAITenantResource(v OpenAITenantResource) error {
	v.Kind = "OpenAITenantResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOpenAITenantResource performs a merge with any union data inside the Resource, using the provided OpenAITenantResource
func (t *Resource) MergeOpenAITenantResource(v OpenAITenantResource) error {
	v.Kind = "OpenAITenantResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVolcTenantResource returns the union data inside the Resource as a VolcTenantResource
func (t Resource) AsVolcTenantResource() (VolcTenantResource, error) {
	var body VolcTenantResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVolcTenantResource overwrites any union data inside the Resource as the provided VolcTenantResource
func (t *Resource) FromVolcTenantResource(v VolcTenantResource) error {
	v.Kind = "VolcTenantResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVolcTenantResource performs a merge with any union data inside the Resource, using the provided VolcTenantResource
func (t *Resource) MergeVolcTenantResource(v VolcTenantResource) error {
	v.Kind = "VolcTenantResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVoiceResource returns the union data inside the Resource as a VoiceResource
func (t Resource) AsVoiceResource() (VoiceResource, error) {
	var body VoiceResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVoiceResource overwrites any union data inside the Resource as the provided VoiceResource
func (t *Resource) FromVoiceResource(v VoiceResource) error {
	v.Kind = "VoiceResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVoiceResource performs a merge with any union data inside the Resource, using the provided VoiceResource
func (t *Resource) MergeVoiceResource(v VoiceResource) error {
	v.Kind = "VoiceResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWorkflowResource returns the union data inside the Resource as a WorkflowResource
func (t Resource) AsWorkflowResource() (WorkflowResource, error) {
	var body WorkflowResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWorkflowResource overwrites any union data inside the Resource as the provided WorkflowResource
func (t *Resource) FromWorkflowResource(v WorkflowResource) error {
	v.Kind = "WorkflowResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWorkflowResource performs a merge with any union data inside the Resource, using the provided WorkflowResource
func (t *Resource) MergeWorkflowResource(v WorkflowResource) error {
	v.Kind = "WorkflowResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWorkspaceResource returns the union data inside the Resource as a WorkspaceResource
func (t Resource) AsWorkspaceResource() (WorkspaceResource, error) {
	var body WorkspaceResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWorkspaceResource overwrites any union data inside the Resource as the provided WorkspaceResource
func (t *Resource) FromWorkspaceResource(v WorkspaceResource) error {
	v.Kind = "WorkspaceResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWorkspaceResource performs a merge with any union data inside the Resource, using the provided WorkspaceResource
func (t *Resource) MergeWorkspaceResource(v WorkspaceResource) error {
	v.Kind = "WorkspaceResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPeerConfigResource returns the union data inside the Resource as a PeerConfigResource
func (t Resource) AsPeerConfigResource() (PeerConfigResource, error) {
	var body PeerConfigResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPeerConfigResource overwrites any union data inside the Resource as the provided PeerConfigResource
func (t *Resource) FromPeerConfigResource(v PeerConfigResource) error {
	v.Kind = "PeerConfigResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePeerConfigResource performs a merge with any union data inside the Resource, using the provided PeerConfigResource
func (t *Resource) MergePeerConfigResource(v PeerConfigResource) error {
	v.Kind = "PeerConfigResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPetSpeciesResource returns the union data inside the Resource as a PetSpeciesResource
func (t Resource) AsPetSpeciesResource() (PetSpeciesResource, error) {
	var body PetSpeciesResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPetSpeciesResource overwrites any union data inside the Resource as the provided PetSpeciesResource
func (t *Resource) FromPetSpeciesResource(v PetSpeciesResource) error {
	v.Kind = "PetSpeciesResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePetSpeciesResource performs a merge with any union data inside the Resource, using the provided PetSpeciesResource
func (t *Resource) MergePetSpeciesResource(v PetSpeciesResource) error {
	v.Kind = "PetSpeciesResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBadgeResource returns the union data inside the Resource as a BadgeResource
func (t Resource) AsBadgeResource() (BadgeResource, error) {
	var body BadgeResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBadgeResource overwrites any union data inside the Resource as the provided BadgeResource
func (t *Resource) FromBadgeResource(v BadgeResource) error {
	v.Kind = "BadgeResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBadgeResource performs a merge with any union data inside the Resource, using the provided BadgeResource
func (t *Resource) MergeBadgeResource(v BadgeResource) error {
	v.Kind = "BadgeResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResourceListResource returns the union data inside the Resource as a ResourceListResource
func (t Resource) AsResourceListResource() (ResourceListResource, error) {
	var body ResourceListResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceListResource overwrites any union data inside the Resource as the provided ResourceListResource
func (t *Resource) FromResourceListResource(v ResourceListResource) error {
	v.Kind = "ResourceListResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceListResource performs a merge with any union data inside the Resource, using the provided ResourceListResource
func (t *Resource) MergeResourceListResource(v ResourceListResource) error {
	v.Kind = "ResourceListResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Resource) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Resource) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ACLPolicyBindingResource":
		return t.AsACLPolicyBindingResource()
	case "ACLRoleResource":
		return t.AsACLRoleResource()
	case "ACLViewResource":
		return t.AsACLViewResource()
	case "BadgeResource":
		return t.AsBadgeResource()
	case "CredentialResource":
		return t.AsCredentialResource()
	case "DashScopeTenantResource":
		return t.AsDashScopeTenantResource()
	case "FirmwareResource":
		return t.AsFirmwareResource()
	case "GeminiTenantResource":
		return t.AsGeminiTenantResource()
	case "MiniMaxTenantResource":
		return t.AsMiniMaxTenantResource()
	case "ModelResource":
		return t.AsModelResource()
	case "OpenAITenantResource":
		return t.AsOpenAITenantResource()
	case "PeerConfigResource":
		return t.AsPeerConfigResource()
	case "PetSpeciesResource":
		return t.AsPetSpeciesResource()
	case "ResourceListResource":
		return t.AsResourceListResource()
	case "VoiceResource":
		return t.AsVoiceResource()
	case "VolcTenantResource":
		return t.AsVolcTenantResource()
	case "WorkflowResource":
		return t.AsWorkflowResource()
	case "WorkspaceResource":
		return t.AsWorkspaceResource()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Resource) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Resource) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
