package: adminhttp
generate:
  fiber-server: true
  strict-server: true
  client: true
  models: true
import-mapping:
  ./type/server.json: github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/rpcapi
  ./types.json: github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/apitypes
output-options:
  skip-prune: true
  user-templates:
    strict/strict-fiber.tmpl: templates/strict/strict-fiber.tmpl
