// Peer RPC enums payload protobuf schema.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payload/enums.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ASTTranslateMode int32

const (
	ASTTranslateMode_ASTTRANSLATE_MODE_UNSPECIFIED ASTTranslateMode = 0
	ASTTranslateMode_ASTTRANSLATE_MODE_S2T         ASTTranslateMode = 1
	ASTTranslateMode_ASTTRANSLATE_MODE_S2S         ASTTranslateMode = 2
)

// Enum value maps for ASTTranslateMode.
var (
	ASTTranslateMode_name = map[int32]string{
		0: "ASTTRANSLATE_MODE_UNSPECIFIED",
		1: "ASTTRANSLATE_MODE_S2T",
		2: "ASTTRANSLATE_MODE_S2S",
	}
	ASTTranslateMode_value = map[string]int32{
		"ASTTRANSLATE_MODE_UNSPECIFIED": 0,
		"ASTTRANSLATE_MODE_S2T":         1,
		"ASTTRANSLATE_MODE_S2S":         2,
	}
)

func (x ASTTranslateMode) Enum() *ASTTranslateMode {
	p := new(ASTTranslateMode)
	*p = x
	return p
}

func (x ASTTranslateMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ASTTranslateMode) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[0].Descriptor()
}

func (ASTTranslateMode) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[0]
}

func (x ASTTranslateMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ASTTranslateMode.Descriptor instead.
func (ASTTranslateMode) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{0}
}

type ASTTranslateWorkspaceParametersAgentType int32

const (
	ASTTranslateWorkspaceParametersAgentType_ASTTRANSLATE_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED   ASTTranslateWorkspaceParametersAgentType = 0
	ASTTranslateWorkspaceParametersAgentType_ASTTRANSLATE_WORKSPACE_PARAMETERS_AGENT_TYPE_AST_TRANSLATE ASTTranslateWorkspaceParametersAgentType = 1
)

// Enum value maps for ASTTranslateWorkspaceParametersAgentType.
var (
	ASTTranslateWorkspaceParametersAgentType_name = map[int32]string{
		0: "ASTTRANSLATE_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED",
		1: "ASTTRANSLATE_WORKSPACE_PARAMETERS_AGENT_TYPE_AST_TRANSLATE",
	}
	ASTTranslateWorkspaceParametersAgentType_value = map[string]int32{
		"ASTTRANSLATE_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED":   0,
		"ASTTRANSLATE_WORKSPACE_PARAMETERS_AGENT_TYPE_AST_TRANSLATE": 1,
	}
)

func (x ASTTranslateWorkspaceParametersAgentType) Enum() *ASTTranslateWorkspaceParametersAgentType {
	p := new(ASTTranslateWorkspaceParametersAgentType)
	*p = x
	return p
}

func (x ASTTranslateWorkspaceParametersAgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ASTTranslateWorkspaceParametersAgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[1].Descriptor()
}

func (ASTTranslateWorkspaceParametersAgentType) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[1]
}

func (x ASTTranslateWorkspaceParametersAgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ASTTranslateWorkspaceParametersAgentType.Descriptor instead.
func (ASTTranslateWorkspaceParametersAgentType) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{1}
}

type ChatRoomMode int32

const (
	ChatRoomMode_CHAT_ROOM_MODE_UNSPECIFIED ChatRoomMode = 0
	ChatRoomMode_CHAT_ROOM_MODE_DIRECT      ChatRoomMode = 1
	ChatRoomMode_CHAT_ROOM_MODE_GROUP       ChatRoomMode = 2
)

// Enum value maps for ChatRoomMode.
var (
	ChatRoomMode_name = map[int32]string{
		0: "CHAT_ROOM_MODE_UNSPECIFIED",
		1: "CHAT_ROOM_MODE_DIRECT",
		2: "CHAT_ROOM_MODE_GROUP",
	}
	ChatRoomMode_value = map[string]int32{
		"CHAT_ROOM_MODE_UNSPECIFIED": 0,
		"CHAT_ROOM_MODE_DIRECT":      1,
		"CHAT_ROOM_MODE_GROUP":       2,
	}
)

func (x ChatRoomMode) Enum() *ChatRoomMode {
	p := new(ChatRoomMode)
	*p = x
	return p
}

func (x ChatRoomMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatRoomMode) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[2].Descriptor()
}

func (ChatRoomMode) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[2]
}

func (x ChatRoomMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatRoomMode.Descriptor instead.
func (ChatRoomMode) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{2}
}

type ChatRoomWorkspaceParametersAgentType int32

const (
	ChatRoomWorkspaceParametersAgentType_CHAT_ROOM_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED ChatRoomWorkspaceParametersAgentType = 0
	ChatRoomWorkspaceParametersAgentType_CHAT_ROOM_WORKSPACE_PARAMETERS_AGENT_TYPE_CHATROOM    ChatRoomWorkspaceParametersAgentType = 1
)

// Enum value maps for ChatRoomWorkspaceParametersAgentType.
var (
	ChatRoomWorkspaceParametersAgentType_name = map[int32]string{
		0: "CHAT_ROOM_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED",
		1: "CHAT_ROOM_WORKSPACE_PARAMETERS_AGENT_TYPE_CHATROOM",
	}
	ChatRoomWorkspaceParametersAgentType_value = map[string]int32{
		"CHAT_ROOM_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED": 0,
		"CHAT_ROOM_WORKSPACE_PARAMETERS_AGENT_TYPE_CHATROOM":    1,
	}
)

func (x ChatRoomWorkspaceParametersAgentType) Enum() *ChatRoomWorkspaceParametersAgentType {
	p := new(ChatRoomWorkspaceParametersAgentType)
	*p = x
	return p
}

func (x ChatRoomWorkspaceParametersAgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatRoomWorkspaceParametersAgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[3].Descriptor()
}

func (ChatRoomWorkspaceParametersAgentType) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[3]
}

func (x ChatRoomWorkspaceParametersAgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatRoomWorkspaceParametersAgentType.Descriptor instead.
func (ChatRoomWorkspaceParametersAgentType) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{3}
}

type DashScopeTenantModelProviderDataApiMode int32

const (
	DashScopeTenantModelProviderDataApiMode_DASH_SCOPE_TENANT_MODEL_PROVIDER_DATA_API_MODE_UNSPECIFIED      DashScopeTenantModelProviderDataApiMode = 0
	DashScopeTenantModelProviderDataApiMode_DASH_SCOPE_TENANT_MODEL_PROVIDER_DATA_API_MODE_CHAT_COMPLETIONS DashScopeTenantModelProviderDataApiMode = 1
	DashScopeTenantModelProviderDataApiMode_DASH_SCOPE_TENANT_MODEL_PROVIDER_DATA_API_MODE_REALTIME         DashScopeTenantModelProviderDataApiMode = 2
)

// Enum value maps for DashScopeTenantModelProviderDataApiMode.
var (
	DashScopeTenantModelProviderDataApiMode_name = map[int32]string{
		0: "DASH_SCOPE_TENANT_MODEL_PROVIDER_DATA_API_MODE_UNSPECIFIED",
		1: "DASH_SCOPE_TENANT_MODEL_PROVIDER_DATA_API_MODE_CHAT_COMPLETIONS",
		2: "DASH_SCOPE_TENANT_MODEL_PROVIDER_DATA_API_MODE_REALTIME",
	}
	DashScopeTenantModelProviderDataApiMode_value = map[string]int32{
		"DASH_SCOPE_TENANT_MODEL_PROVIDER_DATA_API_MODE_UNSPECIFIED":      0,
		"DASH_SCOPE_TENANT_MODEL_PROVIDER_DATA_API_MODE_CHAT_COMPLETIONS": 1,
		"DASH_SCOPE_TENANT_MODEL_PROVIDER_DATA_API_MODE_REALTIME":         2,
	}
)

func (x DashScopeTenantModelProviderDataApiMode) Enum() *DashScopeTenantModelProviderDataApiMode {
	p := new(DashScopeTenantModelProviderDataApiMode)
	*p = x
	return p
}

func (x DashScopeTenantModelProviderDataApiMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DashScopeTenantModelProviderDataApiMode) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[4].Descriptor()
}

func (DashScopeTenantModelProviderDataApiMode) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[4]
}

func (x DashScopeTenantModelProviderDataApiMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DashScopeTenantModelProviderDataApiMode.Descriptor instead.
func (DashScopeTenantModelProviderDataApiMode) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{4}
}

type DoubaoRealtimeAudioFormatType int32

const (
	DoubaoRealtimeAudioFormatType_DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_UNSPECIFIED DoubaoRealtimeAudioFormatType = 0
	DoubaoRealtimeAudioFormatType_DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_PCM         DoubaoRealtimeAudioFormatType = 1
	DoubaoRealtimeAudioFormatType_DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_PCM_S16LE   DoubaoRealtimeAudioFormatType = 2
	DoubaoRealtimeAudioFormatType_DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_SPEECH_OPUS DoubaoRealtimeAudioFormatType = 3
	DoubaoRealtimeAudioFormatType_DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_OGG_OPUS    DoubaoRealtimeAudioFormatType = 4
)

// Enum value maps for DoubaoRealtimeAudioFormatType.
var (
	DoubaoRealtimeAudioFormatType_name = map[int32]string{
		0: "DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_UNSPECIFIED",
		1: "DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_PCM",
		2: "DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_PCM_S16LE",
		3: "DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_SPEECH_OPUS",
		4: "DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_OGG_OPUS",
	}
	DoubaoRealtimeAudioFormatType_value = map[string]int32{
		"DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_UNSPECIFIED": 0,
		"DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_PCM":         1,
		"DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_PCM_S16LE":   2,
		"DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_SPEECH_OPUS": 3,
		"DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_OGG_OPUS":    4,
	}
)

func (x DoubaoRealtimeAudioFormatType) Enum() *DoubaoRealtimeAudioFormatType {
	p := new(DoubaoRealtimeAudioFormatType)
	*p = x
	return p
}

func (x DoubaoRealtimeAudioFormatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DoubaoRealtimeAudioFormatType) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[5].Descriptor()
}

func (DoubaoRealtimeAudioFormatType) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[5]
}

func (x DoubaoRealtimeAudioFormatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DoubaoRealtimeAudioFormatType.Descriptor instead.
func (DoubaoRealtimeAudioFormatType) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{5}
}

type DoubaoRealtimeDialogExtraVolcWebsearchType int32

const (
	DoubaoRealtimeDialogExtraVolcWebsearchType_DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_UNSPECIFIED DoubaoRealtimeDialogExtraVolcWebsearchType = 0
	DoubaoRealtimeDialogExtraVolcWebsearchType_DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_WEB         DoubaoRealtimeDialogExtraVolcWebsearchType = 1
	DoubaoRealtimeDialogExtraVolcWebsearchType_DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_WEB_SUMMARY DoubaoRealtimeDialogExtraVolcWebsearchType = 2
	DoubaoRealtimeDialogExtraVolcWebsearchType_DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_WEB_AGENT   DoubaoRealtimeDialogExtraVolcWebsearchType = 3
)

// Enum value maps for DoubaoRealtimeDialogExtraVolcWebsearchType.
var (
	DoubaoRealtimeDialogExtraVolcWebsearchType_name = map[int32]string{
		0: "DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_UNSPECIFIED",
		1: "DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_WEB",
		2: "DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_WEB_SUMMARY",
		3: "DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_WEB_AGENT",
	}
	DoubaoRealtimeDialogExtraVolcWebsearchType_value = map[string]int32{
		"DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_UNSPECIFIED": 0,
		"DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_WEB":         1,
		"DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_WEB_SUMMARY": 2,
		"DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_WEB_AGENT":   3,
	}
)

func (x DoubaoRealtimeDialogExtraVolcWebsearchType) Enum() *DoubaoRealtimeDialogExtraVolcWebsearchType {
	p := new(DoubaoRealtimeDialogExtraVolcWebsearchType)
	*p = x
	return p
}

func (x DoubaoRealtimeDialogExtraVolcWebsearchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DoubaoRealtimeDialogExtraVolcWebsearchType) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[6].Descriptor()
}

func (DoubaoRealtimeDialogExtraVolcWebsearchType) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[6]
}

func (x DoubaoRealtimeDialogExtraVolcWebsearchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DoubaoRealtimeDialogExtraVolcWebsearchType.Descriptor instead.
func (DoubaoRealtimeDialogExtraVolcWebsearchType) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{6}
}

type DoubaoRealtimeFunctionToolType int32

const (
	DoubaoRealtimeFunctionToolType_DOUBAO_REALTIME_FUNCTION_TOOL_TYPE_UNSPECIFIED DoubaoRealtimeFunctionToolType = 0
	DoubaoRealtimeFunctionToolType_DOUBAO_REALTIME_FUNCTION_TOOL_TYPE_FUNCTION    DoubaoRealtimeFunctionToolType = 1
)

// Enum value maps for DoubaoRealtimeFunctionToolType.
var (
	DoubaoRealtimeFunctionToolType_name = map[int32]string{
		0: "DOUBAO_REALTIME_FUNCTION_TOOL_TYPE_UNSPECIFIED",
		1: "DOUBAO_REALTIME_FUNCTION_TOOL_TYPE_FUNCTION",
	}
	DoubaoRealtimeFunctionToolType_value = map[string]int32{
		"DOUBAO_REALTIME_FUNCTION_TOOL_TYPE_UNSPECIFIED": 0,
		"DOUBAO_REALTIME_FUNCTION_TOOL_TYPE_FUNCTION":    1,
	}
)

func (x DoubaoRealtimeFunctionToolType) Enum() *DoubaoRealtimeFunctionToolType {
	p := new(DoubaoRealtimeFunctionToolType)
	*p = x
	return p
}

func (x DoubaoRealtimeFunctionToolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DoubaoRealtimeFunctionToolType) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[7].Descriptor()
}

func (DoubaoRealtimeFunctionToolType) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[7]
}

func (x DoubaoRealtimeFunctionToolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DoubaoRealtimeFunctionToolType.Descriptor instead.
func (DoubaoRealtimeFunctionToolType) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{7}
}

type DoubaoRealtimeWorkspaceParametersAgentType int32

const (
	DoubaoRealtimeWorkspaceParametersAgentType_DOUBAO_REALTIME_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED     DoubaoRealtimeWorkspaceParametersAgentType = 0
	DoubaoRealtimeWorkspaceParametersAgentType_DOUBAO_REALTIME_WORKSPACE_PARAMETERS_AGENT_TYPE_DOUBAO_REALTIME DoubaoRealtimeWorkspaceParametersAgentType = 1
)

// Enum value maps for DoubaoRealtimeWorkspaceParametersAgentType.
var (
	DoubaoRealtimeWorkspaceParametersAgentType_name = map[int32]string{
		0: "DOUBAO_REALTIME_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED",
		1: "DOUBAO_REALTIME_WORKSPACE_PARAMETERS_AGENT_TYPE_DOUBAO_REALTIME",
	}
	DoubaoRealtimeWorkspaceParametersAgentType_value = map[string]int32{
		"DOUBAO_REALTIME_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED":     0,
		"DOUBAO_REALTIME_WORKSPACE_PARAMETERS_AGENT_TYPE_DOUBAO_REALTIME": 1,
	}
)

func (x DoubaoRealtimeWorkspaceParametersAgentType) Enum() *DoubaoRealtimeWorkspaceParametersAgentType {
	p := new(DoubaoRealtimeWorkspaceParametersAgentType)
	*p = x
	return p
}

func (x DoubaoRealtimeWorkspaceParametersAgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DoubaoRealtimeWorkspaceParametersAgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[8].Descriptor()
}

func (DoubaoRealtimeWorkspaceParametersAgentType) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[8]
}

func (x DoubaoRealtimeWorkspaceParametersAgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DoubaoRealtimeWorkspaceParametersAgentType.Descriptor instead.
func (DoubaoRealtimeWorkspaceParametersAgentType) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{8}
}

type FirmwareArtifactEntryType int32

const (
	FirmwareArtifactEntryType_FIRMWARE_ARTIFACT_ENTRY_TYPE_UNSPECIFIED FirmwareArtifactEntryType = 0
	FirmwareArtifactEntryType_FIRMWARE_ARTIFACT_ENTRY_TYPE_FILE        FirmwareArtifactEntryType = 1
	FirmwareArtifactEntryType_FIRMWARE_ARTIFACT_ENTRY_TYPE_DIR         FirmwareArtifactEntryType = 2
)

// Enum value maps for FirmwareArtifactEntryType.
var (
	FirmwareArtifactEntryType_name = map[int32]string{
		0: "FIRMWARE_ARTIFACT_ENTRY_TYPE_UNSPECIFIED",
		1: "FIRMWARE_ARTIFACT_ENTRY_TYPE_FILE",
		2: "FIRMWARE_ARTIFACT_ENTRY_TYPE_DIR",
	}
	FirmwareArtifactEntryType_value = map[string]int32{
		"FIRMWARE_ARTIFACT_ENTRY_TYPE_UNSPECIFIED": 0,
		"FIRMWARE_ARTIFACT_ENTRY_TYPE_FILE":        1,
		"FIRMWARE_ARTIFACT_ENTRY_TYPE_DIR":         2,
	}
)

func (x FirmwareArtifactEntryType) Enum() *FirmwareArtifactEntryType {
	p := new(FirmwareArtifactEntryType)
	*p = x
	return p
}

func (x FirmwareArtifactEntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FirmwareArtifactEntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[9].Descriptor()
}

func (FirmwareArtifactEntryType) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[9]
}

func (x FirmwareArtifactEntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FirmwareArtifactEntryType.Descriptor instead.
func (FirmwareArtifactEntryType) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{9}
}

type FirmwareChannelName int32

const (
	FirmwareChannelName_FIRMWARE_CHANNEL_NAME_UNSPECIFIED FirmwareChannelName = 0
	FirmwareChannelName_FIRMWARE_CHANNEL_NAME_STABLE      FirmwareChannelName = 1
	FirmwareChannelName_FIRMWARE_CHANNEL_NAME_BETA        FirmwareChannelName = 2
	FirmwareChannelName_FIRMWARE_CHANNEL_NAME_DEVELOP     FirmwareChannelName = 3
	FirmwareChannelName_FIRMWARE_CHANNEL_NAME_PENDING     FirmwareChannelName = 4
)

// Enum value maps for FirmwareChannelName.
var (
	FirmwareChannelName_name = map[int32]string{
		0: "FIRMWARE_CHANNEL_NAME_UNSPECIFIED",
		1: "FIRMWARE_CHANNEL_NAME_STABLE",
		2: "FIRMWARE_CHANNEL_NAME_BETA",
		3: "FIRMWARE_CHANNEL_NAME_DEVELOP",
		4: "FIRMWARE_CHANNEL_NAME_PENDING",
	}
	FirmwareChannelName_value = map[string]int32{
		"FIRMWARE_CHANNEL_NAME_UNSPECIFIED": 0,
		"FIRMWARE_CHANNEL_NAME_STABLE":      1,
		"FIRMWARE_CHANNEL_NAME_BETA":        2,
		"FIRMWARE_CHANNEL_NAME_DEVELOP":     3,
		"FIRMWARE_CHANNEL_NAME_PENDING":     4,
	}
)

func (x FirmwareChannelName) Enum() *FirmwareChannelName {
	p := new(FirmwareChannelName)
	*p = x
	return p
}

func (x FirmwareChannelName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FirmwareChannelName) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[10].Descriptor()
}

func (FirmwareChannelName) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[10]
}

func (x FirmwareChannelName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FirmwareChannelName.Descriptor instead.
func (FirmwareChannelName) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{10}
}

type FlowcraftConversationParametersAgentInitiativePolicy int32

const (
	FlowcraftConversationParametersAgentInitiativePolicy_FLOWCRAFT_CONVERSATION_PARAMETERS_AGENT_INITIATIVE_POLICY_UNSPECIFIED     FlowcraftConversationParametersAgentInitiativePolicy = 0
	FlowcraftConversationParametersAgentInitiativePolicy_FLOWCRAFT_CONVERSATION_PARAMETERS_AGENT_INITIATIVE_POLICY_ONCE_WHEN_EMPTY FlowcraftConversationParametersAgentInitiativePolicy = 1
	FlowcraftConversationParametersAgentInitiativePolicy_FLOWCRAFT_CONVERSATION_PARAMETERS_AGENT_INITIATIVE_POLICY_ON_RELOAD       FlowcraftConversationParametersAgentInitiativePolicy = 2
)

// Enum value maps for FlowcraftConversationParametersAgentInitiativePolicy.
var (
	FlowcraftConversationParametersAgentInitiativePolicy_name = map[int32]string{
		0: "FLOWCRAFT_CONVERSATION_PARAMETERS_AGENT_INITIATIVE_POLICY_UNSPECIFIED",
		1: "FLOWCRAFT_CONVERSATION_PARAMETERS_AGENT_INITIATIVE_POLICY_ONCE_WHEN_EMPTY",
		2: "FLOWCRAFT_CONVERSATION_PARAMETERS_AGENT_INITIATIVE_POLICY_ON_RELOAD",
	}
	FlowcraftConversationParametersAgentInitiativePolicy_value = map[string]int32{
		"FLOWCRAFT_CONVERSATION_PARAMETERS_AGENT_INITIATIVE_POLICY_UNSPECIFIED":     0,
		"FLOWCRAFT_CONVERSATION_PARAMETERS_AGENT_INITIATIVE_POLICY_ONCE_WHEN_EMPTY": 1,
		"FLOWCRAFT_CONVERSATION_PARAMETERS_AGENT_INITIATIVE_POLICY_ON_RELOAD":       2,
	}
)

func (x FlowcraftConversationParametersAgentInitiativePolicy) Enum() *FlowcraftConversationParametersAgentInitiativePolicy {
	p := new(FlowcraftConversationParametersAgentInitiativePolicy)
	*p = x
	return p
}

func (x FlowcraftConversationParametersAgentInitiativePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowcraftConversationParametersAgentInitiativePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[11].Descriptor()
}

func (FlowcraftConversationParametersAgentInitiativePolicy) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[11]
}

func (x FlowcraftConversationParametersAgentInitiativePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowcraftConversationParametersAgentInitiativePolicy.Descriptor instead.
func (FlowcraftConversationParametersAgentInitiativePolicy) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{11}
}

type FlowcraftConversationParametersInitiative int32

const (
	FlowcraftConversationParametersInitiative_FLOWCRAFT_CONVERSATION_PARAMETERS_INITIATIVE_UNSPECIFIED FlowcraftConversationParametersInitiative = 0
	FlowcraftConversationParametersInitiative_FLOWCRAFT_CONVERSATION_PARAMETERS_INITIATIVE_PEER        FlowcraftConversationParametersInitiative = 1
	FlowcraftConversationParametersInitiative_FLOWCRAFT_CONVERSATION_PARAMETERS_INITIATIVE_AGENT       FlowcraftConversationParametersInitiative = 2
)

// Enum value maps for FlowcraftConversationParametersInitiative.
var (
	FlowcraftConversationParametersInitiative_name = map[int32]string{
		0: "FLOWCRAFT_CONVERSATION_PARAMETERS_INITIATIVE_UNSPECIFIED",
		1: "FLOWCRAFT_CONVERSATION_PARAMETERS_INITIATIVE_PEER",
		2: "FLOWCRAFT_CONVERSATION_PARAMETERS_INITIATIVE_AGENT",
	}
	FlowcraftConversationParametersInitiative_value = map[string]int32{
		"FLOWCRAFT_CONVERSATION_PARAMETERS_INITIATIVE_UNSPECIFIED": 0,
		"FLOWCRAFT_CONVERSATION_PARAMETERS_INITIATIVE_PEER":        1,
		"FLOWCRAFT_CONVERSATION_PARAMETERS_INITIATIVE_AGENT":       2,
	}
)

func (x FlowcraftConversationParametersInitiative) Enum() *FlowcraftConversationParametersInitiative {
	p := new(FlowcraftConversationParametersInitiative)
	*p = x
	return p
}

func (x FlowcraftConversationParametersInitiative) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowcraftConversationParametersInitiative) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[12].Descriptor()
}

func (FlowcraftConversationParametersInitiative) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[12]
}

func (x FlowcraftConversationParametersInitiative) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowcraftConversationParametersInitiative.Descriptor instead.
func (FlowcraftConversationParametersInitiative) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{12}
}

type FlowcraftWorkspaceParametersAgentType int32

const (
	FlowcraftWorkspaceParametersAgentType_FLOWCRAFT_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED FlowcraftWorkspaceParametersAgentType = 0
	FlowcraftWorkspaceParametersAgentType_FLOWCRAFT_WORKSPACE_PARAMETERS_AGENT_TYPE_FLOWCRAFT   FlowcraftWorkspaceParametersAgentType = 1
)

// Enum value maps for FlowcraftWorkspaceParametersAgentType.
var (
	FlowcraftWorkspaceParametersAgentType_name = map[int32]string{
		0: "FLOWCRAFT_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED",
		1: "FLOWCRAFT_WORKSPACE_PARAMETERS_AGENT_TYPE_FLOWCRAFT",
	}
	FlowcraftWorkspaceParametersAgentType_value = map[string]int32{
		"FLOWCRAFT_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED": 0,
		"FLOWCRAFT_WORKSPACE_PARAMETERS_AGENT_TYPE_FLOWCRAFT":   1,
	}
)

func (x FlowcraftWorkspaceParametersAgentType) Enum() *FlowcraftWorkspaceParametersAgentType {
	p := new(FlowcraftWorkspaceParametersAgentType)
	*p = x
	return p
}

func (x FlowcraftWorkspaceParametersAgentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowcraftWorkspaceParametersAgentType) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[13].Descriptor()
}

func (FlowcraftWorkspaceParametersAgentType) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[13]
}

func (x FlowcraftWorkspaceParametersAgentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowcraftWorkspaceParametersAgentType.Descriptor instead.
func (FlowcraftWorkspaceParametersAgentType) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{13}
}

type FriendGroupMemberMutableRole int32

const (
	FriendGroupMemberMutableRole_FRIEND_GROUP_MEMBER_MUTABLE_ROLE_UNSPECIFIED FriendGroupMemberMutableRole = 0
	FriendGroupMemberMutableRole_FRIEND_GROUP_MEMBER_MUTABLE_ROLE_ADMIN       FriendGroupMemberMutableRole = 1
	FriendGroupMemberMutableRole_FRIEND_GROUP_MEMBER_MUTABLE_ROLE_MEMBER      FriendGroupMemberMutableRole = 2
)

// Enum value maps for FriendGroupMemberMutableRole.
var (
	FriendGroupMemberMutableRole_name = map[int32]string{
		0: "FRIEND_GROUP_MEMBER_MUTABLE_ROLE_UNSPECIFIED",
		1: "FRIEND_GROUP_MEMBER_MUTABLE_ROLE_ADMIN",
		2: "FRIEND_GROUP_MEMBER_MUTABLE_ROLE_MEMBER",
	}
	FriendGroupMemberMutableRole_value = map[string]int32{
		"FRIEND_GROUP_MEMBER_MUTABLE_ROLE_UNSPECIFIED": 0,
		"FRIEND_GROUP_MEMBER_MUTABLE_ROLE_ADMIN":       1,
		"FRIEND_GROUP_MEMBER_MUTABLE_ROLE_MEMBER":      2,
	}
)

func (x FriendGroupMemberMutableRole) Enum() *FriendGroupMemberMutableRole {
	p := new(FriendGroupMemberMutableRole)
	*p = x
	return p
}

func (x FriendGroupMemberMutableRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendGroupMemberMutableRole) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[14].Descriptor()
}

func (FriendGroupMemberMutableRole) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[14]
}

func (x FriendGroupMemberMutableRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendGroupMemberMutableRole.Descriptor instead.
func (FriendGroupMemberMutableRole) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{14}
}

type FriendGroupMemberRole int32

const (
	FriendGroupMemberRole_FRIEND_GROUP_MEMBER_ROLE_UNSPECIFIED FriendGroupMemberRole = 0
	FriendGroupMemberRole_FRIEND_GROUP_MEMBER_ROLE_OWNER       FriendGroupMemberRole = 1
	FriendGroupMemberRole_FRIEND_GROUP_MEMBER_ROLE_ADMIN       FriendGroupMemberRole = 2
	FriendGroupMemberRole_FRIEND_GROUP_MEMBER_ROLE_MEMBER      FriendGroupMemberRole = 3
)

// Enum value maps for FriendGroupMemberRole.
var (
	FriendGroupMemberRole_name = map[int32]string{
		0: "FRIEND_GROUP_MEMBER_ROLE_UNSPECIFIED",
		1: "FRIEND_GROUP_MEMBER_ROLE_OWNER",
		2: "FRIEND_GROUP_MEMBER_ROLE_ADMIN",
		3: "FRIEND_GROUP_MEMBER_ROLE_MEMBER",
	}
	FriendGroupMemberRole_value = map[string]int32{
		"FRIEND_GROUP_MEMBER_ROLE_UNSPECIFIED": 0,
		"FRIEND_GROUP_MEMBER_ROLE_OWNER":       1,
		"FRIEND_GROUP_MEMBER_ROLE_ADMIN":       2,
		"FRIEND_GROUP_MEMBER_ROLE_MEMBER":      3,
	}
)

func (x FriendGroupMemberRole) Enum() *FriendGroupMemberRole {
	p := new(FriendGroupMemberRole)
	*p = x
	return p
}

func (x FriendGroupMemberRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendGroupMemberRole) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[15].Descriptor()
}

func (FriendGroupMemberRole) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[15]
}

func (x FriendGroupMemberRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendGroupMemberRole.Descriptor instead.
func (FriendGroupMemberRole) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{15}
}

type PeerRole int32

const (
	PeerRole_PEER_ROLE_UNSPECIFIED PeerRole = 0
	PeerRole_PEER_ROLE_ADMIN       PeerRole = 1
	PeerRole_PEER_ROLE_SERVER      PeerRole = 2
	PeerRole_PEER_ROLE_EDGE_NODE   PeerRole = 3
	PeerRole_PEER_ROLE_CLIENT      PeerRole = 4
)

// Enum value maps for PeerRole.
var (
	PeerRole_name = map[int32]string{
		0: "PEER_ROLE_UNSPECIFIED",
		1: "PEER_ROLE_ADMIN",
		2: "PEER_ROLE_SERVER",
		3: "PEER_ROLE_EDGE_NODE",
		4: "PEER_ROLE_CLIENT",
	}
	PeerRole_value = map[string]int32{
		"PEER_ROLE_UNSPECIFIED": 0,
		"PEER_ROLE_ADMIN":       1,
		"PEER_ROLE_SERVER":      2,
		"PEER_ROLE_EDGE_NODE":   3,
		"PEER_ROLE_CLIENT":      4,
	}
)

func (x PeerRole) Enum() *PeerRole {
	p := new(PeerRole)
	*p = x
	return p
}

func (x PeerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[16].Descriptor()
}

func (PeerRole) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[16]
}

func (x PeerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerRole.Descriptor instead.
func (PeerRole) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{16}
}

type ModelKind int32

const (
	ModelKind_MODEL_KIND_UNSPECIFIED ModelKind = 0
	ModelKind_MODEL_KIND_LLM         ModelKind = 1
	ModelKind_MODEL_KIND_TTS         ModelKind = 2
	ModelKind_MODEL_KIND_ASR         ModelKind = 3
	ModelKind_MODEL_KIND_REALTIME    ModelKind = 4
	ModelKind_MODEL_KIND_TRANSLATION ModelKind = 5
	ModelKind_MODEL_KIND_EMBEDDING   ModelKind = 6
)

// Enum value maps for ModelKind.
var (
	ModelKind_name = map[int32]string{
		0: "MODEL_KIND_UNSPECIFIED",
		1: "MODEL_KIND_LLM",
		2: "MODEL_KIND_TTS",
		3: "MODEL_KIND_ASR",
		4: "MODEL_KIND_REALTIME",
		5: "MODEL_KIND_TRANSLATION",
		6: "MODEL_KIND_EMBEDDING",
	}
	ModelKind_value = map[string]int32{
		"MODEL_KIND_UNSPECIFIED": 0,
		"MODEL_KIND_LLM":         1,
		"MODEL_KIND_TTS":         2,
		"MODEL_KIND_ASR":         3,
		"MODEL_KIND_REALTIME":    4,
		"MODEL_KIND_TRANSLATION": 5,
		"MODEL_KIND_EMBEDDING":   6,
	}
)

func (x ModelKind) Enum() *ModelKind {
	p := new(ModelKind)
	*p = x
	return p
}

func (x ModelKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelKind) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[17].Descriptor()
}

func (ModelKind) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[17]
}

func (x ModelKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelKind.Descriptor instead.
func (ModelKind) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{17}
}

type ModelProviderKind int32

const (
	ModelProviderKind_MODEL_PROVIDER_KIND_UNSPECIFIED      ModelProviderKind = 0
	ModelProviderKind_MODEL_PROVIDER_KIND_GEMINI_TENANT    ModelProviderKind = 1
	ModelProviderKind_MODEL_PROVIDER_KIND_DASHSCOPE_TENANT ModelProviderKind = 2
	ModelProviderKind_MODEL_PROVIDER_KIND_OPENAI_TENANT    ModelProviderKind = 3
	ModelProviderKind_MODEL_PROVIDER_KIND_VOLC_TENANT      ModelProviderKind = 4
)

// Enum value maps for ModelProviderKind.
var (
	ModelProviderKind_name = map[int32]string{
		0: "MODEL_PROVIDER_KIND_UNSPECIFIED",
		1: "MODEL_PROVIDER_KIND_GEMINI_TENANT",
		2: "MODEL_PROVIDER_KIND_DASHSCOPE_TENANT",
		3: "MODEL_PROVIDER_KIND_OPENAI_TENANT",
		4: "MODEL_PROVIDER_KIND_VOLC_TENANT",
	}
	ModelProviderKind_value = map[string]int32{
		"MODEL_PROVIDER_KIND_UNSPECIFIED":      0,
		"MODEL_PROVIDER_KIND_GEMINI_TENANT":    1,
		"MODEL_PROVIDER_KIND_DASHSCOPE_TENANT": 2,
		"MODEL_PROVIDER_KIND_OPENAI_TENANT":    3,
		"MODEL_PROVIDER_KIND_VOLC_TENANT":      4,
	}
)

func (x ModelProviderKind) Enum() *ModelProviderKind {
	p := new(ModelProviderKind)
	*p = x
	return p
}

func (x ModelProviderKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelProviderKind) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[18].Descriptor()
}

func (ModelProviderKind) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[18]
}

func (x ModelProviderKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelProviderKind.Descriptor instead.
func (ModelProviderKind) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{18}
}

type ModelSource int32

const (
	ModelSource_MODEL_SOURCE_UNSPECIFIED ModelSource = 0
	ModelSource_MODEL_SOURCE_SYNC        ModelSource = 1
	ModelSource_MODEL_SOURCE_MANUAL      ModelSource = 2
)

// Enum value maps for ModelSource.
var (
	ModelSource_name = map[int32]string{
		0: "MODEL_SOURCE_UNSPECIFIED",
		1: "MODEL_SOURCE_SYNC",
		2: "MODEL_SOURCE_MANUAL",
	}
	ModelSource_value = map[string]int32{
		"MODEL_SOURCE_UNSPECIFIED": 0,
		"MODEL_SOURCE_SYNC":        1,
		"MODEL_SOURCE_MANUAL":      2,
	}
)

func (x ModelSource) Enum() *ModelSource {
	p := new(ModelSource)
	*p = x
	return p
}

func (x ModelSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelSource) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[19].Descriptor()
}

func (ModelSource) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[19]
}

func (x ModelSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelSource.Descriptor instead.
func (ModelSource) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{19}
}

type PeerRunHistoryEntryType int32

const (
	PeerRunHistoryEntryType_PEER_RUN_HISTORY_ENTRY_TYPE_UNSPECIFIED PeerRunHistoryEntryType = 0
	PeerRunHistoryEntryType_PEER_RUN_HISTORY_ENTRY_TYPE_GEAR        PeerRunHistoryEntryType = 1
	PeerRunHistoryEntryType_PEER_RUN_HISTORY_ENTRY_TYPE_AGENT       PeerRunHistoryEntryType = 2
)

// Enum value maps for PeerRunHistoryEntryType.
var (
	PeerRunHistoryEntryType_name = map[int32]string{
		0: "PEER_RUN_HISTORY_ENTRY_TYPE_UNSPECIFIED",
		1: "PEER_RUN_HISTORY_ENTRY_TYPE_GEAR",
		2: "PEER_RUN_HISTORY_ENTRY_TYPE_AGENT",
	}
	PeerRunHistoryEntryType_value = map[string]int32{
		"PEER_RUN_HISTORY_ENTRY_TYPE_UNSPECIFIED": 0,
		"PEER_RUN_HISTORY_ENTRY_TYPE_GEAR":        1,
		"PEER_RUN_HISTORY_ENTRY_TYPE_AGENT":       2,
	}
)

func (x PeerRunHistoryEntryType) Enum() *PeerRunHistoryEntryType {
	p := new(PeerRunHistoryEntryType)
	*p = x
	return p
}

func (x PeerRunHistoryEntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerRunHistoryEntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[20].Descriptor()
}

func (PeerRunHistoryEntryType) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[20]
}

func (x PeerRunHistoryEntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerRunHistoryEntryType.Descriptor instead.
func (PeerRunHistoryEntryType) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{20}
}

type PeerRunHistoryListRequestOrder int32

const (
	PeerRunHistoryListRequestOrder_PEER_RUN_HISTORY_LIST_REQUEST_ORDER_UNSPECIFIED PeerRunHistoryListRequestOrder = 0
	PeerRunHistoryListRequestOrder_PEER_RUN_HISTORY_LIST_REQUEST_ORDER_ASC         PeerRunHistoryListRequestOrder = 1
	PeerRunHistoryListRequestOrder_PEER_RUN_HISTORY_LIST_REQUEST_ORDER_DESC        PeerRunHistoryListRequestOrder = 2
)

// Enum value maps for PeerRunHistoryListRequestOrder.
var (
	PeerRunHistoryListRequestOrder_name = map[int32]string{
		0: "PEER_RUN_HISTORY_LIST_REQUEST_ORDER_UNSPECIFIED",
		1: "PEER_RUN_HISTORY_LIST_REQUEST_ORDER_ASC",
		2: "PEER_RUN_HISTORY_LIST_REQUEST_ORDER_DESC",
	}
	PeerRunHistoryListRequestOrder_value = map[string]int32{
		"PEER_RUN_HISTORY_LIST_REQUEST_ORDER_UNSPECIFIED": 0,
		"PEER_RUN_HISTORY_LIST_REQUEST_ORDER_ASC":         1,
		"PEER_RUN_HISTORY_LIST_REQUEST_ORDER_DESC":        2,
	}
)

func (x PeerRunHistoryListRequestOrder) Enum() *PeerRunHistoryListRequestOrder {
	p := new(PeerRunHistoryListRequestOrder)
	*p = x
	return p
}

func (x PeerRunHistoryListRequestOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerRunHistoryListRequestOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[21].Descriptor()
}

func (PeerRunHistoryListRequestOrder) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[21]
}

func (x PeerRunHistoryListRequestOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerRunHistoryListRequestOrder.Descriptor instead.
func (PeerRunHistoryListRequestOrder) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{21}
}

type PeerRunStatusState int32

const (
	PeerRunStatusState_PEER_RUN_STATUS_STATE_UNSPECIFIED PeerRunStatusState = 0
	PeerRunStatusState_PEER_RUN_STATUS_STATE_STOPPED     PeerRunStatusState = 1
	PeerRunStatusState_PEER_RUN_STATUS_STATE_STARTING    PeerRunStatusState = 2
	PeerRunStatusState_PEER_RUN_STATUS_STATE_RUNNING     PeerRunStatusState = 3
	PeerRunStatusState_PEER_RUN_STATUS_STATE_STOPPING    PeerRunStatusState = 4
	PeerRunStatusState_PEER_RUN_STATUS_STATE_ERROR       PeerRunStatusState = 5
)

// Enum value maps for PeerRunStatusState.
var (
	PeerRunStatusState_name = map[int32]string{
		0: "PEER_RUN_STATUS_STATE_UNSPECIFIED",
		1: "PEER_RUN_STATUS_STATE_STOPPED",
		2: "PEER_RUN_STATUS_STATE_STARTING",
		3: "PEER_RUN_STATUS_STATE_RUNNING",
		4: "PEER_RUN_STATUS_STATE_STOPPING",
		5: "PEER_RUN_STATUS_STATE_ERROR",
	}
	PeerRunStatusState_value = map[string]int32{
		"PEER_RUN_STATUS_STATE_UNSPECIFIED": 0,
		"PEER_RUN_STATUS_STATE_STOPPED":     1,
		"PEER_RUN_STATUS_STATE_STARTING":    2,
		"PEER_RUN_STATUS_STATE_RUNNING":     3,
		"PEER_RUN_STATUS_STATE_STOPPING":    4,
		"PEER_RUN_STATUS_STATE_ERROR":       5,
	}
)

func (x PeerRunStatusState) Enum() *PeerRunStatusState {
	p := new(PeerRunStatusState)
	*p = x
	return p
}

func (x PeerRunStatusState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerRunStatusState) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[22].Descriptor()
}

func (PeerRunStatusState) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[22]
}

func (x PeerRunStatusState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerRunStatusState.Descriptor instead.
func (PeerRunStatusState) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{22}
}

type VoiceProviderKind int32

const (
	VoiceProviderKind_VOICE_PROVIDER_KIND_UNSPECIFIED      VoiceProviderKind = 0
	VoiceProviderKind_VOICE_PROVIDER_KIND_GEMINI_TENANT    VoiceProviderKind = 1
	VoiceProviderKind_VOICE_PROVIDER_KIND_DASHSCOPE_TENANT VoiceProviderKind = 2
	VoiceProviderKind_VOICE_PROVIDER_KIND_OPENAI_TENANT    VoiceProviderKind = 3
	VoiceProviderKind_VOICE_PROVIDER_KIND_MINIMAX_TENANT   VoiceProviderKind = 4
	VoiceProviderKind_VOICE_PROVIDER_KIND_VOLC_TENANT      VoiceProviderKind = 5
)

// Enum value maps for VoiceProviderKind.
var (
	VoiceProviderKind_name = map[int32]string{
		0: "VOICE_PROVIDER_KIND_UNSPECIFIED",
		1: "VOICE_PROVIDER_KIND_GEMINI_TENANT",
		2: "VOICE_PROVIDER_KIND_DASHSCOPE_TENANT",
		3: "VOICE_PROVIDER_KIND_OPENAI_TENANT",
		4: "VOICE_PROVIDER_KIND_MINIMAX_TENANT",
		5: "VOICE_PROVIDER_KIND_VOLC_TENANT",
	}
	VoiceProviderKind_value = map[string]int32{
		"VOICE_PROVIDER_KIND_UNSPECIFIED":      0,
		"VOICE_PROVIDER_KIND_GEMINI_TENANT":    1,
		"VOICE_PROVIDER_KIND_DASHSCOPE_TENANT": 2,
		"VOICE_PROVIDER_KIND_OPENAI_TENANT":    3,
		"VOICE_PROVIDER_KIND_MINIMAX_TENANT":   4,
		"VOICE_PROVIDER_KIND_VOLC_TENANT":      5,
	}
)

func (x VoiceProviderKind) Enum() *VoiceProviderKind {
	p := new(VoiceProviderKind)
	*p = x
	return p
}

func (x VoiceProviderKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceProviderKind) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[23].Descriptor()
}

func (VoiceProviderKind) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[23]
}

func (x VoiceProviderKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoiceProviderKind.Descriptor instead.
func (VoiceProviderKind) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{23}
}

type VoiceSource int32

const (
	VoiceSource_VOICE_SOURCE_UNSPECIFIED VoiceSource = 0
	VoiceSource_VOICE_SOURCE_SYNC        VoiceSource = 1
	VoiceSource_VOICE_SOURCE_MANUAL      VoiceSource = 2
)

// Enum value maps for VoiceSource.
var (
	VoiceSource_name = map[int32]string{
		0: "VOICE_SOURCE_UNSPECIFIED",
		1: "VOICE_SOURCE_SYNC",
		2: "VOICE_SOURCE_MANUAL",
	}
	VoiceSource_value = map[string]int32{
		"VOICE_SOURCE_UNSPECIFIED": 0,
		"VOICE_SOURCE_SYNC":        1,
		"VOICE_SOURCE_MANUAL":      2,
	}
)

func (x VoiceSource) Enum() *VoiceSource {
	p := new(VoiceSource)
	*p = x
	return p
}

func (x VoiceSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoiceSource) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[24].Descriptor()
}

func (VoiceSource) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[24]
}

func (x VoiceSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoiceSource.Descriptor instead.
func (VoiceSource) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{24}
}

type VolcTenantModelProviderDataApiMode int32

const (
	VolcTenantModelProviderDataApiMode_VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_UNSPECIFIED VolcTenantModelProviderDataApiMode = 0
	VolcTenantModelProviderDataApiMode_VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_ASR         VolcTenantModelProviderDataApiMode = 1
	VolcTenantModelProviderDataApiMode_VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_TTS         VolcTenantModelProviderDataApiMode = 2
	VolcTenantModelProviderDataApiMode_VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_REALTIME    VolcTenantModelProviderDataApiMode = 3
)

// Enum value maps for VolcTenantModelProviderDataApiMode.
var (
	VolcTenantModelProviderDataApiMode_name = map[int32]string{
		0: "VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_UNSPECIFIED",
		1: "VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_ASR",
		2: "VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_TTS",
		3: "VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_REALTIME",
	}
	VolcTenantModelProviderDataApiMode_value = map[string]int32{
		"VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_UNSPECIFIED": 0,
		"VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_ASR":         1,
		"VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_TTS":         2,
		"VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_REALTIME":    3,
	}
)

func (x VolcTenantModelProviderDataApiMode) Enum() *VolcTenantModelProviderDataApiMode {
	p := new(VolcTenantModelProviderDataApiMode)
	*p = x
	return p
}

func (x VolcTenantModelProviderDataApiMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VolcTenantModelProviderDataApiMode) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[25].Descriptor()
}

func (VolcTenantModelProviderDataApiMode) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[25]
}

func (x VolcTenantModelProviderDataApiMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VolcTenantModelProviderDataApiMode.Descriptor instead.
func (VolcTenantModelProviderDataApiMode) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{25}
}

type WorkflowDriver int32

const (
	WorkflowDriver_WORKFLOW_DRIVER_UNSPECIFIED     WorkflowDriver = 0
	WorkflowDriver_WORKFLOW_DRIVER_FLOWCRAFT       WorkflowDriver = 1
	WorkflowDriver_WORKFLOW_DRIVER_DOUBAO_REALTIME WorkflowDriver = 2
	WorkflowDriver_WORKFLOW_DRIVER_AST_TRANSLATE   WorkflowDriver = 3
	WorkflowDriver_WORKFLOW_DRIVER_CHATROOM        WorkflowDriver = 4
)

// Enum value maps for WorkflowDriver.
var (
	WorkflowDriver_name = map[int32]string{
		0: "WORKFLOW_DRIVER_UNSPECIFIED",
		1: "WORKFLOW_DRIVER_FLOWCRAFT",
		2: "WORKFLOW_DRIVER_DOUBAO_REALTIME",
		3: "WORKFLOW_DRIVER_AST_TRANSLATE",
		4: "WORKFLOW_DRIVER_CHATROOM",
	}
	WorkflowDriver_value = map[string]int32{
		"WORKFLOW_DRIVER_UNSPECIFIED":     0,
		"WORKFLOW_DRIVER_FLOWCRAFT":       1,
		"WORKFLOW_DRIVER_DOUBAO_REALTIME": 2,
		"WORKFLOW_DRIVER_AST_TRANSLATE":   3,
		"WORKFLOW_DRIVER_CHATROOM":        4,
	}
)

func (x WorkflowDriver) Enum() *WorkflowDriver {
	p := new(WorkflowDriver)
	*p = x
	return p
}

func (x WorkflowDriver) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowDriver) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[26].Descriptor()
}

func (WorkflowDriver) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[26]
}

func (x WorkflowDriver) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowDriver.Descriptor instead.
func (WorkflowDriver) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{26}
}

type WorkspaceHistoryListRequestOrder int32

const (
	WorkspaceHistoryListRequestOrder_WORKSPACE_HISTORY_LIST_REQUEST_ORDER_UNSPECIFIED WorkspaceHistoryListRequestOrder = 0
	WorkspaceHistoryListRequestOrder_WORKSPACE_HISTORY_LIST_REQUEST_ORDER_ASC         WorkspaceHistoryListRequestOrder = 1
	WorkspaceHistoryListRequestOrder_WORKSPACE_HISTORY_LIST_REQUEST_ORDER_DESC        WorkspaceHistoryListRequestOrder = 2
)

// Enum value maps for WorkspaceHistoryListRequestOrder.
var (
	WorkspaceHistoryListRequestOrder_name = map[int32]string{
		0: "WORKSPACE_HISTORY_LIST_REQUEST_ORDER_UNSPECIFIED",
		1: "WORKSPACE_HISTORY_LIST_REQUEST_ORDER_ASC",
		2: "WORKSPACE_HISTORY_LIST_REQUEST_ORDER_DESC",
	}
	WorkspaceHistoryListRequestOrder_value = map[string]int32{
		"WORKSPACE_HISTORY_LIST_REQUEST_ORDER_UNSPECIFIED": 0,
		"WORKSPACE_HISTORY_LIST_REQUEST_ORDER_ASC":         1,
		"WORKSPACE_HISTORY_LIST_REQUEST_ORDER_DESC":        2,
	}
)

func (x WorkspaceHistoryListRequestOrder) Enum() *WorkspaceHistoryListRequestOrder {
	p := new(WorkspaceHistoryListRequestOrder)
	*p = x
	return p
}

func (x WorkspaceHistoryListRequestOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkspaceHistoryListRequestOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[27].Descriptor()
}

func (WorkspaceHistoryListRequestOrder) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[27]
}

func (x WorkspaceHistoryListRequestOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkspaceHistoryListRequestOrder.Descriptor instead.
func (WorkspaceHistoryListRequestOrder) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{27}
}

type WorkspaceInputMode int32

const (
	WorkspaceInputMode_WORKSPACE_INPUT_MODE_UNSPECIFIED  WorkspaceInputMode = 0
	WorkspaceInputMode_WORKSPACE_INPUT_MODE_PUSH_TO_TALK WorkspaceInputMode = 1
	WorkspaceInputMode_WORKSPACE_INPUT_MODE_REALTIME     WorkspaceInputMode = 2
)

// Enum value maps for WorkspaceInputMode.
var (
	WorkspaceInputMode_name = map[int32]string{
		0: "WORKSPACE_INPUT_MODE_UNSPECIFIED",
		1: "WORKSPACE_INPUT_MODE_PUSH_TO_TALK",
		2: "WORKSPACE_INPUT_MODE_REALTIME",
	}
	WorkspaceInputMode_value = map[string]int32{
		"WORKSPACE_INPUT_MODE_UNSPECIFIED":  0,
		"WORKSPACE_INPUT_MODE_PUSH_TO_TALK": 1,
		"WORKSPACE_INPUT_MODE_REALTIME":     2,
	}
)

func (x WorkspaceInputMode) Enum() *WorkspaceInputMode {
	p := new(WorkspaceInputMode)
	*p = x
	return p
}

func (x WorkspaceInputMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkspaceInputMode) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[28].Descriptor()
}

func (WorkspaceInputMode) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[28]
}

func (x WorkspaceInputMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkspaceInputMode.Descriptor instead.
func (WorkspaceInputMode) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{28}
}

type ToolSource int32

const (
	ToolSource_TOOL_SOURCE_UNSPECIFIED ToolSource = 0
	ToolSource_TOOL_SOURCE_BUILTIN     ToolSource = 1
	ToolSource_TOOL_SOURCE_DEVICE      ToolSource = 2
	ToolSource_TOOL_SOURCE_ADMIN       ToolSource = 3
)

// Enum value maps for ToolSource.
var (
	ToolSource_name = map[int32]string{
		0: "TOOL_SOURCE_UNSPECIFIED",
		1: "TOOL_SOURCE_BUILTIN",
		2: "TOOL_SOURCE_DEVICE",
		3: "TOOL_SOURCE_ADMIN",
	}
	ToolSource_value = map[string]int32{
		"TOOL_SOURCE_UNSPECIFIED": 0,
		"TOOL_SOURCE_BUILTIN":     1,
		"TOOL_SOURCE_DEVICE":      2,
		"TOOL_SOURCE_ADMIN":       3,
	}
)

func (x ToolSource) Enum() *ToolSource {
	p := new(ToolSource)
	*p = x
	return p
}

func (x ToolSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolSource) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[29].Descriptor()
}

func (ToolSource) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[29]
}

func (x ToolSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolSource.Descriptor instead.
func (ToolSource) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{29}
}

type ToolExecutorKind int32

const (
	ToolExecutorKind_TOOL_EXECUTOR_KIND_UNSPECIFIED ToolExecutorKind = 0
	ToolExecutorKind_TOOL_EXECUTOR_KIND_BUILTIN     ToolExecutorKind = 1
	ToolExecutorKind_TOOL_EXECUTOR_KIND_DEVICE_RPC  ToolExecutorKind = 2
)

// Enum value maps for ToolExecutorKind.
var (
	ToolExecutorKind_name = map[int32]string{
		0: "TOOL_EXECUTOR_KIND_UNSPECIFIED",
		1: "TOOL_EXECUTOR_KIND_BUILTIN",
		2: "TOOL_EXECUTOR_KIND_DEVICE_RPC",
	}
	ToolExecutorKind_value = map[string]int32{
		"TOOL_EXECUTOR_KIND_UNSPECIFIED": 0,
		"TOOL_EXECUTOR_KIND_BUILTIN":     1,
		"TOOL_EXECUTOR_KIND_DEVICE_RPC":  2,
	}
)

func (x ToolExecutorKind) Enum() *ToolExecutorKind {
	p := new(ToolExecutorKind)
	*p = x
	return p
}

func (x ToolExecutorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolExecutorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_enums_proto_enumTypes[30].Descriptor()
}

func (ToolExecutorKind) Type() protoreflect.EnumType {
	return &file_payload_enums_proto_enumTypes[30]
}

func (x ToolExecutorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolExecutorKind.Descriptor instead.
func (ToolExecutorKind) EnumDescriptor() ([]byte, []int) {
	return file_payload_enums_proto_rawDescGZIP(), []int{30}
}

var File_payload_enums_proto protoreflect.FileDescriptor

const file_payload_enums_proto_rawDesc = "" +
	"\n" +
	"\x13payload/enums.proto\x12\x0egizclaw.rpc.v1*k\n" +
	"\x10ASTTranslateMode\x12!\n" +
	"\x1dASTTRANSLATE_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ASTTRANSLATE_MODE_S2T\x10\x01\x12\x19\n" +
	"\x15ASTTRANSLATE_MODE_S2S\x10\x02*\xa8\x01\n" +
	"(ASTTranslateWorkspaceParametersAgentType\x12<\n" +
	"8ASTTRANSLATE_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED\x10\x00\x12>\n" +
	":ASTTRANSLATE_WORKSPACE_PARAMETERS_AGENT_TYPE_AST_TRANSLATE\x10\x01*c\n" +
	"\fChatRoomMode\x12\x1e\n" +
	"\x1aCHAT_ROOM_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CHAT_ROOM_MODE_DIRECT\x10\x01\x12\x18\n" +
	"\x14CHAT_ROOM_MODE_GROUP\x10\x02*\x99\x01\n" +
	"$ChatRoomWorkspaceParametersAgentType\x129\n" +
	"5CHAT_ROOM_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED\x10\x00\x126\n" +
	"2CHAT_ROOM_WORKSPACE_PARAMETERS_AGENT_TYPE_CHATROOM\x10\x01*\xeb\x01\n" +
	"'DashScopeTenantModelProviderDataApiMode\x12>\n" +
	":DASH_SCOPE_TENANT_MODEL_PROVIDER_DATA_API_MODE_UNSPECIFIED\x10\x00\x12C\n" +
	"?DASH_SCOPE_TENANT_MODEL_PROVIDER_DATA_API_MODE_CHAT_COMPLETIONS\x10\x01\x12;\n" +
	"7DASH_SCOPE_TENANT_MODEL_PROVIDER_DATA_API_MODE_REALTIME\x10\x02*\x91\x02\n" +
	"\x1dDoubaoRealtimeAudioFormatType\x121\n" +
	"-DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_UNSPECIFIED\x10\x00\x12)\n" +
	"%DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_PCM\x10\x01\x12/\n" +
	"+DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_PCM_S16LE\x10\x02\x121\n" +
	"-DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_SPEECH_OPUS\x10\x03\x12.\n" +
	"*DOUBAO_REALTIME_AUDIO_FORMAT_TYPE_OGG_OPUS\x10\x04*\xaa\x02\n" +
	"*DoubaoRealtimeDialogExtraVolcWebsearchType\x12@\n" +
	"<DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_UNSPECIFIED\x10\x00\x128\n" +
	"4DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_WEB\x10\x01\x12@\n" +
	"<DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_WEB_SUMMARY\x10\x02\x12>\n" +
	":DOUBAO_REALTIME_DIALOG_EXTRA_VOLC_WEBSEARCH_TYPE_WEB_AGENT\x10\x03*\x85\x01\n" +
	"\x1eDoubaoRealtimeFunctionToolType\x122\n" +
	".DOUBAO_REALTIME_FUNCTION_TOOL_TYPE_UNSPECIFIED\x10\x00\x12/\n" +
	"+DOUBAO_REALTIME_FUNCTION_TOOL_TYPE_FUNCTION\x10\x01*\xb2\x01\n" +
	"*DoubaoRealtimeWorkspaceParametersAgentType\x12?\n" +
	";DOUBAO_REALTIME_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED\x10\x00\x12C\n" +
	"?DOUBAO_REALTIME_WORKSPACE_PARAMETERS_AGENT_TYPE_DOUBAO_REALTIME\x10\x01*\x96\x01\n" +
	"\x19FirmwareArtifactEntryType\x12,\n" +
	"(FIRMWARE_ARTIFACT_ENTRY_TYPE_UNSPECIFIED\x10\x00\x12%\n" +
	"!FIRMWARE_ARTIFACT_ENTRY_TYPE_FILE\x10\x01\x12$\n" +
	" FIRMWARE_ARTIFACT_ENTRY_TYPE_DIR\x10\x02*\xc4\x01\n" +
	"\x13FirmwareChannelName\x12%\n" +
	"!FIRMWARE_CHANNEL_NAME_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cFIRMWARE_CHANNEL_NAME_STABLE\x10\x01\x12\x1e\n" +
	"\x1aFIRMWARE_CHANNEL_NAME_BETA\x10\x02\x12!\n" +
	"\x1dFIRMWARE_CHANNEL_NAME_DEVELOP\x10\x03\x12!\n" +
	"\x1dFIRMWARE_CHANNEL_NAME_PENDING\x10\x04*\x99\x02\n" +
	"4FlowcraftConversationParametersAgentInitiativePolicy\x12I\n" +
	"EFLOWCRAFT_CONVERSATION_PARAMETERS_AGENT_INITIATIVE_POLICY_UNSPECIFIED\x10\x00\x12M\n" +
	"IFLOWCRAFT_CONVERSATION_PARAMETERS_AGENT_INITIATIVE_POLICY_ONCE_WHEN_EMPTY\x10\x01\x12G\n" +
	"CFLOWCRAFT_CONVERSATION_PARAMETERS_AGENT_INITIATIVE_POLICY_ON_RELOAD\x10\x02*\xd8\x01\n" +
	")FlowcraftConversationParametersInitiative\x12<\n" +
	"8FLOWCRAFT_CONVERSATION_PARAMETERS_INITIATIVE_UNSPECIFIED\x10\x00\x125\n" +
	"1FLOWCRAFT_CONVERSATION_PARAMETERS_INITIATIVE_PEER\x10\x01\x126\n" +
	"2FLOWCRAFT_CONVERSATION_PARAMETERS_INITIATIVE_AGENT\x10\x02*\x9b\x01\n" +
	"%FlowcraftWorkspaceParametersAgentType\x129\n" +
	"5FLOWCRAFT_WORKSPACE_PARAMETERS_AGENT_TYPE_UNSPECIFIED\x10\x00\x127\n" +
	"3FLOWCRAFT_WORKSPACE_PARAMETERS_AGENT_TYPE_FLOWCRAFT\x10\x01*\xa9\x01\n" +
	"\x1cFriendGroupMemberMutableRole\x120\n" +
	",FRIEND_GROUP_MEMBER_MUTABLE_ROLE_UNSPECIFIED\x10\x00\x12*\n" +
	"&FRIEND_GROUP_MEMBER_MUTABLE_ROLE_ADMIN\x10\x01\x12+\n" +
	"'FRIEND_GROUP_MEMBER_MUTABLE_ROLE_MEMBER\x10\x02*\xae\x01\n" +
	"\x15FriendGroupMemberRole\x12(\n" +
	"$FRIEND_GROUP_MEMBER_ROLE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eFRIEND_GROUP_MEMBER_ROLE_OWNER\x10\x01\x12\"\n" +
	"\x1eFRIEND_GROUP_MEMBER_ROLE_ADMIN\x10\x02\x12#\n" +
	"\x1fFRIEND_GROUP_MEMBER_ROLE_MEMBER\x10\x03*\x7f\n" +
	"\bPeerRole\x12\x19\n" +
	"\x15PEER_ROLE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPEER_ROLE_ADMIN\x10\x01\x12\x14\n" +
	"\x10PEER_ROLE_SERVER\x10\x02\x12\x17\n" +
	"\x13PEER_ROLE_EDGE_NODE\x10\x03\x12\x14\n" +
	"\x10PEER_ROLE_CLIENT\x10\x04*\xb2\x01\n" +
	"\tModelKind\x12\x1a\n" +
	"\x16MODEL_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eMODEL_KIND_LLM\x10\x01\x12\x12\n" +
	"\x0eMODEL_KIND_TTS\x10\x02\x12\x12\n" +
	"\x0eMODEL_KIND_ASR\x10\x03\x12\x17\n" +
	"\x13MODEL_KIND_REALTIME\x10\x04\x12\x1a\n" +
	"\x16MODEL_KIND_TRANSLATION\x10\x05\x12\x18\n" +
	"\x14MODEL_KIND_EMBEDDING\x10\x06*\xd5\x01\n" +
	"\x11ModelProviderKind\x12#\n" +
	"\x1fMODEL_PROVIDER_KIND_UNSPECIFIED\x10\x00\x12%\n" +
	"!MODEL_PROVIDER_KIND_GEMINI_TENANT\x10\x01\x12(\n" +
	"$MODEL_PROVIDER_KIND_DASHSCOPE_TENANT\x10\x02\x12%\n" +
	"!MODEL_PROVIDER_KIND_OPENAI_TENANT\x10\x03\x12#\n" +
	"\x1fMODEL_PROVIDER_KIND_VOLC_TENANT\x10\x04*[\n" +
	"\vModelSource\x12\x1c\n" +
	"\x18MODEL_SOURCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MODEL_SOURCE_SYNC\x10\x01\x12\x17\n" +
	"\x13MODEL_SOURCE_MANUAL\x10\x02*\x93\x01\n" +
	"\x17PeerRunHistoryEntryType\x12+\n" +
	"'PEER_RUN_HISTORY_ENTRY_TYPE_UNSPECIFIED\x10\x00\x12$\n" +
	" PEER_RUN_HISTORY_ENTRY_TYPE_GEAR\x10\x01\x12%\n" +
	"!PEER_RUN_HISTORY_ENTRY_TYPE_AGENT\x10\x02*\xb0\x01\n" +
	"\x1ePeerRunHistoryListRequestOrder\x123\n" +
	"/PEER_RUN_HISTORY_LIST_REQUEST_ORDER_UNSPECIFIED\x10\x00\x12+\n" +
	"'PEER_RUN_HISTORY_LIST_REQUEST_ORDER_ASC\x10\x01\x12,\n" +
	"(PEER_RUN_HISTORY_LIST_REQUEST_ORDER_DESC\x10\x02*\xea\x01\n" +
	"\x12PeerRunStatusState\x12%\n" +
	"!PEER_RUN_STATUS_STATE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dPEER_RUN_STATUS_STATE_STOPPED\x10\x01\x12\"\n" +
	"\x1ePEER_RUN_STATUS_STATE_STARTING\x10\x02\x12!\n" +
	"\x1dPEER_RUN_STATUS_STATE_RUNNING\x10\x03\x12\"\n" +
	"\x1ePEER_RUN_STATUS_STATE_STOPPING\x10\x04\x12\x1f\n" +
	"\x1bPEER_RUN_STATUS_STATE_ERROR\x10\x05*\xfd\x01\n" +
	"\x11VoiceProviderKind\x12#\n" +
	"\x1fVOICE_PROVIDER_KIND_UNSPECIFIED\x10\x00\x12%\n" +
	"!VOICE_PROVIDER_KIND_GEMINI_TENANT\x10\x01\x12(\n" +
	"$VOICE_PROVIDER_KIND_DASHSCOPE_TENANT\x10\x02\x12%\n" +
	"!VOICE_PROVIDER_KIND_OPENAI_TENANT\x10\x03\x12&\n" +
	"\"VOICE_PROVIDER_KIND_MINIMAX_TENANT\x10\x04\x12#\n" +
	"\x1fVOICE_PROVIDER_KIND_VOLC_TENANT\x10\x05*[\n" +
	"\vVoiceSource\x12\x1c\n" +
	"\x18VOICE_SOURCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VOICE_SOURCE_SYNC\x10\x01\x12\x17\n" +
	"\x13VOICE_SOURCE_MANUAL\x10\x02*\xf9\x01\n" +
	"\"VolcTenantModelProviderDataApiMode\x128\n" +
	"4VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_UNSPECIFIED\x10\x00\x120\n" +
	",VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_ASR\x10\x01\x120\n" +
	",VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_TTS\x10\x02\x125\n" +
	"1VOLC_TENANT_MODEL_PROVIDER_DATA_API_MODE_REALTIME\x10\x03*\xb6\x01\n" +
	"\x0eWorkflowDriver\x12\x1f\n" +
	"\x1bWORKFLOW_DRIVER_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19WORKFLOW_DRIVER_FLOWCRAFT\x10\x01\x12#\n" +
	"\x1fWORKFLOW_DRIVER_DOUBAO_REALTIME\x10\x02\x12!\n" +
	"\x1dWORKFLOW_DRIVER_AST_TRANSLATE\x10\x03\x12\x1c\n" +
	"\x18WORKFLOW_DRIVER_CHATROOM\x10\x04*\xb5\x01\n" +
	" WorkspaceHistoryListRequestOrder\x124\n" +
	"0WORKSPACE_HISTORY_LIST_REQUEST_ORDER_UNSPECIFIED\x10\x00\x12,\n" +
	"(WORKSPACE_HISTORY_LIST_REQUEST_ORDER_ASC\x10\x01\x12-\n" +
	")WORKSPACE_HISTORY_LIST_REQUEST_ORDER_DESC\x10\x02*\x84\x01\n" +
	"\x12WorkspaceInputMode\x12$\n" +
	" WORKSPACE_INPUT_MODE_UNSPECIFIED\x10\x00\x12%\n" +
	"!WORKSPACE_INPUT_MODE_PUSH_TO_TALK\x10\x01\x12!\n" +
	"\x1dWORKSPACE_INPUT_MODE_REALTIME\x10\x02*q\n" +
	"\n" +
	"ToolSource\x12\x1b\n" +
	"\x17TOOL_SOURCE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TOOL_SOURCE_BUILTIN\x10\x01\x12\x16\n" +
	"\x12TOOL_SOURCE_DEVICE\x10\x02\x12\x15\n" +
	"\x11TOOL_SOURCE_ADMIN\x10\x03*y\n" +
	"\x10ToolExecutorKind\x12\"\n" +
	"\x1eTOOL_EXECUTOR_KIND_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTOOL_EXECUTOR_KIND_BUILTIN\x10\x01\x12!\n" +
	"\x1dTOOL_EXECUTOR_KIND_DEVICE_RPC\x10\x02B?Z=github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/rpcproto;rpcpbb\x06proto3"

var (
	file_payload_enums_proto_rawDescOnce sync.Once
	file_payload_enums_proto_rawDescData []byte
)

func file_payload_enums_proto_rawDescGZIP() []byte {
	file_payload_enums_proto_rawDescOnce.Do(func() {
		file_payload_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_enums_proto_rawDesc), len(file_payload_enums_proto_rawDesc)))
	})
	return file_payload_enums_proto_rawDescData
}

var file_payload_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 31)
var file_payload_enums_proto_goTypes = []any{
	(ASTTranslateMode)(0),                                     // 0: gizclaw.rpc.v1.ASTTranslateMode
	(ASTTranslateWorkspaceParametersAgentType)(0),             // 1: gizclaw.rpc.v1.ASTTranslateWorkspaceParametersAgentType
	(ChatRoomMode)(0),                                         // 2: gizclaw.rpc.v1.ChatRoomMode
	(ChatRoomWorkspaceParametersAgentType)(0),                 // 3: gizclaw.rpc.v1.ChatRoomWorkspaceParametersAgentType
	(DashScopeTenantModelProviderDataApiMode)(0),              // 4: gizclaw.rpc.v1.DashScopeTenantModelProviderDataApiMode
	(DoubaoRealtimeAudioFormatType)(0),                        // 5: gizclaw.rpc.v1.DoubaoRealtimeAudioFormatType
	(DoubaoRealtimeDialogExtraVolcWebsearchType)(0),           // 6: gizclaw.rpc.v1.DoubaoRealtimeDialogExtraVolcWebsearchType
	(DoubaoRealtimeFunctionToolType)(0),                       // 7: gizclaw.rpc.v1.DoubaoRealtimeFunctionToolType
	(DoubaoRealtimeWorkspaceParametersAgentType)(0),           // 8: gizclaw.rpc.v1.DoubaoRealtimeWorkspaceParametersAgentType
	(FirmwareArtifactEntryType)(0),                            // 9: gizclaw.rpc.v1.FirmwareArtifactEntryType
	(FirmwareChannelName)(0),                                  // 10: gizclaw.rpc.v1.FirmwareChannelName
	(FlowcraftConversationParametersAgentInitiativePolicy)(0), // 11: gizclaw.rpc.v1.FlowcraftConversationParametersAgentInitiativePolicy
	(FlowcraftConversationParametersInitiative)(0),            // 12: gizclaw.rpc.v1.FlowcraftConversationParametersInitiative
	(FlowcraftWorkspaceParametersAgentType)(0),                // 13: gizclaw.rpc.v1.FlowcraftWorkspaceParametersAgentType
	(FriendGroupMemberMutableRole)(0),                         // 14: gizclaw.rpc.v1.FriendGroupMemberMutableRole
	(FriendGroupMemberRole)(0),                                // 15: gizclaw.rpc.v1.FriendGroupMemberRole
	(PeerRole)(0),                                             // 16: gizclaw.rpc.v1.PeerRole
	(ModelKind)(0),                                            // 17: gizclaw.rpc.v1.ModelKind
	(ModelProviderKind)(0),                                    // 18: gizclaw.rpc.v1.ModelProviderKind
	(ModelSource)(0),                                          // 19: gizclaw.rpc.v1.ModelSource
	(PeerRunHistoryEntryType)(0),                              // 20: gizclaw.rpc.v1.PeerRunHistoryEntryType
	(PeerRunHistoryListRequestOrder)(0),                       // 21: gizclaw.rpc.v1.PeerRunHistoryListRequestOrder
	(PeerRunStatusState)(0),                                   // 22: gizclaw.rpc.v1.PeerRunStatusState
	(VoiceProviderKind)(0),                                    // 23: gizclaw.rpc.v1.VoiceProviderKind
	(VoiceSource)(0),                                          // 24: gizclaw.rpc.v1.VoiceSource
	(VolcTenantModelProviderDataApiMode)(0),                   // 25: gizclaw.rpc.v1.VolcTenantModelProviderDataApiMode
	(WorkflowDriver)(0),                                       // 26: gizclaw.rpc.v1.WorkflowDriver
	(WorkspaceHistoryListRequestOrder)(0),                     // 27: gizclaw.rpc.v1.WorkspaceHistoryListRequestOrder
	(WorkspaceInputMode)(0),                                   // 28: gizclaw.rpc.v1.WorkspaceInputMode
	(ToolSource)(0),                                           // 29: gizclaw.rpc.v1.ToolSource
	(ToolExecutorKind)(0),                                     // 30: gizclaw.rpc.v1.ToolExecutorKind
}
var file_payload_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payload_enums_proto_init() }
func file_payload_enums_proto_init() {
	if File_payload_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_enums_proto_rawDesc), len(file_payload_enums_proto_rawDesc)),
			NumEnums:      31,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_enums_proto_goTypes,
		DependencyIndexes: file_payload_enums_proto_depIdxs,
		EnumInfos:         file_payload_enums_proto_enumTypes,
	}.Build()
	File_payload_enums_proto = out.File
	file_payload_enums_proto_goTypes = nil
	file_payload_enums_proto_depIdxs = nil
}
