// Peer RPC system payload protobuf schema.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payload/system.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientGetIdentifiersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGetIdentifiersRequest) Reset() {
	*x = ClientGetIdentifiersRequest{}
	mi := &file_payload_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetIdentifiersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetIdentifiersRequest) ProtoMessage() {}

func (x *ClientGetIdentifiersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetIdentifiersRequest.ProtoReflect.Descriptor instead.
func (*ClientGetIdentifiersRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{0}
}

type ClientGetIdentifiersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *RefreshIdentifiers    `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGetIdentifiersResponse) Reset() {
	*x = ClientGetIdentifiersResponse{}
	mi := &file_payload_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetIdentifiersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetIdentifiersResponse) ProtoMessage() {}

func (x *ClientGetIdentifiersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetIdentifiersResponse.ProtoReflect.Descriptor instead.
func (*ClientGetIdentifiersResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{1}
}

func (x *ClientGetIdentifiersResponse) GetValue() *RefreshIdentifiers {
	if x != nil {
		return x.Value
	}
	return nil
}

type ClientGetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGetInfoRequest) Reset() {
	*x = ClientGetInfoRequest{}
	mi := &file_payload_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetInfoRequest) ProtoMessage() {}

func (x *ClientGetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetInfoRequest.ProtoReflect.Descriptor instead.
func (*ClientGetInfoRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{2}
}

type ClientGetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *RefreshInfo           `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGetInfoResponse) Reset() {
	*x = ClientGetInfoResponse{}
	mi := &file_payload_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetInfoResponse) ProtoMessage() {}

func (x *ClientGetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetInfoResponse.ProtoReflect.Descriptor instead.
func (*ClientGetInfoResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{3}
}

func (x *ClientGetInfoResponse) GetValue() *RefreshInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hardware      *HardwareInfo          `protobuf:"bytes,1,opt,name=hardware,proto3,oneof" json:"hardware,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Sn            *string                `protobuf:"bytes,3,opt,name=sn,proto3,oneof" json:"sn,omitempty"`
	Icon          *Icon                  `protobuf:"bytes,4,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_payload_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceInfo) GetHardware() *HardwareInfo {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *DeviceInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *DeviceInfo) GetSn() string {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return ""
}

func (x *DeviceInfo) GetIcon() *Icon {
	if x != nil {
		return x.Icon
	}
	return nil
}

type HardwareInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HardwareRevision *string                `protobuf:"bytes,1,opt,name=hardware_revision,json=hardwareRevision,proto3,oneof" json:"hardware_revision,omitempty"`
	Imeis            []*PeerIMEI            `protobuf:"bytes,2,rep,name=imeis,proto3" json:"imeis,omitempty"`
	Labels           []*PeerLabel           `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	Manufacturer     *string                `protobuf:"bytes,4,opt,name=manufacturer,proto3,oneof" json:"manufacturer,omitempty"`
	Model            *string                `protobuf:"bytes,5,opt,name=model,proto3,oneof" json:"model,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HardwareInfo) Reset() {
	*x = HardwareInfo{}
	mi := &file_payload_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfo) ProtoMessage() {}

func (x *HardwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfo.ProtoReflect.Descriptor instead.
func (*HardwareInfo) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{5}
}

func (x *HardwareInfo) GetHardwareRevision() string {
	if x != nil && x.HardwareRevision != nil {
		return *x.HardwareRevision
	}
	return ""
}

func (x *HardwareInfo) GetImeis() []*PeerIMEI {
	if x != nil {
		return x.Imeis
	}
	return nil
}

func (x *HardwareInfo) GetLabels() []*PeerLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *HardwareInfo) GetManufacturer() string {
	if x != nil && x.Manufacturer != nil {
		return *x.Manufacturer
	}
	return ""
}

func (x *HardwareInfo) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

type PeerIMEI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Tac           string                 `protobuf:"bytes,3,opt,name=tac,proto3" json:"tac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerIMEI) Reset() {
	*x = PeerIMEI{}
	mi := &file_payload_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerIMEI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerIMEI) ProtoMessage() {}

func (x *PeerIMEI) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerIMEI.ProtoReflect.Descriptor instead.
func (*PeerIMEI) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{6}
}

func (x *PeerIMEI) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PeerIMEI) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *PeerIMEI) GetTac() string {
	if x != nil {
		return x.Tac
	}
	return ""
}

type PeerLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerLabel) Reset() {
	*x = PeerLabel{}
	mi := &file_payload_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerLabel) ProtoMessage() {}

func (x *PeerLabel) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerLabel.ProtoReflect.Descriptor instead.
func (*PeerLabel) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{7}
}

func (x *PeerLabel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PeerLabel) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PeerStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BatteryPercent *int64                 `protobuf:"varint,1,opt,name=battery_percent,json=batteryPercent,proto3,oneof" json:"battery_percent,omitempty"`
	Charging       *bool                  `protobuf:"varint,2,opt,name=charging,proto3,oneof" json:"charging,omitempty"`
	Details        *structpb.Struct       `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	GnssAccuracyM  *float64               `protobuf:"fixed64,4,opt,name=gnss_accuracy_m,json=gnssAccuracyM,proto3,oneof" json:"gnss_accuracy_m,omitempty"`
	GnssAltitudeM  *float64               `protobuf:"fixed64,5,opt,name=gnss_altitude_m,json=gnssAltitudeM,proto3,oneof" json:"gnss_altitude_m,omitempty"`
	GnssLatitude   *float64               `protobuf:"fixed64,6,opt,name=gnss_latitude,json=gnssLatitude,proto3,oneof" json:"gnss_latitude,omitempty"`
	GnssLongitude  *float64               `protobuf:"fixed64,7,opt,name=gnss_longitude,json=gnssLongitude,proto3,oneof" json:"gnss_longitude,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Muted          *bool                  `protobuf:"varint,9,opt,name=muted,proto3,oneof" json:"muted,omitempty"`
	ReportedAt     *string                `protobuf:"bytes,10,opt,name=reported_at,json=reportedAt,proto3,oneof" json:"reported_at,omitempty"`
	Volume         *int64                 `protobuf:"varint,11,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_payload_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{8}
}

func (x *PeerStatus) GetBatteryPercent() int64 {
	if x != nil && x.BatteryPercent != nil {
		return *x.BatteryPercent
	}
	return 0
}

func (x *PeerStatus) GetCharging() bool {
	if x != nil && x.Charging != nil {
		return *x.Charging
	}
	return false
}

func (x *PeerStatus) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *PeerStatus) GetGnssAccuracyM() float64 {
	if x != nil && x.GnssAccuracyM != nil {
		return *x.GnssAccuracyM
	}
	return 0
}

func (x *PeerStatus) GetGnssAltitudeM() float64 {
	if x != nil && x.GnssAltitudeM != nil {
		return *x.GnssAltitudeM
	}
	return 0
}

func (x *PeerStatus) GetGnssLatitude() float64 {
	if x != nil && x.GnssLatitude != nil {
		return *x.GnssLatitude
	}
	return 0
}

func (x *PeerStatus) GetGnssLongitude() float64 {
	if x != nil && x.GnssLongitude != nil {
		return *x.GnssLongitude
	}
	return 0
}

func (x *PeerStatus) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PeerStatus) GetMuted() bool {
	if x != nil && x.Muted != nil {
		return *x.Muted
	}
	return false
}

func (x *PeerStatus) GetReportedAt() string {
	if x != nil && x.ReportedAt != nil {
		return *x.ReportedAt
	}
	return ""
}

func (x *PeerStatus) GetVolume() int64 {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return 0
}

type PingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientSendTime int64                  `protobuf:"varint,1,opt,name=client_send_time,json=clientSendTime,proto3" json:"client_send_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_payload_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{9}
}

func (x *PingRequest) GetClientSendTime() int64 {
	if x != nil {
		return x.ClientSendTime
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_payload_system_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type RefreshIdentifiers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imeis         []*PeerIMEI            `protobuf:"bytes,1,rep,name=imeis,proto3" json:"imeis,omitempty"`
	Labels        []*PeerLabel           `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Sn            *string                `protobuf:"bytes,3,opt,name=sn,proto3,oneof" json:"sn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshIdentifiers) Reset() {
	*x = RefreshIdentifiers{}
	mi := &file_payload_system_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshIdentifiers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshIdentifiers) ProtoMessage() {}

func (x *RefreshIdentifiers) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshIdentifiers.ProtoReflect.Descriptor instead.
func (*RefreshIdentifiers) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshIdentifiers) GetImeis() []*PeerIMEI {
	if x != nil {
		return x.Imeis
	}
	return nil
}

func (x *RefreshIdentifiers) GetLabels() []*PeerLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RefreshIdentifiers) GetSn() string {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return ""
}

type RefreshInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HardwareRevision *string                `protobuf:"bytes,1,opt,name=hardware_revision,json=hardwareRevision,proto3,oneof" json:"hardware_revision,omitempty"`
	Manufacturer     *string                `protobuf:"bytes,2,opt,name=manufacturer,proto3,oneof" json:"manufacturer,omitempty"`
	Model            *string                `protobuf:"bytes,3,opt,name=model,proto3,oneof" json:"model,omitempty"`
	Name             *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RefreshInfo) Reset() {
	*x = RefreshInfo{}
	mi := &file_payload_system_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshInfo) ProtoMessage() {}

func (x *RefreshInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshInfo.ProtoReflect.Descriptor instead.
func (*RefreshInfo) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshInfo) GetHardwareRevision() string {
	if x != nil && x.HardwareRevision != nil {
		return *x.HardwareRevision
	}
	return ""
}

func (x *RefreshInfo) GetManufacturer() string {
	if x != nil && x.Manufacturer != nil {
		return *x.Manufacturer
	}
	return ""
}

func (x *RefreshInfo) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *RefreshInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type Runtime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastAddr      *string                `protobuf:"bytes,1,opt,name=last_addr,json=lastAddr,proto3,oneof" json:"last_addr,omitempty"`
	LastSeenAt    string                 `protobuf:"bytes,2,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	RxBytes       *uint64                `protobuf:"varint,4,opt,name=rx_bytes,json=rxBytes,proto3,oneof" json:"rx_bytes,omitempty"`
	TxBytes       *uint64                `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3,oneof" json:"tx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runtime) Reset() {
	*x = Runtime{}
	mi := &file_payload_system_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runtime) ProtoMessage() {}

func (x *Runtime) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runtime.ProtoReflect.Descriptor instead.
func (*Runtime) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{13}
}

func (x *Runtime) GetLastAddr() string {
	if x != nil && x.LastAddr != nil {
		return *x.LastAddr
	}
	return ""
}

func (x *Runtime) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *Runtime) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Runtime) GetRxBytes() uint64 {
	if x != nil && x.RxBytes != nil {
		return *x.RxBytes
	}
	return 0
}

func (x *Runtime) GetTxBytes() uint64 {
	if x != nil && x.TxBytes != nil {
		return *x.TxBytes
	}
	return 0
}

type ServerGetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetInfoRequest) Reset() {
	*x = ServerGetInfoRequest{}
	mi := &file_payload_system_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetInfoRequest) ProtoMessage() {}

func (x *ServerGetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerGetInfoRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{14}
}

type ServerGetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *DeviceInfo            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetInfoResponse) Reset() {
	*x = ServerGetInfoResponse{}
	mi := &file_payload_system_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetInfoResponse) ProtoMessage() {}

func (x *ServerGetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerGetInfoResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{15}
}

func (x *ServerGetInfoResponse) GetValue() *DeviceInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

type ServerGetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetStatusRequest) Reset() {
	*x = ServerGetStatusRequest{}
	mi := &file_payload_system_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetStatusRequest) ProtoMessage() {}

func (x *ServerGetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetStatusRequest.ProtoReflect.Descriptor instead.
func (*ServerGetStatusRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{16}
}

type ServerGetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *PeerStatus            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetStatusResponse) Reset() {
	*x = ServerGetStatusResponse{}
	mi := &file_payload_system_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetStatusResponse) ProtoMessage() {}

func (x *ServerGetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetStatusResponse.ProtoReflect.Descriptor instead.
func (*ServerGetStatusResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{17}
}

func (x *ServerGetStatusResponse) GetValue() *PeerStatus {
	if x != nil {
		return x.Value
	}
	return nil
}

type ServerPutInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *DeviceInfo            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPutInfoRequest) Reset() {
	*x = ServerPutInfoRequest{}
	mi := &file_payload_system_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPutInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPutInfoRequest) ProtoMessage() {}

func (x *ServerPutInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPutInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerPutInfoRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{18}
}

func (x *ServerPutInfoRequest) GetValue() *DeviceInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

type ServerPutInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *DeviceInfo            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPutInfoResponse) Reset() {
	*x = ServerPutInfoResponse{}
	mi := &file_payload_system_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPutInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPutInfoResponse) ProtoMessage() {}

func (x *ServerPutInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPutInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerPutInfoResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{19}
}

func (x *ServerPutInfoResponse) GetValue() *DeviceInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

type ServerInfoIconDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        IconFormat             `protobuf:"varint,1,opt,name=format,proto3,enum=gizclaw.rpc.v1.IconFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoIconDeleteRequest) Reset() {
	*x = ServerInfoIconDeleteRequest{}
	mi := &file_payload_system_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoIconDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoIconDeleteRequest) ProtoMessage() {}

func (x *ServerInfoIconDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoIconDeleteRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoIconDeleteRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{20}
}

func (x *ServerInfoIconDeleteRequest) GetFormat() IconFormat {
	if x != nil {
		return x.Format
	}
	return IconFormat_ICON_FORMAT_UNSPECIFIED
}

type ServerInfoIconDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *DeviceInfo            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoIconDeleteResponse) Reset() {
	*x = ServerInfoIconDeleteResponse{}
	mi := &file_payload_system_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoIconDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoIconDeleteResponse) ProtoMessage() {}

func (x *ServerInfoIconDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoIconDeleteResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoIconDeleteResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{21}
}

func (x *ServerInfoIconDeleteResponse) GetValue() *DeviceInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

type ServerInfoIconDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        IconFormat             `protobuf:"varint,1,opt,name=format,proto3,enum=gizclaw.rpc.v1.IconFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoIconDownloadRequest) Reset() {
	*x = ServerInfoIconDownloadRequest{}
	mi := &file_payload_system_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoIconDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoIconDownloadRequest) ProtoMessage() {}

func (x *ServerInfoIconDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoIconDownloadRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoIconDownloadRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{22}
}

func (x *ServerInfoIconDownloadRequest) GetFormat() IconFormat {
	if x != nil {
		return x.Format
	}
	return IconFormat_ICON_FORMAT_UNSPECIFIED
}

type ServerInfoIconDownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        IconFormat             `protobuf:"varint,1,opt,name=format,proto3,enum=gizclaw.rpc.v1.IconFormat" json:"format,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoIconDownloadResponse) Reset() {
	*x = ServerInfoIconDownloadResponse{}
	mi := &file_payload_system_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoIconDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoIconDownloadResponse) ProtoMessage() {}

func (x *ServerInfoIconDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoIconDownloadResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoIconDownloadResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{23}
}

func (x *ServerInfoIconDownloadResponse) GetFormat() IconFormat {
	if x != nil {
		return x.Format
	}
	return IconFormat_ICON_FORMAT_UNSPECIFIED
}

func (x *ServerInfoIconDownloadResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ServerInfoIconUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        IconFormat             `protobuf:"varint,1,opt,name=format,proto3,enum=gizclaw.rpc.v1.IconFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoIconUploadRequest) Reset() {
	*x = ServerInfoIconUploadRequest{}
	mi := &file_payload_system_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoIconUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoIconUploadRequest) ProtoMessage() {}

func (x *ServerInfoIconUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoIconUploadRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoIconUploadRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{24}
}

func (x *ServerInfoIconUploadRequest) GetFormat() IconFormat {
	if x != nil {
		return x.Format
	}
	return IconFormat_ICON_FORMAT_UNSPECIFIED
}

type ServerInfoIconUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *DeviceInfo            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoIconUploadResponse) Reset() {
	*x = ServerInfoIconUploadResponse{}
	mi := &file_payload_system_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoIconUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoIconUploadResponse) ProtoMessage() {}

func (x *ServerInfoIconUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoIconUploadResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoIconUploadResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{25}
}

func (x *ServerInfoIconUploadResponse) GetValue() *DeviceInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

type SpeedTestRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DownContentLength int64                  `protobuf:"varint,1,opt,name=down_content_length,json=downContentLength,proto3" json:"down_content_length,omitempty"`
	UpContentLength   int64                  `protobuf:"varint,2,opt,name=up_content_length,json=upContentLength,proto3" json:"up_content_length,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpeedTestRequest) Reset() {
	*x = SpeedTestRequest{}
	mi := &file_payload_system_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedTestRequest) ProtoMessage() {}

func (x *SpeedTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedTestRequest.ProtoReflect.Descriptor instead.
func (*SpeedTestRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{26}
}

func (x *SpeedTestRequest) GetDownContentLength() int64 {
	if x != nil {
		return x.DownContentLength
	}
	return 0
}

func (x *SpeedTestRequest) GetUpContentLength() int64 {
	if x != nil {
		return x.UpContentLength
	}
	return 0
}

type SpeedTestResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DownContentLength int64                  `protobuf:"varint,1,opt,name=down_content_length,json=downContentLength,proto3" json:"down_content_length,omitempty"`
	UpContentLength   int64                  `protobuf:"varint,2,opt,name=up_content_length,json=upContentLength,proto3" json:"up_content_length,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpeedTestResponse) Reset() {
	*x = SpeedTestResponse{}
	mi := &file_payload_system_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedTestResponse) ProtoMessage() {}

func (x *SpeedTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedTestResponse.ProtoReflect.Descriptor instead.
func (*SpeedTestResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{27}
}

func (x *SpeedTestResponse) GetDownContentLength() int64 {
	if x != nil {
		return x.DownContentLength
	}
	return 0
}

func (x *SpeedTestResponse) GetUpContentLength() int64 {
	if x != nil {
		return x.UpContentLength
	}
	return 0
}

var File_payload_system_proto protoreflect.FileDescriptor

const file_payload_system_proto_rawDesc = "" +
	"\n" +
	"\x14payload/system.proto\x12\x0egizclaw.rpc.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x13payload/enums.proto\x1a\x12payload/icon.proto\"\x1d\n" +
	"\x1bClientGetIdentifiersRequest\"X\n" +
	"\x1cClientGetIdentifiersResponse\x128\n" +
	"\x05value\x18\x01 \x01(\v2\".gizclaw.rpc.v1.RefreshIdentifiersR\x05value\"\x16\n" +
	"\x14ClientGetInfoRequest\"J\n" +
	"\x15ClientGetInfoResponse\x121\n" +
	"\x05value\x18\x01 \x01(\v2\x1b.gizclaw.rpc.v1.RefreshInfoR\x05value\"\xce\x01\n" +
	"\n" +
	"DeviceInfo\x12=\n" +
	"\bhardware\x18\x01 \x01(\v2\x1c.gizclaw.rpc.v1.HardwareInfoH\x00R\bhardware\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x13\n" +
	"\x02sn\x18\x03 \x01(\tH\x02R\x02sn\x88\x01\x01\x12-\n" +
	"\x04icon\x18\x04 \x01(\v2\x14.gizclaw.rpc.v1.IconH\x03R\x04icon\x88\x01\x01B\v\n" +
	"\t_hardwareB\a\n" +
	"\x05_nameB\x05\n" +
	"\x03_snB\a\n" +
	"\x05_icon\"\x98\x02\n" +
	"\fHardwareInfo\x120\n" +
	"\x11hardware_revision\x18\x01 \x01(\tH\x00R\x10hardwareRevision\x88\x01\x01\x12.\n" +
	"\x05imeis\x18\x02 \x03(\v2\x18.gizclaw.rpc.v1.PeerIMEIR\x05imeis\x121\n" +
	"\x06labels\x18\x03 \x03(\v2\x19.gizclaw.rpc.v1.PeerLabelR\x06labels\x12'\n" +
	"\fmanufacturer\x18\x04 \x01(\tH\x01R\fmanufacturer\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\x05 \x01(\tH\x02R\x05model\x88\x01\x01B\x14\n" +
	"\x12_hardware_revisionB\x0f\n" +
	"\r_manufacturerB\b\n" +
	"\x06_model\"V\n" +
	"\bPeerIMEI\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x10\n" +
	"\x03tac\x18\x03 \x01(\tR\x03tacB\a\n" +
	"\x05_name\"3\n" +
	"\tPeerLabel\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xaa\x05\n" +
	"\n" +
	"PeerStatus\x12,\n" +
	"\x0fbattery_percent\x18\x01 \x01(\x03H\x00R\x0ebatteryPercent\x88\x01\x01\x12\x1f\n" +
	"\bcharging\x18\x02 \x01(\bH\x01R\bcharging\x88\x01\x01\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails\x12+\n" +
	"\x0fgnss_accuracy_m\x18\x04 \x01(\x01H\x02R\rgnssAccuracyM\x88\x01\x01\x12+\n" +
	"\x0fgnss_altitude_m\x18\x05 \x01(\x01H\x03R\rgnssAltitudeM\x88\x01\x01\x12(\n" +
	"\rgnss_latitude\x18\x06 \x01(\x01H\x04R\fgnssLatitude\x88\x01\x01\x12*\n" +
	"\x0egnss_longitude\x18\a \x01(\x01H\x05R\rgnssLongitude\x88\x01\x01\x12>\n" +
	"\x06labels\x18\b \x03(\v2&.gizclaw.rpc.v1.PeerStatus.LabelsEntryR\x06labels\x12\x19\n" +
	"\x05muted\x18\t \x01(\bH\x06R\x05muted\x88\x01\x01\x12$\n" +
	"\vreported_at\x18\n" +
	" \x01(\tH\aR\n" +
	"reportedAt\x88\x01\x01\x12\x1b\n" +
	"\x06volume\x18\v \x01(\x03H\bR\x06volume\x88\x01\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_battery_percentB\v\n" +
	"\t_chargingB\x12\n" +
	"\x10_gnss_accuracy_mB\x12\n" +
	"\x10_gnss_altitude_mB\x10\n" +
	"\x0e_gnss_latitudeB\x11\n" +
	"\x0f_gnss_longitudeB\b\n" +
	"\x06_mutedB\x0e\n" +
	"\f_reported_atB\t\n" +
	"\a_volume\"7\n" +
	"\vPingRequest\x12(\n" +
	"\x10client_send_time\x18\x01 \x01(\x03R\x0eclientSendTime\"/\n" +
	"\fPingResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"\x93\x01\n" +
	"\x12RefreshIdentifiers\x12.\n" +
	"\x05imeis\x18\x01 \x03(\v2\x18.gizclaw.rpc.v1.PeerIMEIR\x05imeis\x121\n" +
	"\x06labels\x18\x02 \x03(\v2\x19.gizclaw.rpc.v1.PeerLabelR\x06labels\x12\x13\n" +
	"\x02sn\x18\x03 \x01(\tH\x00R\x02sn\x88\x01\x01B\x05\n" +
	"\x03_sn\"\xd6\x01\n" +
	"\vRefreshInfo\x120\n" +
	"\x11hardware_revision\x18\x01 \x01(\tH\x00R\x10hardwareRevision\x88\x01\x01\x12'\n" +
	"\fmanufacturer\x18\x02 \x01(\tH\x01R\fmanufacturer\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\x03 \x01(\tH\x02R\x05model\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x03R\x04name\x88\x01\x01B\x14\n" +
	"\x12_hardware_revisionB\x0f\n" +
	"\r_manufacturerB\b\n" +
	"\x06_modelB\a\n" +
	"\x05_name\"\xcd\x01\n" +
	"\aRuntime\x12 \n" +
	"\tlast_addr\x18\x01 \x01(\tH\x00R\blastAddr\x88\x01\x01\x12 \n" +
	"\flast_seen_at\x18\x02 \x01(\tR\n" +
	"lastSeenAt\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x12\x1e\n" +
	"\brx_bytes\x18\x04 \x01(\x04H\x01R\arxBytes\x88\x01\x01\x12\x1e\n" +
	"\btx_bytes\x18\x05 \x01(\x04H\x02R\atxBytes\x88\x01\x01B\f\n" +
	"\n" +
	"_last_addrB\v\n" +
	"\t_rx_bytesB\v\n" +
	"\t_tx_bytes\"\x16\n" +
	"\x14ServerGetInfoRequest\"I\n" +
	"\x15ServerGetInfoResponse\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.gizclaw.rpc.v1.DeviceInfoR\x05value\"\x18\n" +
	"\x16ServerGetStatusRequest\"K\n" +
	"\x17ServerGetStatusResponse\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.gizclaw.rpc.v1.PeerStatusR\x05value\"H\n" +
	"\x14ServerPutInfoRequest\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.gizclaw.rpc.v1.DeviceInfoR\x05value\"I\n" +
	"\x15ServerPutInfoResponse\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.gizclaw.rpc.v1.DeviceInfoR\x05value\"Q\n" +
	"\x1bServerInfoIconDeleteRequest\x122\n" +
	"\x06format\x18\x01 \x01(\x0e2\x1a.gizclaw.rpc.v1.IconFormatR\x06format\"P\n" +
	"\x1cServerInfoIconDeleteResponse\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.gizclaw.rpc.v1.DeviceInfoR\x05value\"S\n" +
	"\x1dServerInfoIconDownloadRequest\x122\n" +
	"\x06format\x18\x01 \x01(\x0e2\x1a.gizclaw.rpc.v1.IconFormatR\x06format\"s\n" +
	"\x1eServerInfoIconDownloadResponse\x122\n" +
	"\x06format\x18\x01 \x01(\x0e2\x1a.gizclaw.rpc.v1.IconFormatR\x06format\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\"Q\n" +
	"\x1bServerInfoIconUploadRequest\x122\n" +
	"\x06format\x18\x01 \x01(\x0e2\x1a.gizclaw.rpc.v1.IconFormatR\x06format\"P\n" +
	"\x1cServerInfoIconUploadResponse\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.gizclaw.rpc.v1.DeviceInfoR\x05value\"n\n" +
	"\x10SpeedTestRequest\x12.\n" +
	"\x13down_content_length\x18\x01 \x01(\x03R\x11downContentLength\x12*\n" +
	"\x11up_content_length\x18\x02 \x01(\x03R\x0fupContentLength\"o\n" +
	"\x11SpeedTestResponse\x12.\n" +
	"\x13down_content_length\x18\x01 \x01(\x03R\x11downContentLength\x12*\n" +
	"\x11up_content_length\x18\x02 \x01(\x03R\x0fupContentLengthB?Z=github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/rpcproto;rpcpbb\x06proto3"

var (
	file_payload_system_proto_rawDescOnce sync.Once
	file_payload_system_proto_rawDescData []byte
)

func file_payload_system_proto_rawDescGZIP() []byte {
	file_payload_system_proto_rawDescOnce.Do(func() {
		file_payload_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_system_proto_rawDesc), len(file_payload_system_proto_rawDesc)))
	})
	return file_payload_system_proto_rawDescData
}

var file_payload_system_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_payload_system_proto_goTypes = []any{
	(*ClientGetIdentifiersRequest)(nil),    // 0: gizclaw.rpc.v1.ClientGetIdentifiersRequest
	(*ClientGetIdentifiersResponse)(nil),   // 1: gizclaw.rpc.v1.ClientGetIdentifiersResponse
	(*ClientGetInfoRequest)(nil),           // 2: gizclaw.rpc.v1.ClientGetInfoRequest
	(*ClientGetInfoResponse)(nil),          // 3: gizclaw.rpc.v1.ClientGetInfoResponse
	(*DeviceInfo)(nil),                     // 4: gizclaw.rpc.v1.DeviceInfo
	(*HardwareInfo)(nil),                   // 5: gizclaw.rpc.v1.HardwareInfo
	(*PeerIMEI)(nil),                       // 6: gizclaw.rpc.v1.PeerIMEI
	(*PeerLabel)(nil),                      // 7: gizclaw.rpc.v1.PeerLabel
	(*PeerStatus)(nil),                     // 8: gizclaw.rpc.v1.PeerStatus
	(*PingRequest)(nil),                    // 9: gizclaw.rpc.v1.PingRequest
	(*PingResponse)(nil),                   // 10: gizclaw.rpc.v1.PingResponse
	(*RefreshIdentifiers)(nil),             // 11: gizclaw.rpc.v1.RefreshIdentifiers
	(*RefreshInfo)(nil),                    // 12: gizclaw.rpc.v1.RefreshInfo
	(*Runtime)(nil),                        // 13: gizclaw.rpc.v1.Runtime
	(*ServerGetInfoRequest)(nil),           // 14: gizclaw.rpc.v1.ServerGetInfoRequest
	(*ServerGetInfoResponse)(nil),          // 15: gizclaw.rpc.v1.ServerGetInfoResponse
	(*ServerGetStatusRequest)(nil),         // 16: gizclaw.rpc.v1.ServerGetStatusRequest
	(*ServerGetStatusResponse)(nil),        // 17: gizclaw.rpc.v1.ServerGetStatusResponse
	(*ServerPutInfoRequest)(nil),           // 18: gizclaw.rpc.v1.ServerPutInfoRequest
	(*ServerPutInfoResponse)(nil),          // 19: gizclaw.rpc.v1.ServerPutInfoResponse
	(*ServerInfoIconDeleteRequest)(nil),    // 20: gizclaw.rpc.v1.ServerInfoIconDeleteRequest
	(*ServerInfoIconDeleteResponse)(nil),   // 21: gizclaw.rpc.v1.ServerInfoIconDeleteResponse
	(*ServerInfoIconDownloadRequest)(nil),  // 22: gizclaw.rpc.v1.ServerInfoIconDownloadRequest
	(*ServerInfoIconDownloadResponse)(nil), // 23: gizclaw.rpc.v1.ServerInfoIconDownloadResponse
	(*ServerInfoIconUploadRequest)(nil),    // 24: gizclaw.rpc.v1.ServerInfoIconUploadRequest
	(*ServerInfoIconUploadResponse)(nil),   // 25: gizclaw.rpc.v1.ServerInfoIconUploadResponse
	(*SpeedTestRequest)(nil),               // 26: gizclaw.rpc.v1.SpeedTestRequest
	(*SpeedTestResponse)(nil),              // 27: gizclaw.rpc.v1.SpeedTestResponse
	nil,                                    // 28: gizclaw.rpc.v1.PeerStatus.LabelsEntry
	(*Icon)(nil),                           // 29: gizclaw.rpc.v1.Icon
	(*structpb.Struct)(nil),                // 30: google.protobuf.Struct
	(IconFormat)(0),                        // 31: gizclaw.rpc.v1.IconFormat
}
var file_payload_system_proto_depIdxs = []int32{
	11, // 0: gizclaw.rpc.v1.ClientGetIdentifiersResponse.value:type_name -> gizclaw.rpc.v1.RefreshIdentifiers
	12, // 1: gizclaw.rpc.v1.ClientGetInfoResponse.value:type_name -> gizclaw.rpc.v1.RefreshInfo
	5,  // 2: gizclaw.rpc.v1.DeviceInfo.hardware:type_name -> gizclaw.rpc.v1.HardwareInfo
	29, // 3: gizclaw.rpc.v1.DeviceInfo.icon:type_name -> gizclaw.rpc.v1.Icon
	6,  // 4: gizclaw.rpc.v1.HardwareInfo.imeis:type_name -> gizclaw.rpc.v1.PeerIMEI
	7,  // 5: gizclaw.rpc.v1.HardwareInfo.labels:type_name -> gizclaw.rpc.v1.PeerLabel
	30, // 6: gizclaw.rpc.v1.PeerStatus.details:type_name -> google.protobuf.Struct
	28, // 7: gizclaw.rpc.v1.PeerStatus.labels:type_name -> gizclaw.rpc.v1.PeerStatus.LabelsEntry
	6,  // 8: gizclaw.rpc.v1.RefreshIdentifiers.imeis:type_name -> gizclaw.rpc.v1.PeerIMEI
	7,  // 9: gizclaw.rpc.v1.RefreshIdentifiers.labels:type_name -> gizclaw.rpc.v1.PeerLabel
	4,  // 10: gizclaw.rpc.v1.ServerGetInfoResponse.value:type_name -> gizclaw.rpc.v1.DeviceInfo
	8,  // 11: gizclaw.rpc.v1.ServerGetStatusResponse.value:type_name -> gizclaw.rpc.v1.PeerStatus
	4,  // 12: gizclaw.rpc.v1.ServerPutInfoRequest.value:type_name -> gizclaw.rpc.v1.DeviceInfo
	4,  // 13: gizclaw.rpc.v1.ServerPutInfoResponse.value:type_name -> gizclaw.rpc.v1.DeviceInfo
	31, // 14: gizclaw.rpc.v1.ServerInfoIconDeleteRequest.format:type_name -> gizclaw.rpc.v1.IconFormat
	4,  // 15: gizclaw.rpc.v1.ServerInfoIconDeleteResponse.value:type_name -> gizclaw.rpc.v1.DeviceInfo
	31, // 16: gizclaw.rpc.v1.ServerInfoIconDownloadRequest.format:type_name -> gizclaw.rpc.v1.IconFormat
	31, // 17: gizclaw.rpc.v1.ServerInfoIconDownloadResponse.format:type_name -> gizclaw.rpc.v1.IconFormat
	31, // 18: gizclaw.rpc.v1.ServerInfoIconUploadRequest.format:type_name -> gizclaw.rpc.v1.IconFormat
	4,  // 19: gizclaw.rpc.v1.ServerInfoIconUploadResponse.value:type_name -> gizclaw.rpc.v1.DeviceInfo
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_payload_system_proto_init() }
func file_payload_system_proto_init() {
	if File_payload_system_proto != nil {
		return
	}
	file_payload_enums_proto_init()
	file_payload_icon_proto_init()
	file_payload_system_proto_msgTypes[4].OneofWrappers = []any{}
	file_payload_system_proto_msgTypes[5].OneofWrappers = []any{}
	file_payload_system_proto_msgTypes[6].OneofWrappers = []any{}
	file_payload_system_proto_msgTypes[8].OneofWrappers = []any{}
	file_payload_system_proto_msgTypes[11].OneofWrappers = []any{}
	file_payload_system_proto_msgTypes[12].OneofWrappers = []any{}
	file_payload_system_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_system_proto_rawDesc), len(file_payload_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_system_proto_goTypes,
		DependencyIndexes: file_payload_system_proto_depIdxs,
		MessageInfos:      file_payload_system_proto_msgTypes,
	}.Build()
	File_payload_system_proto = out.File
	file_payload_system_proto_goTypes = nil
	file_payload_system_proto_depIdxs = nil
}
