// Peer RPC system payload protobuf schema.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payload/system.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientGetIdentifiersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGetIdentifiersRequest) Reset() {
	*x = ClientGetIdentifiersRequest{}
	mi := &file_payload_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetIdentifiersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetIdentifiersRequest) ProtoMessage() {}

func (x *ClientGetIdentifiersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetIdentifiersRequest.ProtoReflect.Descriptor instead.
func (*ClientGetIdentifiersRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{0}
}

type ClientGetIdentifiersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *DeviceIdentifiers     `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGetIdentifiersResponse) Reset() {
	*x = ClientGetIdentifiersResponse{}
	mi := &file_payload_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetIdentifiersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetIdentifiersResponse) ProtoMessage() {}

func (x *ClientGetIdentifiersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetIdentifiersResponse.ProtoReflect.Descriptor instead.
func (*ClientGetIdentifiersResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{1}
}

func (x *ClientGetIdentifiersResponse) GetValue() *DeviceIdentifiers {
	if x != nil {
		return x.Value
	}
	return nil
}

type ClientGetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGetInfoRequest) Reset() {
	*x = ClientGetInfoRequest{}
	mi := &file_payload_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetInfoRequest) ProtoMessage() {}

func (x *ClientGetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetInfoRequest.ProtoReflect.Descriptor instead.
func (*ClientGetInfoRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{2}
}

type ClientGetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *HardwareInfo          `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientGetInfoResponse) Reset() {
	*x = ClientGetInfoResponse{}
	mi := &file_payload_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientGetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientGetInfoResponse) ProtoMessage() {}

func (x *ClientGetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientGetInfoResponse.ProtoReflect.Descriptor instead.
func (*ClientGetInfoResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{3}
}

func (x *ClientGetInfoResponse) GetValue() *HardwareInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hardware      *HardwareInfo          `protobuf:"bytes,1,opt,name=hardware,proto3,oneof" json:"hardware,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Emoji         *string                `protobuf:"bytes,4,opt,name=emoji,proto3,oneof" json:"emoji,omitempty"`
	Identifiers   *DeviceIdentifiers     `protobuf:"bytes,5,opt,name=identifiers,proto3,oneof" json:"identifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_payload_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceInfo) GetHardware() *HardwareInfo {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *DeviceInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *DeviceInfo) GetEmoji() string {
	if x != nil && x.Emoji != nil {
		return *x.Emoji
	}
	return ""
}

func (x *DeviceInfo) GetIdentifiers() *DeviceIdentifiers {
	if x != nil {
		return x.Identifiers
	}
	return nil
}

type DeviceProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Emoji         *string                `protobuf:"bytes,2,opt,name=emoji,proto3,oneof" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceProfile) Reset() {
	*x = DeviceProfile{}
	mi := &file_payload_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceProfile) ProtoMessage() {}

func (x *DeviceProfile) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceProfile.ProtoReflect.Descriptor instead.
func (*DeviceProfile) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceProfile) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *DeviceProfile) GetEmoji() string {
	if x != nil && x.Emoji != nil {
		return *x.Emoji
	}
	return ""
}

type DeviceIdentifiers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            *string                `protobuf:"bytes,1,opt,name=sn,proto3,oneof" json:"sn,omitempty"`
	Imeis         []*PeerIMEI            `protobuf:"bytes,2,rep,name=imeis,proto3" json:"imeis,omitempty"`
	Labels        []*PeerLabel           `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceIdentifiers) Reset() {
	*x = DeviceIdentifiers{}
	mi := &file_payload_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceIdentifiers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIdentifiers) ProtoMessage() {}

func (x *DeviceIdentifiers) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIdentifiers.ProtoReflect.Descriptor instead.
func (*DeviceIdentifiers) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceIdentifiers) GetSn() string {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return ""
}

func (x *DeviceIdentifiers) GetImeis() []*PeerIMEI {
	if x != nil {
		return x.Imeis
	}
	return nil
}

func (x *DeviceIdentifiers) GetLabels() []*PeerLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

type HardwareInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HardwareRevision *string                `protobuf:"bytes,1,opt,name=hardware_revision,json=hardwareRevision,proto3,oneof" json:"hardware_revision,omitempty"`
	Manufacturer     *string                `protobuf:"bytes,2,opt,name=manufacturer,proto3,oneof" json:"manufacturer,omitempty"`
	Model            *string                `protobuf:"bytes,3,opt,name=model,proto3,oneof" json:"model,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HardwareInfo) Reset() {
	*x = HardwareInfo{}
	mi := &file_payload_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfo) ProtoMessage() {}

func (x *HardwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfo.ProtoReflect.Descriptor instead.
func (*HardwareInfo) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{7}
}

func (x *HardwareInfo) GetHardwareRevision() string {
	if x != nil && x.HardwareRevision != nil {
		return *x.HardwareRevision
	}
	return ""
}

func (x *HardwareInfo) GetManufacturer() string {
	if x != nil && x.Manufacturer != nil {
		return *x.Manufacturer
	}
	return ""
}

func (x *HardwareInfo) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

type PeerIMEI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Tac           string                 `protobuf:"bytes,3,opt,name=tac,proto3" json:"tac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerIMEI) Reset() {
	*x = PeerIMEI{}
	mi := &file_payload_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerIMEI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerIMEI) ProtoMessage() {}

func (x *PeerIMEI) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerIMEI.ProtoReflect.Descriptor instead.
func (*PeerIMEI) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{8}
}

func (x *PeerIMEI) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PeerIMEI) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *PeerIMEI) GetTac() string {
	if x != nil {
		return x.Tac
	}
	return ""
}

type PeerLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerLabel) Reset() {
	*x = PeerLabel{}
	mi := &file_payload_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerLabel) ProtoMessage() {}

func (x *PeerLabel) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerLabel.ProtoReflect.Descriptor instead.
func (*PeerLabel) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{9}
}

func (x *PeerLabel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PeerLabel) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PeerStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BatteryPercent *int64                 `protobuf:"varint,1,opt,name=battery_percent,json=batteryPercent,proto3,oneof" json:"battery_percent,omitempty"`
	Charging       *bool                  `protobuf:"varint,2,opt,name=charging,proto3,oneof" json:"charging,omitempty"`
	Details        *structpb.Struct       `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	GnssAccuracyM  *float64               `protobuf:"fixed64,4,opt,name=gnss_accuracy_m,json=gnssAccuracyM,proto3,oneof" json:"gnss_accuracy_m,omitempty"`
	GnssAltitudeM  *float64               `protobuf:"fixed64,5,opt,name=gnss_altitude_m,json=gnssAltitudeM,proto3,oneof" json:"gnss_altitude_m,omitempty"`
	GnssLatitude   *float64               `protobuf:"fixed64,6,opt,name=gnss_latitude,json=gnssLatitude,proto3,oneof" json:"gnss_latitude,omitempty"`
	GnssLongitude  *float64               `protobuf:"fixed64,7,opt,name=gnss_longitude,json=gnssLongitude,proto3,oneof" json:"gnss_longitude,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Muted          *bool                  `protobuf:"varint,9,opt,name=muted,proto3,oneof" json:"muted,omitempty"`
	ReportedAt     *string                `protobuf:"bytes,10,opt,name=reported_at,json=reportedAt,proto3,oneof" json:"reported_at,omitempty"`
	Volume         *int64                 `protobuf:"varint,11,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_payload_system_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{10}
}

func (x *PeerStatus) GetBatteryPercent() int64 {
	if x != nil && x.BatteryPercent != nil {
		return *x.BatteryPercent
	}
	return 0
}

func (x *PeerStatus) GetCharging() bool {
	if x != nil && x.Charging != nil {
		return *x.Charging
	}
	return false
}

func (x *PeerStatus) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *PeerStatus) GetGnssAccuracyM() float64 {
	if x != nil && x.GnssAccuracyM != nil {
		return *x.GnssAccuracyM
	}
	return 0
}

func (x *PeerStatus) GetGnssAltitudeM() float64 {
	if x != nil && x.GnssAltitudeM != nil {
		return *x.GnssAltitudeM
	}
	return 0
}

func (x *PeerStatus) GetGnssLatitude() float64 {
	if x != nil && x.GnssLatitude != nil {
		return *x.GnssLatitude
	}
	return 0
}

func (x *PeerStatus) GetGnssLongitude() float64 {
	if x != nil && x.GnssLongitude != nil {
		return *x.GnssLongitude
	}
	return 0
}

func (x *PeerStatus) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PeerStatus) GetMuted() bool {
	if x != nil && x.Muted != nil {
		return *x.Muted
	}
	return false
}

func (x *PeerStatus) GetReportedAt() string {
	if x != nil && x.ReportedAt != nil {
		return *x.ReportedAt
	}
	return ""
}

func (x *PeerStatus) GetVolume() int64 {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return 0
}

type PingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientSendTime int64                  `protobuf:"varint,1,opt,name=client_send_time,json=clientSendTime,proto3" json:"client_send_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_payload_system_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{11}
}

func (x *PingRequest) GetClientSendTime() int64 {
	if x != nil {
		return x.ClientSendTime
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_payload_system_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{12}
}

func (x *PingResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type ServerRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerRegisterRequest) Reset() {
	*x = ServerRegisterRequest{}
	mi := &file_payload_system_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRegisterRequest) ProtoMessage() {}

func (x *ServerRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRegisterRequest.ProtoReflect.Descriptor instead.
func (*ServerRegisterRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{13}
}

func (x *ServerRegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ServerRegisterResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RuntimeProfileName string                 `protobuf:"bytes,1,opt,name=runtime_profile_name,json=runtimeProfileName,proto3" json:"runtime_profile_name,omitempty"`
	FirmwareId         *string                `protobuf:"bytes,2,opt,name=firmware_id,json=firmwareId,proto3,oneof" json:"firmware_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerRegisterResponse) Reset() {
	*x = ServerRegisterResponse{}
	mi := &file_payload_system_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRegisterResponse) ProtoMessage() {}

func (x *ServerRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRegisterResponse.ProtoReflect.Descriptor instead.
func (*ServerRegisterResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{14}
}

func (x *ServerRegisterResponse) GetRuntimeProfileName() string {
	if x != nil {
		return x.RuntimeProfileName
	}
	return ""
}

func (x *ServerRegisterResponse) GetFirmwareId() string {
	if x != nil && x.FirmwareId != nil {
		return *x.FirmwareId
	}
	return ""
}

type ServerPeerDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPeerDeleteRequest) Reset() {
	*x = ServerPeerDeleteRequest{}
	mi := &file_payload_system_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPeerDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPeerDeleteRequest) ProtoMessage() {}

func (x *ServerPeerDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPeerDeleteRequest.ProtoReflect.Descriptor instead.
func (*ServerPeerDeleteRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{15}
}

type ServerPeerDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPeerDeleteResponse) Reset() {
	*x = ServerPeerDeleteResponse{}
	mi := &file_payload_system_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPeerDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPeerDeleteResponse) ProtoMessage() {}

func (x *ServerPeerDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPeerDeleteResponse.ProtoReflect.Descriptor instead.
func (*ServerPeerDeleteResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{16}
}

type Runtime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastAddr      *string                `protobuf:"bytes,1,opt,name=last_addr,json=lastAddr,proto3,oneof" json:"last_addr,omitempty"`
	LastSeenAt    string                 `protobuf:"bytes,2,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	RxBytes       *uint64                `protobuf:"varint,4,opt,name=rx_bytes,json=rxBytes,proto3,oneof" json:"rx_bytes,omitempty"`
	TxBytes       *uint64                `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3,oneof" json:"tx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runtime) Reset() {
	*x = Runtime{}
	mi := &file_payload_system_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runtime) ProtoMessage() {}

func (x *Runtime) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runtime.ProtoReflect.Descriptor instead.
func (*Runtime) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{17}
}

func (x *Runtime) GetLastAddr() string {
	if x != nil && x.LastAddr != nil {
		return *x.LastAddr
	}
	return ""
}

func (x *Runtime) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *Runtime) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Runtime) GetRxBytes() uint64 {
	if x != nil && x.RxBytes != nil {
		return *x.RxBytes
	}
	return 0
}

func (x *Runtime) GetTxBytes() uint64 {
	if x != nil && x.TxBytes != nil {
		return *x.TxBytes
	}
	return 0
}

type ServerGetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetInfoRequest) Reset() {
	*x = ServerGetInfoRequest{}
	mi := &file_payload_system_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetInfoRequest) ProtoMessage() {}

func (x *ServerGetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerGetInfoRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{18}
}

type ServerGetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *DeviceInfo            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetInfoResponse) Reset() {
	*x = ServerGetInfoResponse{}
	mi := &file_payload_system_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetInfoResponse) ProtoMessage() {}

func (x *ServerGetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerGetInfoResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{19}
}

func (x *ServerGetInfoResponse) GetValue() *DeviceInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

type ServerGetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetStatusRequest) Reset() {
	*x = ServerGetStatusRequest{}
	mi := &file_payload_system_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetStatusRequest) ProtoMessage() {}

func (x *ServerGetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetStatusRequest.ProtoReflect.Descriptor instead.
func (*ServerGetStatusRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{20}
}

type ServerGetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *PeerStatus            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGetStatusResponse) Reset() {
	*x = ServerGetStatusResponse{}
	mi := &file_payload_system_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGetStatusResponse) ProtoMessage() {}

func (x *ServerGetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGetStatusResponse.ProtoReflect.Descriptor instead.
func (*ServerGetStatusResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{21}
}

func (x *ServerGetStatusResponse) GetValue() *PeerStatus {
	if x != nil {
		return x.Value
	}
	return nil
}

type ServerPutInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *DeviceProfile         `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPutInfoRequest) Reset() {
	*x = ServerPutInfoRequest{}
	mi := &file_payload_system_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPutInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPutInfoRequest) ProtoMessage() {}

func (x *ServerPutInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPutInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerPutInfoRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{22}
}

func (x *ServerPutInfoRequest) GetValue() *DeviceProfile {
	if x != nil {
		return x.Value
	}
	return nil
}

type ServerPutInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *DeviceInfo            `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPutInfoResponse) Reset() {
	*x = ServerPutInfoResponse{}
	mi := &file_payload_system_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPutInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPutInfoResponse) ProtoMessage() {}

func (x *ServerPutInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPutInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerPutInfoResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{23}
}

func (x *ServerPutInfoResponse) GetValue() *DeviceInfo {
	if x != nil {
		return x.Value
	}
	return nil
}

type SpeedTestRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DownContentLength int64                  `protobuf:"varint,1,opt,name=down_content_length,json=downContentLength,proto3" json:"down_content_length,omitempty"`
	UpContentLength   int64                  `protobuf:"varint,2,opt,name=up_content_length,json=upContentLength,proto3" json:"up_content_length,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpeedTestRequest) Reset() {
	*x = SpeedTestRequest{}
	mi := &file_payload_system_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedTestRequest) ProtoMessage() {}

func (x *SpeedTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedTestRequest.ProtoReflect.Descriptor instead.
func (*SpeedTestRequest) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{24}
}

func (x *SpeedTestRequest) GetDownContentLength() int64 {
	if x != nil {
		return x.DownContentLength
	}
	return 0
}

func (x *SpeedTestRequest) GetUpContentLength() int64 {
	if x != nil {
		return x.UpContentLength
	}
	return 0
}

type SpeedTestResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DownContentLength int64                  `protobuf:"varint,1,opt,name=down_content_length,json=downContentLength,proto3" json:"down_content_length,omitempty"`
	UpContentLength   int64                  `protobuf:"varint,2,opt,name=up_content_length,json=upContentLength,proto3" json:"up_content_length,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpeedTestResponse) Reset() {
	*x = SpeedTestResponse{}
	mi := &file_payload_system_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedTestResponse) ProtoMessage() {}

func (x *SpeedTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payload_system_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedTestResponse.ProtoReflect.Descriptor instead.
func (*SpeedTestResponse) Descriptor() ([]byte, []int) {
	return file_payload_system_proto_rawDescGZIP(), []int{25}
}

func (x *SpeedTestResponse) GetDownContentLength() int64 {
	if x != nil {
		return x.DownContentLength
	}
	return 0
}

func (x *SpeedTestResponse) GetUpContentLength() int64 {
	if x != nil {
		return x.UpContentLength
	}
	return 0
}

var File_payload_system_proto protoreflect.FileDescriptor

const file_payload_system_proto_rawDesc = "" +
	"\n" +
	"\x14payload/system.proto\x12\x0egizclaw.rpc.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x1d\n" +
	"\x1bClientGetIdentifiersRequest\"W\n" +
	"\x1cClientGetIdentifiersResponse\x127\n" +
	"\x05value\x18\x01 \x01(\v2!.gizclaw.rpc.v1.DeviceIdentifiersR\x05value\"\x16\n" +
	"\x14ClientGetInfoRequest\"K\n" +
	"\x15ClientGetInfoResponse\x122\n" +
	"\x05value\x18\x01 \x01(\v2\x1c.gizclaw.rpc.v1.HardwareInfoR\x05value\"\xf9\x01\n" +
	"\n" +
	"DeviceInfo\x12=\n" +
	"\bhardware\x18\x01 \x01(\v2\x1c.gizclaw.rpc.v1.HardwareInfoH\x00R\bhardware\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05emoji\x18\x04 \x01(\tH\x02R\x05emoji\x88\x01\x01\x12H\n" +
	"\videntifiers\x18\x05 \x01(\v2!.gizclaw.rpc.v1.DeviceIdentifiersH\x03R\videntifiers\x88\x01\x01B\v\n" +
	"\t_hardwareB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_emojiB\x0e\n" +
	"\f_identifiers\"V\n" +
	"\rDeviceProfile\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05emoji\x18\x02 \x01(\tH\x01R\x05emoji\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_emoji\"\x92\x01\n" +
	"\x11DeviceIdentifiers\x12\x13\n" +
	"\x02sn\x18\x01 \x01(\tH\x00R\x02sn\x88\x01\x01\x12.\n" +
	"\x05imeis\x18\x02 \x03(\v2\x18.gizclaw.rpc.v1.PeerIMEIR\x05imeis\x121\n" +
	"\x06labels\x18\x03 \x03(\v2\x19.gizclaw.rpc.v1.PeerLabelR\x06labelsB\x05\n" +
	"\x03_sn\"\xb5\x01\n" +
	"\fHardwareInfo\x120\n" +
	"\x11hardware_revision\x18\x01 \x01(\tH\x00R\x10hardwareRevision\x88\x01\x01\x12'\n" +
	"\fmanufacturer\x18\x02 \x01(\tH\x01R\fmanufacturer\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\x03 \x01(\tH\x02R\x05model\x88\x01\x01B\x14\n" +
	"\x12_hardware_revisionB\x0f\n" +
	"\r_manufacturerB\b\n" +
	"\x06_model\"V\n" +
	"\bPeerIMEI\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x10\n" +
	"\x03tac\x18\x03 \x01(\tR\x03tacB\a\n" +
	"\x05_name\"3\n" +
	"\tPeerLabel\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xaa\x05\n" +
	"\n" +
	"PeerStatus\x12,\n" +
	"\x0fbattery_percent\x18\x01 \x01(\x03H\x00R\x0ebatteryPercent\x88\x01\x01\x12\x1f\n" +
	"\bcharging\x18\x02 \x01(\bH\x01R\bcharging\x88\x01\x01\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails\x12+\n" +
	"\x0fgnss_accuracy_m\x18\x04 \x01(\x01H\x02R\rgnssAccuracyM\x88\x01\x01\x12+\n" +
	"\x0fgnss_altitude_m\x18\x05 \x01(\x01H\x03R\rgnssAltitudeM\x88\x01\x01\x12(\n" +
	"\rgnss_latitude\x18\x06 \x01(\x01H\x04R\fgnssLatitude\x88\x01\x01\x12*\n" +
	"\x0egnss_longitude\x18\a \x01(\x01H\x05R\rgnssLongitude\x88\x01\x01\x12>\n" +
	"\x06labels\x18\b \x03(\v2&.gizclaw.rpc.v1.PeerStatus.LabelsEntryR\x06labels\x12\x19\n" +
	"\x05muted\x18\t \x01(\bH\x06R\x05muted\x88\x01\x01\x12$\n" +
	"\vreported_at\x18\n" +
	" \x01(\tH\aR\n" +
	"reportedAt\x88\x01\x01\x12\x1b\n" +
	"\x06volume\x18\v \x01(\x03H\bR\x06volume\x88\x01\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_battery_percentB\v\n" +
	"\t_chargingB\x12\n" +
	"\x10_gnss_accuracy_mB\x12\n" +
	"\x10_gnss_altitude_mB\x10\n" +
	"\x0e_gnss_latitudeB\x11\n" +
	"\x0f_gnss_longitudeB\b\n" +
	"\x06_mutedB\x0e\n" +
	"\f_reported_atB\t\n" +
	"\a_volume\"7\n" +
	"\vPingRequest\x12(\n" +
	"\x10client_send_time\x18\x01 \x01(\x03R\x0eclientSendTime\"/\n" +
	"\fPingResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"-\n" +
	"\x15ServerRegisterRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x80\x01\n" +
	"\x16ServerRegisterResponse\x120\n" +
	"\x14runtime_profile_name\x18\x01 \x01(\tR\x12runtimeProfileName\x12$\n" +
	"\vfirmware_id\x18\x02 \x01(\tH\x00R\n" +
	"firmwareId\x88\x01\x01B\x0e\n" +
	"\f_firmware_id\"\x19\n" +
	"\x17ServerPeerDeleteRequest\"\x1a\n" +
	"\x18ServerPeerDeleteResponse\"\xcd\x01\n" +
	"\aRuntime\x12 \n" +
	"\tlast_addr\x18\x01 \x01(\tH\x00R\blastAddr\x88\x01\x01\x12 \n" +
	"\flast_seen_at\x18\x02 \x01(\tR\n" +
	"lastSeenAt\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x12\x1e\n" +
	"\brx_bytes\x18\x04 \x01(\x04H\x01R\arxBytes\x88\x01\x01\x12\x1e\n" +
	"\btx_bytes\x18\x05 \x01(\x04H\x02R\atxBytes\x88\x01\x01B\f\n" +
	"\n" +
	"_last_addrB\v\n" +
	"\t_rx_bytesB\v\n" +
	"\t_tx_bytes\"\x16\n" +
	"\x14ServerGetInfoRequest\"I\n" +
	"\x15ServerGetInfoResponse\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.gizclaw.rpc.v1.DeviceInfoR\x05value\"\x18\n" +
	"\x16ServerGetStatusRequest\"K\n" +
	"\x17ServerGetStatusResponse\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.gizclaw.rpc.v1.PeerStatusR\x05value\"K\n" +
	"\x14ServerPutInfoRequest\x123\n" +
	"\x05value\x18\x01 \x01(\v2\x1d.gizclaw.rpc.v1.DeviceProfileR\x05value\"I\n" +
	"\x15ServerPutInfoResponse\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.gizclaw.rpc.v1.DeviceInfoR\x05value\"n\n" +
	"\x10SpeedTestRequest\x12.\n" +
	"\x13down_content_length\x18\x01 \x01(\x03R\x11downContentLength\x12*\n" +
	"\x11up_content_length\x18\x02 \x01(\x03R\x0fupContentLength\"o\n" +
	"\x11SpeedTestResponse\x12.\n" +
	"\x13down_content_length\x18\x01 \x01(\x03R\x11downContentLength\x12*\n" +
	"\x11up_content_length\x18\x02 \x01(\x03R\x0fupContentLengthB?Z=github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/rpcproto;rpcpbb\x06proto3"

var (
	file_payload_system_proto_rawDescOnce sync.Once
	file_payload_system_proto_rawDescData []byte
)

func file_payload_system_proto_rawDescGZIP() []byte {
	file_payload_system_proto_rawDescOnce.Do(func() {
		file_payload_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_system_proto_rawDesc), len(file_payload_system_proto_rawDesc)))
	})
	return file_payload_system_proto_rawDescData
}

var file_payload_system_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_payload_system_proto_goTypes = []any{
	(*ClientGetIdentifiersRequest)(nil),  // 0: gizclaw.rpc.v1.ClientGetIdentifiersRequest
	(*ClientGetIdentifiersResponse)(nil), // 1: gizclaw.rpc.v1.ClientGetIdentifiersResponse
	(*ClientGetInfoRequest)(nil),         // 2: gizclaw.rpc.v1.ClientGetInfoRequest
	(*ClientGetInfoResponse)(nil),        // 3: gizclaw.rpc.v1.ClientGetInfoResponse
	(*DeviceInfo)(nil),                   // 4: gizclaw.rpc.v1.DeviceInfo
	(*DeviceProfile)(nil),                // 5: gizclaw.rpc.v1.DeviceProfile
	(*DeviceIdentifiers)(nil),            // 6: gizclaw.rpc.v1.DeviceIdentifiers
	(*HardwareInfo)(nil),                 // 7: gizclaw.rpc.v1.HardwareInfo
	(*PeerIMEI)(nil),                     // 8: gizclaw.rpc.v1.PeerIMEI
	(*PeerLabel)(nil),                    // 9: gizclaw.rpc.v1.PeerLabel
	(*PeerStatus)(nil),                   // 10: gizclaw.rpc.v1.PeerStatus
	(*PingRequest)(nil),                  // 11: gizclaw.rpc.v1.PingRequest
	(*PingResponse)(nil),                 // 12: gizclaw.rpc.v1.PingResponse
	(*ServerRegisterRequest)(nil),        // 13: gizclaw.rpc.v1.ServerRegisterRequest
	(*ServerRegisterResponse)(nil),       // 14: gizclaw.rpc.v1.ServerRegisterResponse
	(*ServerPeerDeleteRequest)(nil),      // 15: gizclaw.rpc.v1.ServerPeerDeleteRequest
	(*ServerPeerDeleteResponse)(nil),     // 16: gizclaw.rpc.v1.ServerPeerDeleteResponse
	(*Runtime)(nil),                      // 17: gizclaw.rpc.v1.Runtime
	(*ServerGetInfoRequest)(nil),         // 18: gizclaw.rpc.v1.ServerGetInfoRequest
	(*ServerGetInfoResponse)(nil),        // 19: gizclaw.rpc.v1.ServerGetInfoResponse
	(*ServerGetStatusRequest)(nil),       // 20: gizclaw.rpc.v1.ServerGetStatusRequest
	(*ServerGetStatusResponse)(nil),      // 21: gizclaw.rpc.v1.ServerGetStatusResponse
	(*ServerPutInfoRequest)(nil),         // 22: gizclaw.rpc.v1.ServerPutInfoRequest
	(*ServerPutInfoResponse)(nil),        // 23: gizclaw.rpc.v1.ServerPutInfoResponse
	(*SpeedTestRequest)(nil),             // 24: gizclaw.rpc.v1.SpeedTestRequest
	(*SpeedTestResponse)(nil),            // 25: gizclaw.rpc.v1.SpeedTestResponse
	nil,                                  // 26: gizclaw.rpc.v1.PeerStatus.LabelsEntry
	(*structpb.Struct)(nil),              // 27: google.protobuf.Struct
}
var file_payload_system_proto_depIdxs = []int32{
	6,  // 0: gizclaw.rpc.v1.ClientGetIdentifiersResponse.value:type_name -> gizclaw.rpc.v1.DeviceIdentifiers
	7,  // 1: gizclaw.rpc.v1.ClientGetInfoResponse.value:type_name -> gizclaw.rpc.v1.HardwareInfo
	7,  // 2: gizclaw.rpc.v1.DeviceInfo.hardware:type_name -> gizclaw.rpc.v1.HardwareInfo
	6,  // 3: gizclaw.rpc.v1.DeviceInfo.identifiers:type_name -> gizclaw.rpc.v1.DeviceIdentifiers
	8,  // 4: gizclaw.rpc.v1.DeviceIdentifiers.imeis:type_name -> gizclaw.rpc.v1.PeerIMEI
	9,  // 5: gizclaw.rpc.v1.DeviceIdentifiers.labels:type_name -> gizclaw.rpc.v1.PeerLabel
	27, // 6: gizclaw.rpc.v1.PeerStatus.details:type_name -> google.protobuf.Struct
	26, // 7: gizclaw.rpc.v1.PeerStatus.labels:type_name -> gizclaw.rpc.v1.PeerStatus.LabelsEntry
	4,  // 8: gizclaw.rpc.v1.ServerGetInfoResponse.value:type_name -> gizclaw.rpc.v1.DeviceInfo
	10, // 9: gizclaw.rpc.v1.ServerGetStatusResponse.value:type_name -> gizclaw.rpc.v1.PeerStatus
	5,  // 10: gizclaw.rpc.v1.ServerPutInfoRequest.value:type_name -> gizclaw.rpc.v1.DeviceProfile
	4,  // 11: gizclaw.rpc.v1.ServerPutInfoResponse.value:type_name -> gizclaw.rpc.v1.DeviceInfo
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_payload_system_proto_init() }
func file_payload_system_proto_init() {
	if File_payload_system_proto != nil {
		return
	}
	file_payload_system_proto_msgTypes[4].OneofWrappers = []any{}
	file_payload_system_proto_msgTypes[5].OneofWrappers = []any{}
	file_payload_system_proto_msgTypes[6].OneofWrappers = []any{}
	file_payload_system_proto_msgTypes[7].OneofWrappers = []any{}
	file_payload_system_proto_msgTypes[8].OneofWrappers = []any{}
	file_payload_system_proto_msgTypes[10].OneofWrappers = []any{}
	file_payload_system_proto_msgTypes[14].OneofWrappers = []any{}
	file_payload_system_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_system_proto_rawDesc), len(file_payload_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_system_proto_goTypes,
		DependencyIndexes: file_payload_system_proto_depIdxs,
		MessageInfos:      file_payload_system_proto_msgTypes,
	}.Build()
	File_payload_system_proto = out.File
	file_payload_system_proto_goTypes = nil
	file_payload_system_proto_depIdxs = nil
}
