import 'dart:convert';
import 'dart:io';

void main() {
  final repo = _repoRoot();
  final package = '$repo/sdk/flutter/gizclaw';
  final outDir = '$package/lib/src/generated/rpc';
  final output = Directory(outDir);
  if (output.existsSync()) {
    output.deleteSync(recursive: true);
  }
  Directory(outDir).createSync(recursive: true);

  final payloadFiles =
      Directory('$repo/api/proto/rpc/payload')
          .listSync()
          .whereType<File>()
          .where((file) => file.path.endsWith('.proto'))
          .map((file) => file.path)
          .toList()
        ..sort();
  if (payloadFiles.isEmpty) {
    throw StateError('api/proto/rpc/payload did not contain any proto files');
  }

  final protocArgs = [
    '--proto_path=$repo/api/proto/rpc',
    '--plugin=protoc-gen-dart=${_protocGenDart(package)}',
    '--dart_out=$outDir',
    '$repo/api/proto/rpc/rpc.proto',
    ...payloadFiles,
  ];
  final result = Process.runSync('protoc', protocArgs);
  if (result.exitCode != 0) {
    stderr.write(result.stderr);
    exit(result.exitCode);
  }

  _writePayloadBarrels(outDir, payloadFiles);

  final methods = _parseRpcMethods(
    File('$repo/api/proto/rpc/rpc.proto').readAsStringSync(),
  );
  if (methods.isEmpty) {
    throw StateError(
      'api/proto/rpc/rpc.proto did not define any rpc_method values',
    );
  }
  _writeMethodRegistry(package, methods);
  _writePayloadCodec(package, methods);
  _formatGeneratedFiles(package, outDir);
}

String _protocGenDart(String package) {
  final configFile = File('$package/.dart_tool/package_config.json');
  if (!configFile.existsSync()) {
    throw StateError('run flutter pub get before generating RPC sources');
  }
  final config =
      jsonDecode(configFile.readAsStringSync()) as Map<String, Object?>;
  final packages = config['packages']! as List<Object?>;
  final protocPlugin = packages.cast<Map<String, Object?>>().singleWhere(
    (entry) => entry['name'] == 'protoc_plugin',
  );
  final rootUri = configFile.uri.resolve(protocPlugin['rootUri']! as String);
  final executable = File.fromUri(
    Directory.fromUri(rootUri).uri.resolve('bin/protoc_plugin.dart'),
  );
  if (!executable.existsSync()) {
    throw StateError('protoc_plugin does not provide bin/protoc_plugin.dart');
  }
  final wrapper = File('$package/.dart_tool/protoc-gen-dart');
  wrapper.writeAsStringSync(
    '#!/bin/sh\n'
    'exec ${_shellQuote(Platform.resolvedExecutable)} '
    '--packages=${_shellQuote(configFile.path)} '
    '${_shellQuote(executable.path)} "\$@"\n',
  );
  final chmod = Process.runSync('chmod', ['+x', wrapper.path]);
  if (chmod.exitCode != 0) {
    stderr.write(chmod.stderr);
    throw StateError('could not make protoc-gen-dart wrapper executable');
  }
  return wrapper.path;
}

String _shellQuote(String value) {
  return "'${value.replaceAll("'", "'\"'\"'")}'";
}

void _writePayloadBarrels(String outDir, List<String> payloadFiles) {
  final libraries = payloadFiles.map((file) {
    final filename = file.split(Platform.pathSeparator).last;
    return filename.substring(0, filename.length - '.proto'.length);
  }).toList();

  for (final suffix in ['pb.dart', 'pbenum.dart', 'pbjson.dart']) {
    final buffer = StringBuffer(
      '// Generated by tool/generate_rpc.dart. Do not edit by hand.\n\n',
    );
    for (final library in libraries) {
      // Flutter applications commonly import material.Icon through the same
      // library that exports this barrel. Keep the protobuf Icon available via
      // its direct generated import without introducing that name collision.
      if (suffix == 'pb.dart' && library == 'icon') {
        continue;
      }
      buffer.writeln("export 'payload/$library.$suffix';");
    }
    File('$outDir/payload.$suffix').writeAsStringSync(buffer.toString());
  }
}

String _repoRoot() {
  final result = Process.runSync('git', ['rev-parse', '--show-toplevel']);
  if (result.exitCode != 0) {
    stderr.write(result.stderr);
    exit(result.exitCode);
  }
  return (result.stdout as String).trim();
}

List<_Method> _parseRpcMethods(String proto) {
  final methods = <_Method>[];
  final pattern = RegExp(
    r'^\s*RPC_METHOD_[A-Z0-9_]+\s*=\s*(\d+)\s*\[\(rpc_method\)\s*=\s*\{\s*name:\s*"([^"]+)"\s+request:\s*"(\w+)"\s+response:\s*"(\w+)"\s*\}\s*\]\s*;',
    multiLine: true,
  );
  for (final match in pattern.allMatches(proto)) {
    methods.add(
      _Method(
        id: int.parse(match.group(1)!),
        name: match.group(2)!,
        request: match.group(3)!,
        response: match.group(4)!,
      ),
    );
  }

  for (final line in proto.split('\n')) {
    if (line.trimLeft().startsWith('RPC_METHOD_') &&
        line.contains('=') &&
        !line.contains('RPC_METHOD_UNSPECIFIED') &&
        !line.contains('(rpc_method)')) {
      throw StateError(
        'RpcMethod entry missing rpc_method option: ${line.trim()}',
      );
    }
  }
  return methods;
}

void _writeMethodRegistry(String package, List<_Method> methods) {
  final buffer = StringBuffer()
    ..writeln('// Generated by tool/generate_rpc.dart. Do not edit by hand.')
    ..writeln()
    ..writeln('class RpcMethodDescriptor {')
    ..writeln('  const RpcMethodDescriptor({')
    ..writeln('    required this.id,')
    ..writeln('    required this.name,')
    ..writeln('    required this.requestType,')
    ..writeln('    required this.responseType,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  final int id;')
    ..writeln('  final String name;')
    ..writeln('  final String requestType;')
    ..writeln('  final String responseType;')
    ..writeln('}')
    ..writeln()
    ..writeln('const rpcMethodsByName = <String, RpcMethodDescriptor>{');
  for (final method in methods) {
    buffer
      ..writeln("  '${method.name}': RpcMethodDescriptor(")
      ..writeln('    id: ${method.id},')
      ..writeln("    name: '${method.name}',")
      ..writeln("    requestType: '${method.request}',")
      ..writeln("    responseType: '${method.response}',")
      ..writeln('  ),');
  }
  buffer
    ..writeln('};')
    ..writeln()
    ..writeln('const rpcMethodNamesById = <int, String>{');
  for (final method in methods) {
    buffer.writeln("  ${method.id}: '${method.name}',");
  }
  buffer
    ..writeln('};')
    ..writeln()
    ..writeln('RpcMethodDescriptor rpcMethodByName(String name) {')
    ..writeln('  final method = rpcMethodsByName[name];')
    ..writeln('  if (method == null) {')
    ..writeln(
      "    throw ArgumentError.value(name, 'name', 'unknown RPC method');",
    )
    ..writeln('  }')
    ..writeln('  return method;')
    ..writeln('}')
    ..writeln()
    ..writeln('String rpcMethodNameById(int id) {')
    ..writeln('  final name = rpcMethodNamesById[id];')
    ..writeln('  if (name == null) {')
    ..writeln(
      "    throw ArgumentError.value(id, 'id', 'unknown RPC method id');",
    )
    ..writeln('  }')
    ..writeln('  return name;')
    ..writeln('}');

  File(
    '$package/lib/src/method_registry.dart',
  ).writeAsStringSync(buffer.toString());
}

void _writePayloadCodec(String package, List<_Method> methods) {
  final types = <String>{};
  for (final method in methods) {
    types
      ..add(method.request)
      ..add(method.response);
  }
  final sortedTypes = types.toList()..sort();
  final buffer = StringBuffer()
    ..writeln('// Generated by tool/generate_rpc.dart. Do not edit by hand.')
    ..writeln()
    ..writeln("import 'package:protobuf/protobuf.dart';")
    ..writeln()
    ..writeln("import 'generated/rpc/payload.pb.dart' as payload;")
    ..writeln("import 'method_registry.dart';")
    ..writeln()
    ..writeln('typedef MessageFactory = GeneratedMessage Function();')
    ..writeln()
    ..writeln('final _messageFactories = <String, MessageFactory>{');
  for (final type in sortedTypes) {
    buffer.writeln("  '$type': payload.$type.new,");
  }
  buffer
    ..writeln('};')
    ..writeln()
    ..writeln('final _messageTypes = <String, Type>{');
  for (final type in sortedTypes) {
    buffer.writeln("  '$type': payload.$type,");
  }
  buffer
    ..writeln('};')
    ..writeln()
    ..writeln('GeneratedMessage newPayloadMessage(String type) {')
    ..writeln('  final factory = _messageFactories[type];')
    ..writeln('  if (factory == null) {')
    ..writeln(
      "    throw ArgumentError.value(type, 'type', 'unknown RPC payload type');",
    )
    ..writeln('  }')
    ..writeln('  return factory();')
    ..writeln('}')
    ..writeln()
    ..writeln('List<int> encodeRpcRequestPayload(')
    ..writeln('  String methodName,')
    ..writeln('  GeneratedMessage message,')
    ..writeln(') {')
    ..writeln('  final expected = rpcMethodByName(methodName).requestType;')
    ..writeln('  _expectPayloadType(expected, message);')
    ..writeln('  return message.writeToBuffer();')
    ..writeln('}')
    ..writeln()
    ..writeln('GeneratedMessage decodeRpcRequestPayload(')
    ..writeln('  String methodName,')
    ..writeln('  List<int> bytes,')
    ..writeln(') {')
    ..writeln('  final type = rpcMethodByName(methodName).requestType;')
    ..writeln('  final message = newPayloadMessage(type);')
    ..writeln('  message.mergeFromBuffer(bytes);')
    ..writeln('  return message;')
    ..writeln('}')
    ..writeln()
    ..writeln('List<int> encodeRpcResponsePayload(')
    ..writeln('  String methodName,')
    ..writeln('  GeneratedMessage message,')
    ..writeln(') {')
    ..writeln('  final expected = rpcMethodByName(methodName).responseType;')
    ..writeln('  _expectPayloadType(expected, message);')
    ..writeln('  return message.writeToBuffer();')
    ..writeln('}')
    ..writeln()
    ..writeln('GeneratedMessage decodeRpcResponsePayload(')
    ..writeln('  String methodName,')
    ..writeln('  List<int> bytes,')
    ..writeln(') {')
    ..writeln('  final type = rpcMethodByName(methodName).responseType;')
    ..writeln('  final message = newPayloadMessage(type);')
    ..writeln('  message.mergeFromBuffer(bytes);')
    ..writeln('  return message;')
    ..writeln('}')
    ..writeln()
    ..writeln('GeneratedMessage? decodeEmptyRpcResponsePayload(')
    ..writeln('  String methodName,')
    ..writeln(') {')
    ..writeln('  final type = rpcMethodByName(methodName).responseType;')
    ..writeln('  final message = newPayloadMessage(type);')
    ..writeln('  return message.info_.fieldInfo.isEmpty ? message : null;')
    ..writeln('}')
    ..writeln()
    ..writeln('void _expectPayloadType(')
    ..writeln('  String expected,')
    ..writeln('  GeneratedMessage message,')
    ..writeln(') {')
    ..writeln('  final expectedType = _messageTypes[expected];')
    ..writeln('  if (expectedType == null) {')
    ..writeln('    throw ArgumentError.value(')
    ..writeln('      expected,')
    ..writeln("      'expected',")
    ..writeln("      'unknown RPC payload type',")
    ..writeln('    );')
    ..writeln('  }')
    ..writeln('  final actualType = message.runtimeType;')
    ..writeln('  if (actualType != expectedType) {')
    ..writeln('    throw ArgumentError(')
    ..writeln(
      "      'RPC payload type mismatch: got \$actualType, want \$expected',",
    )
    ..writeln('    );')
    ..writeln('  }')
    ..writeln('}');

  File(
    '$package/lib/src/payload_codec.dart',
  ).writeAsStringSync(buffer.toString());
}

void _formatGeneratedFiles(String package, String outDir) {
  final result = Process.runSync('dart', [
    'format',
    outDir,
    '$package/lib/src/method_registry.dart',
    '$package/lib/src/payload_codec.dart',
  ]);
  if (result.exitCode != 0) {
    stdout.write(result.stdout);
    stderr.write(result.stderr);
    exit(result.exitCode);
  }
}

class _Method {
  const _Method({
    required this.id,
    required this.name,
    required this.request,
    required this.response,
  });

  final int id;
  final String name;
  final String request;
  final String response;
}
