package: clientservice
generate:
  fiber-server: true
  strict-server: true
  client: true
  models: true
import-mapping:
  ./rpc/server.json: github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/rpcapi
  ./type/voice.json: github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/apitypes
  ./type/voice_provider_kind.json: github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/apitypes
  ./type/voice_source.json: github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/apitypes
  ./type/workspace_parameters.json: github.com/GizClaw/gizclaw-go/pkgs/gizclaw/api/apitypes
output-options:
  skip-prune: true
