// Generated by tool/generate_rpc.dart. Do not edit by hand.

import 'package:protobuf/protobuf.dart';

import 'generated/rpc/payload.pb.dart' as payload;
import 'method_registry.dart';

typedef MessageFactory = GeneratedMessage Function();

final _messageFactories = <String, MessageFactory>{
  'BadgeDefPixaDownloadRequest': payload.BadgeDefPixaDownloadRequest.new,
  'BadgeDefPixaDownloadResponse': payload.BadgeDefPixaDownloadResponse.new,
  'ClientGetIdentifiersRequest': payload.ClientGetIdentifiersRequest.new,
  'ClientGetIdentifiersResponse': payload.ClientGetIdentifiersResponse.new,
  'ClientGetInfoRequest': payload.ClientGetInfoRequest.new,
  'ClientGetInfoResponse': payload.ClientGetInfoResponse.new,
  'ContactCreateRequest': payload.ContactCreateRequest.new,
  'ContactCreateResponse': payload.ContactCreateResponse.new,
  'ContactDeleteRequest': payload.ContactDeleteRequest.new,
  'ContactDeleteResponse': payload.ContactDeleteResponse.new,
  'ContactGetRequest': payload.ContactGetRequest.new,
  'ContactGetResponse': payload.ContactGetResponse.new,
  'ContactListRequest': payload.ContactListRequest.new,
  'ContactListResponse': payload.ContactListResponse.new,
  'ContactPutRequest': payload.ContactPutRequest.new,
  'ContactPutResponse': payload.ContactPutResponse.new,
  'FirmwareFilesDownloadRequest': payload.FirmwareFilesDownloadRequest.new,
  'FirmwareFilesDownloadResponse': payload.FirmwareFilesDownloadResponse.new,
  'FirmwareGetRequest': payload.FirmwareGetRequest.new,
  'FirmwareGetResponse': payload.FirmwareGetResponse.new,
  'FriendAddRequest': payload.FriendAddRequest.new,
  'FriendAddResponse': payload.FriendAddResponse.new,
  'FriendDeleteRequest': payload.FriendDeleteRequest.new,
  'FriendDeleteResponse': payload.FriendDeleteResponse.new,
  'FriendGroupCreateRequest': payload.FriendGroupCreateRequest.new,
  'FriendGroupCreateResponse': payload.FriendGroupCreateResponse.new,
  'FriendGroupDeleteRequest': payload.FriendGroupDeleteRequest.new,
  'FriendGroupDeleteResponse': payload.FriendGroupDeleteResponse.new,
  'FriendGroupGetRequest': payload.FriendGroupGetRequest.new,
  'FriendGroupGetResponse': payload.FriendGroupGetResponse.new,
  'FriendGroupInviteTokenClearRequest':
      payload.FriendGroupInviteTokenClearRequest.new,
  'FriendGroupInviteTokenClearResponse':
      payload.FriendGroupInviteTokenClearResponse.new,
  'FriendGroupInviteTokenCreateRequest':
      payload.FriendGroupInviteTokenCreateRequest.new,
  'FriendGroupInviteTokenCreateResponse':
      payload.FriendGroupInviteTokenCreateResponse.new,
  'FriendGroupInviteTokenGetRequest':
      payload.FriendGroupInviteTokenGetRequest.new,
  'FriendGroupInviteTokenGetResponse':
      payload.FriendGroupInviteTokenGetResponse.new,
  'FriendGroupJoinRequest': payload.FriendGroupJoinRequest.new,
  'FriendGroupJoinResponse': payload.FriendGroupJoinResponse.new,
  'FriendGroupListRequest': payload.FriendGroupListRequest.new,
  'FriendGroupListResponse': payload.FriendGroupListResponse.new,
  'FriendGroupMemberAddRequest': payload.FriendGroupMemberAddRequest.new,
  'FriendGroupMemberAddResponse': payload.FriendGroupMemberAddResponse.new,
  'FriendGroupMemberDeleteRequest': payload.FriendGroupMemberDeleteRequest.new,
  'FriendGroupMemberDeleteResponse':
      payload.FriendGroupMemberDeleteResponse.new,
  'FriendGroupMemberListRequest': payload.FriendGroupMemberListRequest.new,
  'FriendGroupMemberListResponse': payload.FriendGroupMemberListResponse.new,
  'FriendGroupMemberPutRequest': payload.FriendGroupMemberPutRequest.new,
  'FriendGroupMemberPutResponse': payload.FriendGroupMemberPutResponse.new,
  'FriendGroupMessageGetRequest': payload.FriendGroupMessageGetRequest.new,
  'FriendGroupMessageGetResponse': payload.FriendGroupMessageGetResponse.new,
  'FriendGroupMessageListRequest': payload.FriendGroupMessageListRequest.new,
  'FriendGroupMessageListResponse': payload.FriendGroupMessageListResponse.new,
  'FriendGroupMessageSendRequest': payload.FriendGroupMessageSendRequest.new,
  'FriendGroupMessageSendResponse': payload.FriendGroupMessageSendResponse.new,
  'FriendGroupPutRequest': payload.FriendGroupPutRequest.new,
  'FriendGroupPutResponse': payload.FriendGroupPutResponse.new,
  'FriendInfoGetRequest': payload.FriendInfoGetRequest.new,
  'FriendInfoGetResponse': payload.FriendInfoGetResponse.new,
  'FriendInviteTokenClearRequest': payload.FriendInviteTokenClearRequest.new,
  'FriendInviteTokenClearResponse': payload.FriendInviteTokenClearResponse.new,
  'FriendInviteTokenCreateRequest': payload.FriendInviteTokenCreateRequest.new,
  'FriendInviteTokenCreateResponse':
      payload.FriendInviteTokenCreateResponse.new,
  'FriendInviteTokenGetRequest': payload.FriendInviteTokenGetRequest.new,
  'FriendInviteTokenGetResponse': payload.FriendInviteTokenGetResponse.new,
  'FriendListRequest': payload.FriendListRequest.new,
  'FriendListResponse': payload.FriendListResponse.new,
  'ModelGetRequest': payload.ModelGetRequest.new,
  'ModelGetResponse': payload.ModelGetResponse.new,
  'ModelListRequest': payload.ModelListRequest.new,
  'ModelListResponse': payload.ModelListResponse.new,
  'PingRequest': payload.PingRequest.new,
  'PingResponse': payload.PingResponse.new,
  'RuntimeAdoptRequest': payload.RuntimeAdoptRequest.new,
  'RuntimeAdoptResponse': payload.RuntimeAdoptResponse.new,
  'ServerBadgeGetRequest': payload.ServerBadgeGetRequest.new,
  'ServerBadgeGetResponse': payload.ServerBadgeGetResponse.new,
  'ServerBadgeListRequest': payload.ServerBadgeListRequest.new,
  'ServerBadgeListResponse': payload.ServerBadgeListResponse.new,
  'ServerGameResultGetRequest': payload.ServerGameResultGetRequest.new,
  'ServerGameResultGetResponse': payload.ServerGameResultGetResponse.new,
  'ServerGameResultListRequest': payload.ServerGameResultListRequest.new,
  'ServerGameResultListResponse': payload.ServerGameResultListResponse.new,
  'ServerGetInfoRequest': payload.ServerGetInfoRequest.new,
  'ServerGetInfoResponse': payload.ServerGetInfoResponse.new,
  'ServerGetRunAgentRequest': payload.ServerGetRunAgentRequest.new,
  'ServerGetRunAgentResponse': payload.ServerGetRunAgentResponse.new,
  'ServerGetRunStatusRequest': payload.ServerGetRunStatusRequest.new,
  'ServerGetRunStatusResponse': payload.ServerGetRunStatusResponse.new,
  'ServerGetRunWorkspaceMemoryStatsRequest':
      payload.ServerGetRunWorkspaceMemoryStatsRequest.new,
  'ServerGetRunWorkspaceMemoryStatsResponse':
      payload.ServerGetRunWorkspaceMemoryStatsResponse.new,
  'ServerGetRunWorkspaceRequest': payload.ServerGetRunWorkspaceRequest.new,
  'ServerGetRunWorkspaceResponse': payload.ServerGetRunWorkspaceResponse.new,
  'ServerGetRuntimeRequest': payload.ServerGetRuntimeRequest.new,
  'ServerGetRuntimeResponse': payload.ServerGetRuntimeResponse.new,
  'ServerGetStatusRequest': payload.ServerGetStatusRequest.new,
  'ServerGetStatusResponse': payload.ServerGetStatusResponse.new,
  'ServerListRunWorkspaceHistoryRequest':
      payload.ServerListRunWorkspaceHistoryRequest.new,
  'ServerListRunWorkspaceHistoryResponse':
      payload.ServerListRunWorkspaceHistoryResponse.new,
  'ServerPeerAssignRequest': payload.ServerPeerAssignRequest.new,
  'ServerPeerAssignResponse': payload.ServerPeerAssignResponse.new,
  'ServerPeerDeleteRequest': payload.ServerPeerDeleteRequest.new,
  'ServerPeerDeleteResponse': payload.ServerPeerDeleteResponse.new,
  'ServerPeerLookupRequest': payload.ServerPeerLookupRequest.new,
  'ServerPeerLookupResponse': payload.ServerPeerLookupResponse.new,
  'ServerPetActionsGetRequest': payload.ServerPetActionsGetRequest.new,
  'ServerPetActionsGetResponse': payload.ServerPetActionsGetResponse.new,
  'ServerPetDeleteRequest': payload.ServerPetDeleteRequest.new,
  'ServerPetDeleteResponse': payload.ServerPetDeleteResponse.new,
  'ServerPetDriveRequest': payload.ServerPetDriveRequest.new,
  'ServerPetDriveResponse': payload.ServerPetDriveResponse.new,
  'ServerPetGetRequest': payload.ServerPetGetRequest.new,
  'ServerPetGetResponse': payload.ServerPetGetResponse.new,
  'ServerPetListRequest': payload.ServerPetListRequest.new,
  'ServerPetListResponse': payload.ServerPetListResponse.new,
  'ServerPetPixaDownloadRequest': payload.ServerPetPixaDownloadRequest.new,
  'ServerPetPixaDownloadResponse': payload.ServerPetPixaDownloadResponse.new,
  'ServerPetPutRequest': payload.ServerPetPutRequest.new,
  'ServerPetPutResponse': payload.ServerPetPutResponse.new,
  'ServerPlayRunWorkspaceHistoryRequest':
      payload.ServerPlayRunWorkspaceHistoryRequest.new,
  'ServerPlayRunWorkspaceHistoryResponse':
      payload.ServerPlayRunWorkspaceHistoryResponse.new,
  'ServerPointsGetRequest': payload.ServerPointsGetRequest.new,
  'ServerPointsGetResponse': payload.ServerPointsGetResponse.new,
  'ServerPointsTransactionGetRequest':
      payload.ServerPointsTransactionGetRequest.new,
  'ServerPointsTransactionGetResponse':
      payload.ServerPointsTransactionGetResponse.new,
  'ServerPointsTransactionListRequest':
      payload.ServerPointsTransactionListRequest.new,
  'ServerPointsTransactionListResponse':
      payload.ServerPointsTransactionListResponse.new,
  'ServerPutInfoRequest': payload.ServerPutInfoRequest.new,
  'ServerPutInfoResponse': payload.ServerPutInfoResponse.new,
  'ServerRegisterRequest': payload.ServerRegisterRequest.new,
  'ServerRegisterResponse': payload.ServerRegisterResponse.new,
  'ServerReloadRunRequest': payload.ServerReloadRunRequest.new,
  'ServerReloadRunResponse': payload.ServerReloadRunResponse.new,
  'ServerReloadRunWorkspaceRequest':
      payload.ServerReloadRunWorkspaceRequest.new,
  'ServerReloadRunWorkspaceResponse':
      payload.ServerReloadRunWorkspaceResponse.new,
  'ServerRewardGrantGetRequest': payload.ServerRewardGrantGetRequest.new,
  'ServerRewardGrantGetResponse': payload.ServerRewardGrantGetResponse.new,
  'ServerRewardGrantListRequest': payload.ServerRewardGrantListRequest.new,
  'ServerRewardGrantListResponse': payload.ServerRewardGrantListResponse.new,
  'ServerRouteResolveRequest': payload.ServerRouteResolveRequest.new,
  'ServerRouteResolveResponse': payload.ServerRouteResolveResponse.new,
  'ServerRunSayRequest': payload.ServerRunSayRequest.new,
  'ServerRunSayResponse': payload.ServerRunSayResponse.new,
  'ServerRunWorkspaceRecallRequest':
      payload.ServerRunWorkspaceRecallRequest.new,
  'ServerRunWorkspaceRecallResponse':
      payload.ServerRunWorkspaceRecallResponse.new,
  'ServerSetRunAgentRequest': payload.ServerSetRunAgentRequest.new,
  'ServerSetRunAgentResponse': payload.ServerSetRunAgentResponse.new,
  'ServerSetRunWorkspaceRequest': payload.ServerSetRunWorkspaceRequest.new,
  'ServerSetRunWorkspaceResponse': payload.ServerSetRunWorkspaceResponse.new,
  'ServerStopRunRequest': payload.ServerStopRunRequest.new,
  'ServerStopRunResponse': payload.ServerStopRunResponse.new,
  'SpeechSynthesizeRequest': payload.SpeechSynthesizeRequest.new,
  'SpeechSynthesizeResponse': payload.SpeechSynthesizeResponse.new,
  'SpeechTranscribeRequest': payload.SpeechTranscribeRequest.new,
  'SpeechTranscribeResponse': payload.SpeechTranscribeResponse.new,
  'SpeedTestRequest': payload.SpeedTestRequest.new,
  'SpeedTestResponse': payload.SpeedTestResponse.new,
  'ToolGetRequest': payload.ToolGetRequest.new,
  'ToolGetResponse': payload.ToolGetResponse.new,
  'ToolInvokeRequest': payload.ToolInvokeRequest.new,
  'ToolInvokeResponse': payload.ToolInvokeResponse.new,
  'ToolListRequest': payload.ToolListRequest.new,
  'ToolListResponse': payload.ToolListResponse.new,
  'VoiceGetRequest': payload.VoiceGetRequest.new,
  'VoiceGetResponse': payload.VoiceGetResponse.new,
  'VoiceListRequest': payload.VoiceListRequest.new,
  'VoiceListResponse': payload.VoiceListResponse.new,
  'WorkflowGetRequest': payload.WorkflowGetRequest.new,
  'WorkflowGetResponse': payload.WorkflowGetResponse.new,
  'WorkflowListRequest': payload.WorkflowListRequest.new,
  'WorkflowListResponse': payload.WorkflowListResponse.new,
  'WorkspaceCreateRequest': payload.WorkspaceCreateRequest.new,
  'WorkspaceCreateResponse': payload.WorkspaceCreateResponse.new,
  'WorkspaceDeleteRequest': payload.WorkspaceDeleteRequest.new,
  'WorkspaceDeleteResponse': payload.WorkspaceDeleteResponse.new,
  'WorkspaceGetRequest': payload.WorkspaceGetRequest.new,
  'WorkspaceGetResponse': payload.WorkspaceGetResponse.new,
  'WorkspaceHistoryAudioGetRequest':
      payload.WorkspaceHistoryAudioGetRequest.new,
  'WorkspaceHistoryAudioGetResponse':
      payload.WorkspaceHistoryAudioGetResponse.new,
  'WorkspaceHistoryGetRequest': payload.WorkspaceHistoryGetRequest.new,
  'WorkspaceHistoryGetResponse': payload.WorkspaceHistoryGetResponse.new,
  'WorkspaceHistoryListRequest': payload.WorkspaceHistoryListRequest.new,
  'WorkspaceHistoryListResponse': payload.WorkspaceHistoryListResponse.new,
  'WorkspaceIconDownloadRequest': payload.WorkspaceIconDownloadRequest.new,
  'WorkspaceIconDownloadResponse': payload.WorkspaceIconDownloadResponse.new,
  'WorkspaceListRequest': payload.WorkspaceListRequest.new,
  'WorkspaceListResponse': payload.WorkspaceListResponse.new,
  'WorkspacePutRequest': payload.WorkspacePutRequest.new,
  'WorkspacePutResponse': payload.WorkspacePutResponse.new,
};

final _messageTypes = <String, Type>{
  'BadgeDefPixaDownloadRequest': payload.BadgeDefPixaDownloadRequest,
  'BadgeDefPixaDownloadResponse': payload.BadgeDefPixaDownloadResponse,
  'ClientGetIdentifiersRequest': payload.ClientGetIdentifiersRequest,
  'ClientGetIdentifiersResponse': payload.ClientGetIdentifiersResponse,
  'ClientGetInfoRequest': payload.ClientGetInfoRequest,
  'ClientGetInfoResponse': payload.ClientGetInfoResponse,
  'ContactCreateRequest': payload.ContactCreateRequest,
  'ContactCreateResponse': payload.ContactCreateResponse,
  'ContactDeleteRequest': payload.ContactDeleteRequest,
  'ContactDeleteResponse': payload.ContactDeleteResponse,
  'ContactGetRequest': payload.ContactGetRequest,
  'ContactGetResponse': payload.ContactGetResponse,
  'ContactListRequest': payload.ContactListRequest,
  'ContactListResponse': payload.ContactListResponse,
  'ContactPutRequest': payload.ContactPutRequest,
  'ContactPutResponse': payload.ContactPutResponse,
  'FirmwareFilesDownloadRequest': payload.FirmwareFilesDownloadRequest,
  'FirmwareFilesDownloadResponse': payload.FirmwareFilesDownloadResponse,
  'FirmwareGetRequest': payload.FirmwareGetRequest,
  'FirmwareGetResponse': payload.FirmwareGetResponse,
  'FriendAddRequest': payload.FriendAddRequest,
  'FriendAddResponse': payload.FriendAddResponse,
  'FriendDeleteRequest': payload.FriendDeleteRequest,
  'FriendDeleteResponse': payload.FriendDeleteResponse,
  'FriendGroupCreateRequest': payload.FriendGroupCreateRequest,
  'FriendGroupCreateResponse': payload.FriendGroupCreateResponse,
  'FriendGroupDeleteRequest': payload.FriendGroupDeleteRequest,
  'FriendGroupDeleteResponse': payload.FriendGroupDeleteResponse,
  'FriendGroupGetRequest': payload.FriendGroupGetRequest,
  'FriendGroupGetResponse': payload.FriendGroupGetResponse,
  'FriendGroupInviteTokenClearRequest':
      payload.FriendGroupInviteTokenClearRequest,
  'FriendGroupInviteTokenClearResponse':
      payload.FriendGroupInviteTokenClearResponse,
  'FriendGroupInviteTokenCreateRequest':
      payload.FriendGroupInviteTokenCreateRequest,
  'FriendGroupInviteTokenCreateResponse':
      payload.FriendGroupInviteTokenCreateResponse,
  'FriendGroupInviteTokenGetRequest': payload.FriendGroupInviteTokenGetRequest,
  'FriendGroupInviteTokenGetResponse':
      payload.FriendGroupInviteTokenGetResponse,
  'FriendGroupJoinRequest': payload.FriendGroupJoinRequest,
  'FriendGroupJoinResponse': payload.FriendGroupJoinResponse,
  'FriendGroupListRequest': payload.FriendGroupListRequest,
  'FriendGroupListResponse': payload.FriendGroupListResponse,
  'FriendGroupMemberAddRequest': payload.FriendGroupMemberAddRequest,
  'FriendGroupMemberAddResponse': payload.FriendGroupMemberAddResponse,
  'FriendGroupMemberDeleteRequest': payload.FriendGroupMemberDeleteRequest,
  'FriendGroupMemberDeleteResponse': payload.FriendGroupMemberDeleteResponse,
  'FriendGroupMemberListRequest': payload.FriendGroupMemberListRequest,
  'FriendGroupMemberListResponse': payload.FriendGroupMemberListResponse,
  'FriendGroupMemberPutRequest': payload.FriendGroupMemberPutRequest,
  'FriendGroupMemberPutResponse': payload.FriendGroupMemberPutResponse,
  'FriendGroupMessageGetRequest': payload.FriendGroupMessageGetRequest,
  'FriendGroupMessageGetResponse': payload.FriendGroupMessageGetResponse,
  'FriendGroupMessageListRequest': payload.FriendGroupMessageListRequest,
  'FriendGroupMessageListResponse': payload.FriendGroupMessageListResponse,
  'FriendGroupMessageSendRequest': payload.FriendGroupMessageSendRequest,
  'FriendGroupMessageSendResponse': payload.FriendGroupMessageSendResponse,
  'FriendGroupPutRequest': payload.FriendGroupPutRequest,
  'FriendGroupPutResponse': payload.FriendGroupPutResponse,
  'FriendInfoGetRequest': payload.FriendInfoGetRequest,
  'FriendInfoGetResponse': payload.FriendInfoGetResponse,
  'FriendInviteTokenClearRequest': payload.FriendInviteTokenClearRequest,
  'FriendInviteTokenClearResponse': payload.FriendInviteTokenClearResponse,
  'FriendInviteTokenCreateRequest': payload.FriendInviteTokenCreateRequest,
  'FriendInviteTokenCreateResponse': payload.FriendInviteTokenCreateResponse,
  'FriendInviteTokenGetRequest': payload.FriendInviteTokenGetRequest,
  'FriendInviteTokenGetResponse': payload.FriendInviteTokenGetResponse,
  'FriendListRequest': payload.FriendListRequest,
  'FriendListResponse': payload.FriendListResponse,
  'ModelGetRequest': payload.ModelGetRequest,
  'ModelGetResponse': payload.ModelGetResponse,
  'ModelListRequest': payload.ModelListRequest,
  'ModelListResponse': payload.ModelListResponse,
  'PingRequest': payload.PingRequest,
  'PingResponse': payload.PingResponse,
  'RuntimeAdoptRequest': payload.RuntimeAdoptRequest,
  'RuntimeAdoptResponse': payload.RuntimeAdoptResponse,
  'ServerBadgeGetRequest': payload.ServerBadgeGetRequest,
  'ServerBadgeGetResponse': payload.ServerBadgeGetResponse,
  'ServerBadgeListRequest': payload.ServerBadgeListRequest,
  'ServerBadgeListResponse': payload.ServerBadgeListResponse,
  'ServerGameResultGetRequest': payload.ServerGameResultGetRequest,
  'ServerGameResultGetResponse': payload.ServerGameResultGetResponse,
  'ServerGameResultListRequest': payload.ServerGameResultListRequest,
  'ServerGameResultListResponse': payload.ServerGameResultListResponse,
  'ServerGetInfoRequest': payload.ServerGetInfoRequest,
  'ServerGetInfoResponse': payload.ServerGetInfoResponse,
  'ServerGetRunAgentRequest': payload.ServerGetRunAgentRequest,
  'ServerGetRunAgentResponse': payload.ServerGetRunAgentResponse,
  'ServerGetRunStatusRequest': payload.ServerGetRunStatusRequest,
  'ServerGetRunStatusResponse': payload.ServerGetRunStatusResponse,
  'ServerGetRunWorkspaceMemoryStatsRequest':
      payload.ServerGetRunWorkspaceMemoryStatsRequest,
  'ServerGetRunWorkspaceMemoryStatsResponse':
      payload.ServerGetRunWorkspaceMemoryStatsResponse,
  'ServerGetRunWorkspaceRequest': payload.ServerGetRunWorkspaceRequest,
  'ServerGetRunWorkspaceResponse': payload.ServerGetRunWorkspaceResponse,
  'ServerGetRuntimeRequest': payload.ServerGetRuntimeRequest,
  'ServerGetRuntimeResponse': payload.ServerGetRuntimeResponse,
  'ServerGetStatusRequest': payload.ServerGetStatusRequest,
  'ServerGetStatusResponse': payload.ServerGetStatusResponse,
  'ServerListRunWorkspaceHistoryRequest':
      payload.ServerListRunWorkspaceHistoryRequest,
  'ServerListRunWorkspaceHistoryResponse':
      payload.ServerListRunWorkspaceHistoryResponse,
  'ServerPeerAssignRequest': payload.ServerPeerAssignRequest,
  'ServerPeerAssignResponse': payload.ServerPeerAssignResponse,
  'ServerPeerDeleteRequest': payload.ServerPeerDeleteRequest,
  'ServerPeerDeleteResponse': payload.ServerPeerDeleteResponse,
  'ServerPeerLookupRequest': payload.ServerPeerLookupRequest,
  'ServerPeerLookupResponse': payload.ServerPeerLookupResponse,
  'ServerPetActionsGetRequest': payload.ServerPetActionsGetRequest,
  'ServerPetActionsGetResponse': payload.ServerPetActionsGetResponse,
  'ServerPetDeleteRequest': payload.ServerPetDeleteRequest,
  'ServerPetDeleteResponse': payload.ServerPetDeleteResponse,
  'ServerPetDriveRequest': payload.ServerPetDriveRequest,
  'ServerPetDriveResponse': payload.ServerPetDriveResponse,
  'ServerPetGetRequest': payload.ServerPetGetRequest,
  'ServerPetGetResponse': payload.ServerPetGetResponse,
  'ServerPetListRequest': payload.ServerPetListRequest,
  'ServerPetListResponse': payload.ServerPetListResponse,
  'ServerPetPixaDownloadRequest': payload.ServerPetPixaDownloadRequest,
  'ServerPetPixaDownloadResponse': payload.ServerPetPixaDownloadResponse,
  'ServerPetPutRequest': payload.ServerPetPutRequest,
  'ServerPetPutResponse': payload.ServerPetPutResponse,
  'ServerPlayRunWorkspaceHistoryRequest':
      payload.ServerPlayRunWorkspaceHistoryRequest,
  'ServerPlayRunWorkspaceHistoryResponse':
      payload.ServerPlayRunWorkspaceHistoryResponse,
  'ServerPointsGetRequest': payload.ServerPointsGetRequest,
  'ServerPointsGetResponse': payload.ServerPointsGetResponse,
  'ServerPointsTransactionGetRequest':
      payload.ServerPointsTransactionGetRequest,
  'ServerPointsTransactionGetResponse':
      payload.ServerPointsTransactionGetResponse,
  'ServerPointsTransactionListRequest':
      payload.ServerPointsTransactionListRequest,
  'ServerPointsTransactionListResponse':
      payload.ServerPointsTransactionListResponse,
  'ServerPutInfoRequest': payload.ServerPutInfoRequest,
  'ServerPutInfoResponse': payload.ServerPutInfoResponse,
  'ServerRegisterRequest': payload.ServerRegisterRequest,
  'ServerRegisterResponse': payload.ServerRegisterResponse,
  'ServerReloadRunRequest': payload.ServerReloadRunRequest,
  'ServerReloadRunResponse': payload.ServerReloadRunResponse,
  'ServerReloadRunWorkspaceRequest': payload.ServerReloadRunWorkspaceRequest,
  'ServerReloadRunWorkspaceResponse': payload.ServerReloadRunWorkspaceResponse,
  'ServerRewardGrantGetRequest': payload.ServerRewardGrantGetRequest,
  'ServerRewardGrantGetResponse': payload.ServerRewardGrantGetResponse,
  'ServerRewardGrantListRequest': payload.ServerRewardGrantListRequest,
  'ServerRewardGrantListResponse': payload.ServerRewardGrantListResponse,
  'ServerRouteResolveRequest': payload.ServerRouteResolveRequest,
  'ServerRouteResolveResponse': payload.ServerRouteResolveResponse,
  'ServerRunSayRequest': payload.ServerRunSayRequest,
  'ServerRunSayResponse': payload.ServerRunSayResponse,
  'ServerRunWorkspaceRecallRequest': payload.ServerRunWorkspaceRecallRequest,
  'ServerRunWorkspaceRecallResponse': payload.ServerRunWorkspaceRecallResponse,
  'ServerSetRunAgentRequest': payload.ServerSetRunAgentRequest,
  'ServerSetRunAgentResponse': payload.ServerSetRunAgentResponse,
  'ServerSetRunWorkspaceRequest': payload.ServerSetRunWorkspaceRequest,
  'ServerSetRunWorkspaceResponse': payload.ServerSetRunWorkspaceResponse,
  'ServerStopRunRequest': payload.ServerStopRunRequest,
  'ServerStopRunResponse': payload.ServerStopRunResponse,
  'SpeechSynthesizeRequest': payload.SpeechSynthesizeRequest,
  'SpeechSynthesizeResponse': payload.SpeechSynthesizeResponse,
  'SpeechTranscribeRequest': payload.SpeechTranscribeRequest,
  'SpeechTranscribeResponse': payload.SpeechTranscribeResponse,
  'SpeedTestRequest': payload.SpeedTestRequest,
  'SpeedTestResponse': payload.SpeedTestResponse,
  'ToolGetRequest': payload.ToolGetRequest,
  'ToolGetResponse': payload.ToolGetResponse,
  'ToolInvokeRequest': payload.ToolInvokeRequest,
  'ToolInvokeResponse': payload.ToolInvokeResponse,
  'ToolListRequest': payload.ToolListRequest,
  'ToolListResponse': payload.ToolListResponse,
  'VoiceGetRequest': payload.VoiceGetRequest,
  'VoiceGetResponse': payload.VoiceGetResponse,
  'VoiceListRequest': payload.VoiceListRequest,
  'VoiceListResponse': payload.VoiceListResponse,
  'WorkflowGetRequest': payload.WorkflowGetRequest,
  'WorkflowGetResponse': payload.WorkflowGetResponse,
  'WorkflowListRequest': payload.WorkflowListRequest,
  'WorkflowListResponse': payload.WorkflowListResponse,
  'WorkspaceCreateRequest': payload.WorkspaceCreateRequest,
  'WorkspaceCreateResponse': payload.WorkspaceCreateResponse,
  'WorkspaceDeleteRequest': payload.WorkspaceDeleteRequest,
  'WorkspaceDeleteResponse': payload.WorkspaceDeleteResponse,
  'WorkspaceGetRequest': payload.WorkspaceGetRequest,
  'WorkspaceGetResponse': payload.WorkspaceGetResponse,
  'WorkspaceHistoryAudioGetRequest': payload.WorkspaceHistoryAudioGetRequest,
  'WorkspaceHistoryAudioGetResponse': payload.WorkspaceHistoryAudioGetResponse,
  'WorkspaceHistoryGetRequest': payload.WorkspaceHistoryGetRequest,
  'WorkspaceHistoryGetResponse': payload.WorkspaceHistoryGetResponse,
  'WorkspaceHistoryListRequest': payload.WorkspaceHistoryListRequest,
  'WorkspaceHistoryListResponse': payload.WorkspaceHistoryListResponse,
  'WorkspaceIconDownloadRequest': payload.WorkspaceIconDownloadRequest,
  'WorkspaceIconDownloadResponse': payload.WorkspaceIconDownloadResponse,
  'WorkspaceListRequest': payload.WorkspaceListRequest,
  'WorkspaceListResponse': payload.WorkspaceListResponse,
  'WorkspacePutRequest': payload.WorkspacePutRequest,
  'WorkspacePutResponse': payload.WorkspacePutResponse,
};

GeneratedMessage newPayloadMessage(String type) {
  final factory = _messageFactories[type];
  if (factory == null) {
    throw ArgumentError.value(type, 'type', 'unknown RPC payload type');
  }
  return factory();
}

List<int> encodeRpcRequestPayload(String methodName, GeneratedMessage message) {
  final expected = rpcMethodByName(methodName).requestType;
  _expectPayloadType(expected, message);
  return message.writeToBuffer();
}

GeneratedMessage decodeRpcRequestPayload(String methodName, List<int> bytes) {
  final type = rpcMethodByName(methodName).requestType;
  final message = newPayloadMessage(type);
  message.mergeFromBuffer(bytes);
  return message;
}

List<int> encodeRpcResponsePayload(
  String methodName,
  GeneratedMessage message,
) {
  final expected = rpcMethodByName(methodName).responseType;
  _expectPayloadType(expected, message);
  return message.writeToBuffer();
}

GeneratedMessage decodeRpcResponsePayload(String methodName, List<int> bytes) {
  final type = rpcMethodByName(methodName).responseType;
  final message = newPayloadMessage(type);
  message.mergeFromBuffer(bytes);
  return message;
}

GeneratedMessage? decodeEmptyRpcResponsePayload(String methodName) {
  final type = rpcMethodByName(methodName).responseType;
  final message = newPayloadMessage(type);
  return message.info_.fieldInfo.isEmpty ? message : null;
}

void _expectPayloadType(String expected, GeneratedMessage message) {
  final expectedType = _messageTypes[expected];
  if (expectedType == null) {
    throw ArgumentError.value(expected, 'expected', 'unknown RPC payload type');
  }
  final actualType = message.runtimeType;
  if (actualType != expectedType) {
    throw ArgumentError(
      'RPC payload type mismatch: got $actualType, want $expected',
    );
  }
}
